%% --non-deterministic
  $ ocamlfind list | grep top
  astring.top         (version: 0.8.3)
  cohttp.top          (version: n/a)
  compiler-libs.toplevel (version: [distributed with Ocaml])
  core.top            (version: v0.10.0)
  ctypes.top          (version: 0.13.1)
  findlib.top         (version: 1.7.3)
  fmt.top             (version: 0.8.5)
  ipaddr.top          (version: 2.8.0)
  js_of_ocaml.toplevel (version: n/a)
  logs.top            (version: 0.6.2)
  lwt.simple-top      (version: 3.2.1)
  mtime.top           (version: 1.1.0)
  num-top             (version: 1.1)
  ocaml-compiler-libs.toplevel (version: v0.10.0)
  react.top           (version: 1.2.1)
  topkg               (version: 0.9.1)
  toplevel_expect_test (version: v0.10.0)
  toplevel_expect_test.types (version: v0.10.0)
  uri.top             (version: 1.9.6)
  utop                (version: 2.1.0)
