open Core.Std

module type Interval_intf = sig
  type t
  type endpoint
  val create : endpoint -> endpoint -> t
  val is_empty : t -> bool
  val contains : t -> endpoint -> bool
  val intersect : t -> t -> t
end

module type Interval_intf_with_sexp = sig
  type t
  include Interval_intf with type t := t
  include Sexpable      with type t := t
end

module Make_interval(C : sig
  type t
  include Comparable with type t := t
  include Sexpable   with type t := t
end)
  : Interval_intf_with_sexp with type endpoint := C.t = struct

    type t = | Interval of C.t * C.t
             | Empty
    with sexp

    let create low high =
      if C.compare low high > 0 then Empty
      else Interval (low,high)

    (* put a wrapper round the autogenerated sexp_of_t to enforce
       the invariants of the datastructure *)
    let t_of_sexp sexp =
      match t_of_sexp sexp with
      | Empty -> Empty
      | Interval (x,y) -> create x y

    let is_empty = function
      | Empty -> true
      | Interval _ -> false

    let contains t x =
      match t with
      | Empty -> false
      | Interval (l,h) ->
        C.compare x l >= 0 && C.compare x h <= 0

    let intersect t1 t2 =
      let min x y = if C.compare x y <= 0 then x else y in
      let max x y = if C.compare x y >= 0 then x else y in
      match t1,t2 with
      | Empty, _ | _, Empty -> Empty
      | Interval (l1,h1), Interval (l2,h2) ->
        create (max l1 l2) (min h1 h2)
  end
