(lang dune 2.8)

(name ocaml-compiler-libs)
(version v0.12.4)
(license MIT)
(maintainers "Jane Street developers")
(authors "Jane Street Group, LLC")
(source (github janestreet/ocaml-compiler-libs))

(package
 (name ocaml-compiler-libs)
 (depends
  (ocaml (>= 4.04.1)))
 (synopsis "OCaml compiler libraries repackaged")
 (description "\
This packages exposes the OCaml compiler libraries repackages under
the toplevel names Ocaml_common, Ocaml_bytecomp, Ocaml_optcomp, ..."))

(generate_opam_files true)
