(lang dune 2.9)
(using fmt 1.2 (enabled_for mlfi))

(dialect
 (name mlfi)
 (implementation
  (extension mf)
  (format (run fmt %{input-file})))
 (interface
  (extension mfi)
  (format (run fmt %{input-file}))))
