.PHONY: all app lib clean

all: app

lib:
	$(MAKE) -C lib

app: lib
	$(MAKE) -C app

################################################################################
# Install and Uninstall

OPAM_PACKAGE_NAME ?= Real-World-OCaml
export OPAM_PACKAGE_NAME

OCAMLFIND_PACKAGE_NAME = $(OPAM_PACKAGE_NAME)

################################################################################
# Clean Up

clean:
	$(MAKE) -C lib clean
	$(MAKE) -C app clean

include Makefile.shared
include Makefile.derived
