#!/usr/bin/env bash

ocamlbuild \
    -use-ocamlfind \
    -syntax camlp4o \
    -pkg core,core_extended,async,textutils,core_bench  \
    -pkg sexplib.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax \
    -pkg bin_prot.syntax \
    -tag thread \
    -tag debug \
    -cflags -strict-sequence \
    -cflags -principal \
    $@


