(lang dune 2.8)
(name odoc-parser)
(version 2.0.0) 

(generate_opam_files true)

(source (github ocaml-doc/odoc-parser))
(license ISC)
(authors "Anton Bachin <antonbachin@yahoo.com>")
(maintainers "Jon Ludlam <jon@recoil.org>")

(package
 (name odoc-parser)
 (synopsis "Parser for ocaml documentation comments")
 (description "Odoc_parser is a library for parsing the contents of OCaml documentation
comments, formatted using 'odoc' syntax, an extension of the language
understood by ocamldoc.")
 (depends
  dune
  (ocaml (>= 4.02.0))
  astring
  result
  camlp-streams
  (ppx_expect :with-test)))

