(* If a.ml and b.ml have the same nested module name generated by Bisect, this
   include will trigger a compilation error. *)
include A

(* If a.ml and b.ml have the same unscoped function name generated by Bisect,
   executing a.out will cause an Index out of bounds error. *)
let () =
  ();
  ();
  ()
