(lang dune 1.11)
(name octavius)

(generate_opam_files true)

(maintainers leo@lpw25.net)
(authors "Leo White <leo@lpw25.net>")
(source (github ocaml-doc/octavius))
(documentation http://ocaml-doc.github.io/octavius/)
(license ISC)

(package
 (name octavius)
 (depends (ocaml (>= 4.03.0)))
 (tags (doc ocamldoc org:ocaml-doc)))
