#!/usr/bin/env bash
# Designed for the Travis CI build environment. See .travis.yml

set -ex
export OPAMYES=1
export OPAMJOBS=2

if [ ! -d $HOME/.opam ]; then
  opam init -a --compiler 4.06.0
else
  opam update -u
fi
opam pin add jbuilder --dev
opam pin add -n rwo $TRAVIS_BUILD_DIR
opam install --deps-only rwo
opam update -u
