open! Core_kernel

(*_ Check that the signature generated by deriving quickcheck is able to unify with the
  corresponding implementation. *)
module Foo (X : sig
    type t

    include Comparable.S with type t := t
    include Quickcheckable with type t := t
  end) : sig
  type t1 = Set.M(X).t [@@deriving quickcheck]
  type t2 = unit Map.M(X).t [@@deriving quickcheck]
end
