Grammar has 14 nonterminal symbols, among which 1 start symbols.
Grammar has 17 terminal symbols.
Grammar has 35 productions.
nullable(stmttail) = false
nullable(stmt) = false
nullable(patom) = false
nullable(parse_io_module) = false
nullable(paramlisttail) = true
nullable(paramlist) = false
nullable(imports) = true
nullable(importlist) = true
nullable(idlist) = true
nullable(expr) = false
nullable(export) = true
nullable(eatom) = false
nullable(decll) = true
nullable(atom) = false
first(stmttail) = Lstring Lsemi Llpar Lint
first(stmt) = Llambda
first(patom) = Lstring Llpar Lint Lident
first(parse_io_module) = Lvariable Lprimitive Llambda Limport Lident Lexport Ldeclare
first(paramlisttail) = Lstring Lsemi Llpar Llambda Lint Lident
first(paramlist) = Lstring Lsemi Llpar Llambda Lint Lident
first(imports) = Limport
first(importlist) = Lcolon
first(idlist) = Lident
first(expr) = Llambda Lident
first(export) = Lexport
first(eatom) = Lstring Llpar Llambda Lint Lident
first(decll) = Lvariable Lprimitive Ldeclare
first(atom) = Lstring Llpar Lint
minimal(stmttail) = (* 1 *) Lint
minimal(stmt) = (* 2 *) Llambda Lint
minimal(patom) = (* 1 *) Lident
minimal(parse_io_module) = (* 2 *) Lident Lend
minimal(paramlisttail) = (* 0 *) 
minimal(paramlist) = (* 1 *) Lident
minimal(imports) = (* 0 *) 
minimal(importlist) = (* 0 *) 
minimal(idlist) = (* 0 *) 
minimal(expr) = (* 1 *) Lident
minimal(export) = (* 0 *) 
minimal(eatom) = (* 1 *) Lident
minimal(decll) = (* 0 *) 
minimal(atom) = (* 1 *) Lint
follow(stmttail) = Lrpar Lperiod Lend
follow(stmt) = Lrpar Lperiod Lend
follow(patom) = Lstring Lsemi Lrpar Lperiod Llpar Llambda Lint Lident Lend
follow(parse_io_module) = #
follow(paramlisttail) = Lrpar Lperiod Lend
follow(paramlist) = Lrpar Lperiod Lend
follow(imports) = Lvariable Lprimitive Llambda Lident Lexport Ldeclare
follow(importlist) = Lperiod
follow(idlist) = Lstring Lsemi Lperiod Llpar Lint
follow(expr) = Lrpar Lperiod Lend
follow(export) = Lvariable Lprimitive Llambda Lident Ldeclare
follow(eatom) = Lrpar Lperiod Lend
follow(decll) = Llambda Lident
follow(atom) = Lstring Lsemi Lrpar Lperiod Llpar Llambda Lint Lident Lend
Built an LR(0) automaton with 71 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 71 states.
29 out of 71 states have a default reduction.
24 out of 71 states are represented.
0 out of 34 symbols keep track of their start position.
0 out of 34 symbols keep track of their end position.
19 out of 36 productions exploit shiftreduce optimization.
0 out of 71 states can peek at an error.
198 functions before inlining, 33 functions after inlining.
