Grammar has 5 nonterminal symbols, among which 2 start symbols.
Grammar has 5 terminal symbols.
Grammar has 9 productions.
nullable(seplist(A)) = false
nullable(phrase) = false
nullable(other) = false
nullable(midrule(__anonymous_1)) = false
nullable(list(__anonymous_0(A,B))) = true
first(seplist(A)) = A
first(phrase) = C
first(other) = A
first(midrule(__anonymous_1)) = D C
first(list(__anonymous_0(A,B))) = B A
minimal(seplist(A)) = (* 1 *) A
minimal(phrase) = (* 3 *) C D EOF
minimal(other) = (* 2 *) A EOF
minimal(midrule(__anonymous_1)) = (* 1 *) C
minimal(list(__anonymous_0(A,B))) = (* 0 *) 
follow(seplist(A)) = EOF
follow(phrase) = #
follow(other) = #
follow(midrule(__anonymous_1)) = A
follow(list(__anonymous_0(A,B))) = EOF D
Built an LR(0) automaton with 20 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 20 states.
9 out of 20 states have a default reduction.
6 out of 20 states are represented.
0 out of 14 symbols keep track of their start position.
0 out of 14 symbols keep track of their end position.
6 out of 11 productions exploit shiftreduce optimization.
0 out of 20 states can peek at an error.
63 functions before inlining, 13 functions after inlining.
