%start phrase
%token <int> A
%token <int> B
%token <int> C
%token <int> D
%token <int> EOF
%type <int list> phrase
%%

list___anonymous_0_:
  
    {    ( [] )}
| x = A xs = list___anonymous_0_
    {let x =                                   ( x ) in
    ( x :: xs )}
| x = B xs = list___anonymous_0_
    {let x =                                   ( x ) in
    ( x :: xs )}
| x = C xs = list___anonymous_0_
    {let x =                                   ( x ) in
    ( x :: xs )}

list___anonymous_1_:
  
    {    ( [] )}
| x = D y = D xs = list___anonymous_1_
    {let x =                         ( x + y ) in
    ( x :: xs )}

phrase:
  xs = list___anonymous_0_ ys = list___anonymous_1_ _3 = EOF
    {    ( xs @ ys )}

%%


