Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 5 terminal symbols.
Grammar has 7 productions.
nullable(phrase) = false
nullable(list(__anonymous_1)) = true
nullable(list(__anonymous_0)) = true
first(phrase) = EOF D C B A
first(list(__anonymous_1)) = D
first(list(__anonymous_0)) = C B A
minimal(phrase) = (* 1 *) EOF
minimal(list(__anonymous_1)) = (* 0 *) 
minimal(list(__anonymous_0)) = (* 0 *) 
follow(phrase) = #
follow(list(__anonymous_1)) = EOF
follow(list(__anonymous_0)) = EOF D
Built an LR(0) automaton with 14 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 14 states.
6 out of 14 states have a default reduction.
6 out of 14 states are represented.
0 out of 11 symbols keep track of their start position.
0 out of 11 symbols keep track of their end position.
2 out of 8 productions exploit shiftreduce optimization.
0 out of 14 states can peek at an error.
45 functions before inlining, 12 functions after inlining.
