File "attapl-deptypes.mly", line 47, characters 28-38:
Warning: the token APOSTROPHE is unused.
File "attapl-deptypes.mly", line 49, characters 28-33:
Warning: the token BARGT is unused.
File "attapl-deptypes.mly", line 50, characters 28-37:
Warning: the token BARRCURLY is unused.
File "attapl-deptypes.mly", line 51, characters 28-38:
Warning: the token BARRSQUARE is unused.
File "attapl-deptypes.mly", line 53, characters 28-38:
Warning: the token COLONCOLON is unused.
File "attapl-deptypes.mly", line 54, characters 28-35:
Warning: the token COLONEQ is unused.
File "attapl-deptypes.mly", line 55, characters 28-37:
Warning: the token COLONHASH is unused.
File "attapl-deptypes.mly", line 57, characters 28-34:
Warning: the token DARROW is unused.
File "attapl-deptypes.mly", line 59, characters 28-35:
Warning: the token DDARROW is unused.
File "attapl-deptypes.mly", line 48, characters 28-34:
Warning: the token DQUOTE is unused.
File "attapl-deptypes.mly", line 63, characters 28-32:
Warning: the token EQEQ is unused.
File "attapl-deptypes.mly", line 64, characters 28-30:
Warning: the token GT is unused.
File "attapl-deptypes.mly", line 65, characters 28-32:
Warning: the token HASH is unused.
File "attapl-deptypes.mly", line 66, characters 28-34:
Warning: the token LCURLY is unused.
File "attapl-deptypes.mly", line 67, characters 28-37:
Warning: the token LCURLYBAR is unused.
File "attapl-deptypes.mly", line 68, characters 28-37:
Warning: the token LEFTARROW is unused.
File "attapl-deptypes.mly", line 71, characters 28-35:
Warning: the token LSQUARE is unused.
File "attapl-deptypes.mly", line 72, characters 28-38:
Warning: the token LSQUAREBAR is unused.
File "attapl-deptypes.mly", line 73, characters 28-30:
Warning: the token LT is unused.
File "attapl-deptypes.mly", line 70, characters 28-34:
Warning: the token Normal is unused.
File "attapl-deptypes.mly", line 74, characters 28-34:
Warning: the token RCURLY is unused.
File "attapl-deptypes.mly", line 76, characters 28-35:
Warning: the token RSQUARE is unused.
File "attapl-deptypes.mly", line 78, characters 28-33:
Warning: the token SLASH is unused.
File "attapl-deptypes.mly", line 80, characters 28-36:
Warning: the token TRIANGLE is unused.
File "attapl-deptypes.mly", line 30, characters 28-32:
Warning: the token TYPE is unused.
File "attapl-deptypes.mly", line 82, characters 28-32:
Warning: the token VBAR is unused.
Grammar has 15 nonterminal symbols, among which 1 start symbols.
Grammar has 50 terminal symbols.
Grammar has 42 productions.
nullable(toplevel) = false
nullable(Type) = false
nullable(TyBinder) = false
nullable(TermList) = false
nullable(Term) = false
nullable(PathTerm) = false
nullable(Kind) = false
nullable(Command) = false
nullable(Binder) = false
nullable(ArrowKind) = false
nullable(AppType) = false
nullable(AppTerm) = false
nullable(AType) = false
nullable(ATerm) = false
nullable(AKind) = false
first(toplevel) = UCID LPAREN LCID LAMBDA IMPORT EOF ALL
first(Type) = UCID SIGMA PROP PRF PI LPAREN
first(TyBinder) = EQ COLON
first(TermList) = LPAREN LCID LAMBDA ALL
first(Term) = LPAREN LCID LAMBDA ALL
first(PathTerm) = LPAREN LCID
first(Kind) = UCID STAR PROP PRF PI LPAREN
first(Command) = UCID LPAREN LCID LAMBDA IMPORT ALL
first(Binder) = EQ COLON
first(ArrowKind) = UCID STAR PROP PRF LPAREN
first(AppType) = UCID PROP PRF LPAREN
first(AppTerm) = LPAREN LCID
first(AType) = UCID PROP PRF LPAREN
first(ATerm) = LPAREN LCID
first(AKind) = STAR LPAREN
minimal(toplevel) = (* 1 *) EOF
minimal(Type) = (* 1 *) PROP
minimal(TyBinder) = (* 2 *) COLON STAR
minimal(TermList) = (* 1 *) LCID
minimal(Term) = (* 1 *) LCID
minimal(PathTerm) = (* 1 *) LCID
minimal(Kind) = (* 1 *) STAR
minimal(Command) = (* 1 *) LCID
minimal(Binder) = (* 2 *) COLON PROP
minimal(ArrowKind) = (* 1 *) STAR
minimal(AppType) = (* 1 *) PROP
minimal(AppTerm) = (* 1 *) LCID
minimal(AType) = (* 1 *) PROP
minimal(ATerm) = (* 1 *) LCID
minimal(AKind) = (* 1 *) STAR
follow(toplevel) = #
follow(Type) = SEMI RPAREN DOT
follow(TyBinder) = SEMI
follow(TermList) = COLON
follow(Term) = SEMI RPAREN COMMA COLON
follow(PathTerm) = SEMI RPAREN LPAREN LCID DOT COMMA COLON
follow(Kind) = SEMI RPAREN
follow(Command) = SEMI
follow(Binder) = SEMI
follow(ArrowKind) = SEMI RPAREN
follow(AppType) = SEMI RPAREN LPAREN LCID DOT ARROW
follow(AppTerm) = SEMI RPAREN LPAREN LCID COMMA COLON
follow(AType) = SEMI RPAREN LPAREN LCID DOT ARROW
follow(ATerm) = SEMI RPAREN LPAREN LCID DOT COMMA COLON ARROW
follow(AKind) = SEMI RPAREN
Built an LR(0) automaton with 111 states.
The grammar is not SLR(1) -- 1 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 111 states.
File "attapl-deptypes.mly", line 84, characters 0-6:
Warning: the precedence level assigned to COMMA is never useful.
38 out of 111 states have a default reduction.
37 out of 111 states are represented.
0 out of 68 symbols keep track of their start position.
0 out of 68 symbols keep track of their end position.
24 out of 43 productions exploit shiftreduce optimization.
0 out of 111 states can peek at an error.
286 functions before inlining, 40 functions after inlining.
