%start main
%token A
%token B
%token C
%type <unit> main
%%

main:
  _1 = liste_A_ _2 = liste_B_ _3 = liste_C_
    {    ()}

liste_A_ [@liste.A true] [@happy true] [@liste true]:
  x = A xs = liste_A_
    {                      ( x :: xs )}
| 
    {                      ( [] )}

liste_B_ [@happy true] [@liste true]:
  x = B xs = liste_B_
    {                      ( x :: xs )}
| 
    {                      ( [] )}

liste_C_ [@happy true] [@liste true]:
  x = C xs = liste_C_
    {                      ( x :: xs )}
| 
    {                      ( [] )}

%%


