Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 5 terminal symbols.
Grammar has 7 productions.
nullable(exprl) = true
nullable(expr) = false
nullable(desc) = false
first(exprl) = SIZE BANG
first(expr) = LOG
first(desc) = SIZE BANG ARROW
minimal(exprl) = (* 0 *) 
minimal(expr) = (* 1 *) LOG
minimal(desc) = (* 3 *) ARROW LOG EOF
follow(exprl) = SIZE EOF BANG ARROW
follow(expr) = SIZE EOF BANG
follow(desc) = #
Built an LR(0) automaton with 14 states.
The grammar is not SLR(1) -- 4 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 14 states.
3 shift/reduce conflicts were silently solved.
Warning: 3 states have shift/reduce conflicts.
1 conflict could not be explained.
Warning: 3 shift/reduce conflicts were arbitrarily resolved.
7 out of 14 states have a default reduction.
4 out of 14 states are represented.
0 out of 11 symbols keep track of their start position.
0 out of 11 symbols keep track of their end position.
4 out of 8 productions exploit shiftreduce optimization.
0 out of 14 states can peek at an error.
45 functions before inlining, 7 functions after inlining.
