File "bibtex2html.1.99-bibtex_parser.mly", line 46, characters 25-32:
Warning: the token Tlbrace is unused.
Grammar has 9 nonterminal symbols, among which 2 start symbols.
Grammar has 12 terminal symbols.
Grammar has 19 productions.
nullable(sharp_string_list) = false
nullable(field_name) = false
nullable(field) = false
nullable(entry) = false
nullable(commands) = true
nullable(command_list) = false
nullable(command) = false
nullable(comma_field_list) = false
nullable(atom) = false
first(sharp_string_list) = Tstring Tident
first(field_name) = Tident Tcomment
first(field) = Tident Tcomment
first(entry) = Tentry
first(commands) = Tpreamble Tentry Tcomment Tabbrev
first(command_list) = Tpreamble Tentry Tcomment Tabbrev EOF
first(command) = Tpreamble Tentry Tcomment Tabbrev
first(comma_field_list) = Tident Tcomment
first(atom) = Tstring Tident
minimal(sharp_string_list) = (* 1 *) Tident
minimal(field_name) = (* 1 *) Tident
minimal(field) = (* 2 *) Tident Tequal
minimal(entry) = (* 1 *) Tentry
minimal(commands) = (* 0 *) 
minimal(command_list) = (* 1 *) EOF
minimal(command) = (* 1 *) Tcomment
minimal(comma_field_list) = (* 2 *) Tident Tequal
minimal(atom) = (* 1 *) Tident
follow(sharp_string_list) = Trbrace Tcomma
follow(field_name) = Tequal
follow(field) = Trbrace Tcomma
follow(entry) = Tcomma
follow(commands) = Tpreamble Tentry Tcomment Tabbrev EOF
follow(command_list) = #
follow(command) = Tpreamble Tentry Tcomment Tabbrev EOF #
follow(comma_field_list) = Trbrace
follow(atom) = Tsharp Trbrace Tcomma
Built an LR(0) automaton with 34 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 47 states.
21 out of 47 states have a default reduction.
11 out of 47 states are represented.
0 out of 25 symbols keep track of their start position.
0 out of 25 symbols keep track of their end position.
13 out of 21 productions exploit shiftreduce optimization.
0 out of 47 states can peek at an error.
131 functions before inlining, 22 functions after inlining.
