Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 3 terminal symbols.
Grammar has 7 productions.
nullable(inst) = false
nullable(expr) = false
nullable(debut) = false
first(inst) = SEP LIDENT
first(expr) = SEP LIDENT
first(debut) = SEP LIDENT
minimal(inst) = (* 2 *) LIDENT LIDENT
minimal(expr) = (* 1 *) LIDENT
minimal(debut) = (* 2 *) LIDENT DOT
follow(inst) = SEP LIDENT DOT
follow(expr) = SEP LIDENT DOT
follow(debut) = #
Built an LR(0) automaton with 14 states.
The grammar is not SLR(1) -- 6 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 16 states.
Warning: 4 states have shift/reduce conflicts.
Warning: 3 states have reduce/reduce conflicts.
Warning: 5 shift/reduce conflicts were arbitrarily resolved.
Warning: 3 reduce/reduce conflicts were arbitrarily resolved.
Warning: one state has an end-of-stream conflict.
File "boris-mini.mly", line 38, characters 2-10:
Warning: production debut -> expr DOT is never reduced.
Warning: in total, 1 production is never reduced.
3 out of 16 states have a default reduction.
8 out of 16 states are represented.
0 out of 9 symbols keep track of their start position.
0 out of 9 symbols keep track of their end position.
2 out of 8 productions exploit shiftreduce optimization.
0 out of 16 states can peek at an error.
48 functions before inlining, 13 functions after inlining.
