Grammar has 4 nonterminal symbols, among which 1 start symbols.
Grammar has 8 terminal symbols.
Grammar has 10 productions.
nullable(main) = false
nullable(fold_left(multiplicative_op,atomic_expr)) = false
nullable(fold_left(additive_op,multiplicative_expr)) = false
nullable(atomic_expr) = false
first(main) = MINUS LPAREN INT
first(fold_left(multiplicative_op,atomic_expr)) = MINUS LPAREN INT
first(fold_left(additive_op,multiplicative_expr)) = MINUS LPAREN INT
first(atomic_expr) = MINUS LPAREN INT
minimal(main) = (* 2 *) INT EOL
minimal(fold_left(multiplicative_op,atomic_expr)) = (* 1 *) INT
minimal(fold_left(additive_op,multiplicative_expr)) = (* 1 *) INT
minimal(atomic_expr) = (* 1 *) INT
follow(main) = #
follow(fold_left(multiplicative_op,atomic_expr)) = TIMES RPAREN PLUS MINUS EOL DIV
follow(fold_left(additive_op,multiplicative_expr)) = RPAREN PLUS MINUS EOL
follow(atomic_expr) = TIMES RPAREN PLUS MINUS EOL DIV
Built an LR(0) automaton with 20 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 20 states.
8 out of 20 states have a default reduction.
7 out of 20 states are represented.
0 out of 15 symbols keep track of their start position.
0 out of 15 symbols keep track of their end position.
8 out of 11 productions exploit shiftreduce optimization.
0 out of 20 states can peek at an error.
61 functions before inlining, 14 functions after inlining.
