Grammar has 2 nonterminal symbols, among which 1 start symbols.
Grammar has 8 terminal symbols.
Grammar has 8 productions.
nullable(main) = false
nullable(expr) = false
first(main) = MINUS LPAREN INT
first(expr) = MINUS LPAREN INT
minimal(main) = (* 2 *) INT EOL
minimal(expr) = (* 1 *) INT
follow(main) = #
follow(expr) = TIMES RPAREN PLUS MINUS EOL DIV
Built an LR(0) automaton with 18 states.
The grammar is not SLR(1) -- 5 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 18 states.
20 shift/reduce conflicts were silently solved.
7 out of 18 states have a default reduction.
7 out of 18 states are represented.
4 out of 13 symbols keep track of their start position.
3 out of 13 symbols keep track of their end position.
4 out of 9 productions exploit shiftreduce optimization.
0 out of 18 states can peek at an error.
53 functions before inlining, 11 functions after inlining.
