Grammar has 8 nonterminal symbols, among which 1 start symbols.
Grammar has 10 terminal symbols.
Grammar has 24 productions.
nullable(ulist) = false
nullable(rules) = false
nullable(rule) = false
nullable(main) = false
nullable(init) = false
nullable(header_option) = false
nullable(header) = false
nullable(elem) = false
first(ulist) = UCHAR
first(rules) = RESET
first(rule) = RESET
first(main) = UCHAR RESET OPTION EOF
first(init) = UCHAR OPTION
first(header_option) = UCHAR OPTION
first(header) = UCHAR OPTION
first(elem) = UCHAR OPTION
minimal(ulist) = (* 1 *) UCHAR
minimal(rules) = (* 2 *) RESET UCHAR
minimal(rule) = (* 2 *) RESET UCHAR
minimal(main) = (* 1 *) EOF
minimal(init) = (* 1 *) UCHAR
minimal(header_option) = (* 1 *) OPTION
minimal(header) = (* 1 *) OPTION
minimal(elem) = (* 1 *) UCHAR
follow(ulist) = TERTIARY SECONDARY RESET PRIMARY PREFIX EXPAND EQ EOF
follow(rules) = EOF
follow(rule) = TERTIARY SECONDARY RESET PRIMARY EQ EOF
follow(main) = #
follow(init) = TERTIARY SECONDARY RESET PRIMARY EQ EOF
follow(header_option) = UCHAR RESET OPTION EOF
follow(header) = RESET EOF
follow(elem) = TERTIARY SECONDARY RESET PRIMARY EXPAND EQ EOF
Built an LR(0) automaton with 37 states.
The grammar is not SLR(1) -- 1 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 37 states.
One shift/reduce conflict was silently solved.
File "camomile.1.0.1-colParser.mly", line 53, characters 2-7:
Warning: the precedence level assigned to EQ is never useful.
File "camomile.1.0.1-colParser.mly", line 53, characters 2-7:
Warning: the precedence level assigned to PRIMARY is never useful.
File "camomile.1.0.1-colParser.mly", line 52, characters 2-11:
Warning: the precedence level assigned to RESET is never useful.
File "camomile.1.0.1-colParser.mly", line 53, characters 2-7:
Warning: the precedence level assigned to SECONDARY is never useful.
File "camomile.1.0.1-colParser.mly", line 53, characters 2-7:
Warning: the precedence level assigned to TERTIARY is never useful.
17 out of 37 states have a default reduction.
13 out of 37 states are represented.
0 out of 21 symbols keep track of their start position.
0 out of 21 symbols keep track of their end position.
10 out of 25 productions exploit shiftreduce optimization.
0 out of 37 states can peek at an error.
113 functions before inlining, 19 functions after inlining.
