Grammar has 8 nonterminal symbols, among which 1 start symbols.
Grammar has 23 terminal symbols.
Grammar has 19 productions.
nullable(subnets) = true
nullable(subnet) = false
nullable(statements) = true
nullable(statement) = false
nullable(main) = false
nullable(ips) = false
nullable(hosts) = true
nullable(host) = false
first(subnets) = SUBNET
first(subnet) = SUBNET
first(statements) = RANGE OPTION MAXLEASETIME HARDWARE FIXEDADDRESS DEFAULTLEASETIME
first(statement) = RANGE OPTION MAXLEASETIME HARDWARE FIXEDADDRESS DEFAULTLEASETIME
first(main) = RANGE OPTION MAXLEASETIME HARDWARE FIXEDADDRESS DEFAULTLEASETIME
first(ips) = IP
first(hosts) = HOST
first(host) = HOST
minimal(subnets) = (* 0 *) 
minimal(subnet) = (* 6 *) SUBNET IP NETMASK IP LBRACKET RBRACKET
minimal(statements) = (* 0 *) 
minimal(statement) = (* 3 *) FIXEDADDRESS IP SCOLON
minimal(main) = (* 10 *) FIXEDADDRESS IP SCOLON SUBNET IP NETMASK IP LBRACKET RBRACKET EOF
minimal(ips) = (* 1 *) IP
minimal(hosts) = (* 0 *) 
minimal(host) = (* 4 *) HOST WORD LBRACKET RBRACKET
follow(subnets) = EOF
follow(subnet) = SUBNET EOF
follow(statements) = SUBNET RBRACKET HOST
follow(statement) = SUBNET RBRACKET RANGE OPTION MAXLEASETIME HOST HARDWARE FIXEDADDRESS DEFAULTLEASETIME
follow(main) = #
follow(ips) = SCOLON
follow(hosts) = RBRACKET
follow(host) = RBRACKET HOST
Built an LR(0) automaton with 56 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 56 states.
16 out of 56 states have a default reduction.
13 out of 56 states are represented.
0 out of 34 symbols keep track of their start position.
0 out of 34 symbols keep track of their end position.
12 out of 20 productions exploit shiftreduce optimization.
0 out of 56 states can peek at an error.
146 functions before inlining, 21 functions after inlining.
