Grammar has 6 nonterminal symbols, among which 1 start symbols.
Grammar has 14 terminal symbols.
Grammar has 17 productions.
nullable(signature) = false
nullable(op_list) = false
nullable(ident) = false
nullable(fix) = true
nullable(decl) = false
nullable(arity) = false
first(signature) = INT IDENT EOF
first(op_list) = INT IDENT
first(ident) = INT IDENT
first(fix) = KW_PREFIX KW_POSTFIX KW_INFIX
first(decl) = INT IDENT
first(arity) = KW_UNARY KW_CONSTANT KW_C KW_BINARY KW_AC INT
minimal(signature) = (* 1 *) EOF
minimal(op_list) = (* 1 *) IDENT
minimal(ident) = (* 1 *) IDENT
minimal(fix) = (* 0 *) 
minimal(decl) = (* 3 *) IDENT COLON KW_C
minimal(arity) = (* 1 *) KW_C
follow(signature) = #
follow(op_list) = COLON
follow(ident) = COMMA COLON
follow(fix) = KW_UNARY KW_CONSTANT KW_C KW_BINARY KW_AC INT
follow(decl) = SEMICOLON
follow(arity) = SEMICOLON
Built an LR(0) automaton with 24 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 24 states.
16 out of 24 states have a default reduction.
3 out of 24 states are represented.
0 out of 23 symbols keep track of their start position.
0 out of 23 symbols keep track of their end position.
15 out of 18 productions exploit shiftreduce optimization.
0 out of 24 states can peek at an error.
78 functions before inlining, 11 functions after inlining.
