Grammar has 12 nonterminal symbols, among which 2 start symbols.
Grammar has 16 terminal symbols.
Grammar has 28 productions.
nullable(sorted_signature) = false
nullable(sorted_decl) = false
nullable(sort_list) = true
nullable(sort) = false
nullable(signature) = false
nullable(profile_list) = false
nullable(profile) = false
nullable(op_list) = false
nullable(ident) = false
nullable(fix) = true
nullable(decl) = false
nullable(arity) = false
first(sorted_signature) = INT IDENT EOF
first(sorted_decl) = INT IDENT
first(sort_list) = IDENT
first(sort) = IDENT
first(signature) = INT IDENT EOF
first(profile_list) = IDENT ARROW
first(profile) = IDENT ARROW
first(op_list) = INT IDENT
first(ident) = INT IDENT
first(fix) = KW_PREFIX KW_POSTFIX KW_INFIX
first(decl) = INT IDENT
first(arity) = KW_UNARY KW_CONSTANT KW_C KW_BINARY KW_AC INT
minimal(sorted_signature) = (* 1 *) EOF
minimal(sorted_decl) = (* 6 *) IDENT COLON KW_C AS ARROW IDENT
minimal(sort_list) = (* 0 *) 
minimal(sort) = (* 1 *) IDENT
minimal(signature) = (* 1 *) EOF
minimal(profile_list) = (* 2 *) ARROW IDENT
minimal(profile) = (* 2 *) ARROW IDENT
minimal(op_list) = (* 1 *) IDENT
minimal(ident) = (* 1 *) IDENT
minimal(fix) = (* 0 *) 
minimal(decl) = (* 3 *) IDENT COLON KW_C
minimal(arity) = (* 1 *) KW_C
follow(sorted_signature) = #
follow(sorted_decl) = SEMICOLON #
follow(sort_list) = ARROW
follow(sort) = SEMICOLON IDENT COMMA ARROW #
follow(signature) = #
follow(profile_list) = SEMICOLON #
follow(profile) = SEMICOLON COMMA #
follow(op_list) = COLON
follow(ident) = COMMA COLON
follow(fix) = KW_UNARY KW_CONSTANT KW_C KW_BINARY KW_AC INT
follow(decl) = SEMICOLON #
follow(arity) = SEMICOLON AS #
Built an LR(0) automaton with 45 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 45 states.
Warning: 14 states have an end-of-stream conflict.
File "cime-terms-signature.mly", line 38, characters 2-6:
Warning: production signature -> decl is never reduced.
File "cime-terms-signature.mly", line 44, characters 2-13:
Warning: production sorted_signature -> sorted_decl is never reduced.
Warning: in total, 2 productions are never reduced.
24 out of 45 states have a default reduction.
13 out of 45 states are represented.
0 out of 32 symbols keep track of their start position.
0 out of 32 symbols keep track of their end position.
22 out of 30 productions exploit shiftreduce optimization.
0 out of 45 states can peek at an error.
137 functions before inlining, 30 functions after inlining.
