File "cime-poly-interp.mly", line 29, characters 7-15:
Warning: the token LEFT_BRA is unused.
File "cime-poly-interp.mly", line 29, characters 16-25:
Warning: the token RIGHT_BRA is unused.
Grammar has 7 nonterminal symbols, among which 2 start symbols.
Grammar has 15 terminal symbols.
Grammar has 18 productions.
nullable(weight_entry) = false
nullable(weight) = true
nullable(vars) = false
nullable(symbol_interp) = false
nullable(poly_interp_entry) = false
nullable(poly) = false
nullable(interp) = true
first(weight_entry) = INTERP EOF
first(weight) = INTERP
first(vars) = VAR
first(symbol_interp) = INTERP
first(poly_interp_entry) = INTERP EOF
first(poly) = VAR MINUS LEFT_PAR INT
first(interp) = INTERP
minimal(weight_entry) = (* 1 *) EOF
minimal(weight) = (* 0 *) 
minimal(vars) = (* 2 *) VAR RIGHT_PAR
minimal(symbol_interp) = (* 1 *) INTERP
minimal(poly_interp_entry) = (* 1 *) EOF
minimal(poly) = (* 1 *) VAR
minimal(interp) = (* 0 *) 
follow(weight_entry) = #
follow(weight) = EOF
follow(vars) = EQUAL
follow(symbol_interp) = EQUAL
follow(poly_interp_entry) = #
follow(poly) = SEMICOLON RIGHT_PAR PLUS MULT MINUS EXP
follow(interp) = EOF
Built an LR(0) automaton with 40 states.
The grammar is not SLR(1) -- 4 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 40 states.
16 shift/reduce conflicts were silently solved.
13 out of 40 states have a default reduction.
12 out of 40 states are represented.
0 out of 26 symbols keep track of their start position.
0 out of 26 symbols keep track of their end position.
11 out of 20 productions exploit shiftreduce optimization.
0 out of 40 states can peek at an error.
114 functions before inlining, 24 functions after inlining.
