Grammar has 10 nonterminal symbols, among which 4 start symbols.
Grammar has 8 terminal symbols.
Grammar has 23 productions.
nullable(params) = true
nullable(param) = false
nullable(media_ranges) = false
nullable(media_range) = false
nullable(languages) = false
nullable(language) = false
nullable(encodings) = false
nullable(encoding) = false
nullable(charsets) = false
nullable(charset) = false
first(params) = SEMI
first(param) = SEMI
first(media_ranges) = TOK STAR EOI
first(media_range) = TOK STAR
first(languages) = TOK STAR
first(language) = TOK STAR
first(encodings) = TOK STAR EOI
first(encoding) = TOK STAR
first(charsets) = TOK STAR
first(charset) = TOK STAR
minimal(params) = (* 0 *) 
minimal(param) = (* 4 *) SEMI TOK EQUAL QS
minimal(media_ranges) = (* 1 *) EOI
minimal(media_range) = (* 3 *) STAR SLASH STAR
minimal(languages) = (* 2 *) TOK EOI
minimal(language) = (* 1 *) TOK
minimal(encodings) = (* 1 *) EOI
minimal(encoding) = (* 1 *) TOK
minimal(charsets) = (* 2 *) TOK EOI
minimal(charset) = (* 1 *) TOK
follow(params) = EOI COMMA
follow(param) = SEMI EOI COMMA
follow(media_ranges) = #
follow(media_range) = EOI COMMA
follow(languages) = #
follow(language) = EOI COMMA
follow(encodings) = #
follow(encoding) = EOI COMMA
follow(charsets) = #
follow(charset) = EOI COMMA
Built an LR(0) automaton with 55 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 55 states.
26 out of 55 states have a default reduction.
18 out of 55 states are represented.
0 out of 24 symbols keep track of their start position.
0 out of 24 symbols keep track of their end position.
26 out of 27 productions exploit shiftreduce optimization.
0 out of 55 states can peek at an error.
156 functions before inlining, 30 functions after inlining.
