Grammar has 7 nonterminal symbols, among which 1 start symbols.
Grammar has 6 terminal symbols.
Grammar has 10 productions.
nullable(primary_not_name) = false
nullable(primary) = false
nullable(left_hand_side) = false
nullable(goal) = false
nullable(expression) = false
nullable(assignment) = false
nullable(array_access) = false
first(primary_not_name) = NEW INTEGER_LITERAL
first(primary) = NEW INTEGER_LITERAL
first(left_hand_side) = NEW INTEGER_LITERAL
first(goal) = NEW INTEGER_LITERAL
first(expression) = NEW INTEGER_LITERAL
first(assignment) = NEW INTEGER_LITERAL
first(array_access) = NEW INTEGER_LITERAL
minimal(primary_not_name) = (* 4 *) NEW L_BRACKET INTEGER_LITERAL R_BRACKET
minimal(primary) = (* 1 *) INTEGER_LITERAL
minimal(left_hand_side) = (* 4 *) NEW L_BRACKET INTEGER_LITERAL R_BRACKET
minimal(goal) = (* 7 *) NEW L_BRACKET INTEGER_LITERAL R_BRACKET ASSIGN INTEGER_LITERAL EOF
minimal(expression) = (* 1 *) INTEGER_LITERAL
minimal(assignment) = (* 6 *) NEW L_BRACKET INTEGER_LITERAL R_BRACKET ASSIGN INTEGER_LITERAL
minimal(array_access) = (* 7 *) INTEGER_LITERAL L_BRACKET NEW L_BRACKET INTEGER_LITERAL R_BRACKET R_BRACKET
follow(primary_not_name) = R_BRACKET ASSIGN
follow(primary) = R_BRACKET L_BRACKET EOF
follow(left_hand_side) = ASSIGN
follow(goal) = #
follow(expression) = R_BRACKET L_BRACKET EOF
follow(assignment) = R_BRACKET L_BRACKET EOF
follow(array_access) = R_BRACKET L_BRACKET EOF ASSIGN
Built an LR(0) automaton with 20 states.
The grammar is not SLR(1) -- 3 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 21 states.
Warning: one state has shift/reduce conflicts.
Warning: one shift/reduce conflict was arbitrarily resolved.
8 out of 21 states have a default reduction.
4 out of 21 states are represented.
0 out of 16 symbols keep track of their start position.
0 out of 16 symbols keep track of their end position.
6 out of 11 productions exploit shiftreduce optimization.
0 out of 21 states can peek at an error.
66 functions before inlining, 13 functions after inlining.
