Grammar has 8 nonterminal symbols, among which 2 start symbols.
Grammar has 4 terminal symbols.
Grammar has 18 productions.
nullable(stanzas) = true
nullable(stanza_822) = false
nullable(stanza) = false
nullable(linecont) = false
nullable(fields) = false
nullable(field) = false
nullable(eols) = false
nullable(doc_822) = true
first(stanzas) = FIELD
first(stanza_822) = FIELD EOL EOF
first(stanza) = FIELD
first(linecont) = CONT
first(fields) = FIELD
first(field) = FIELD
first(eols) = EOL
first(doc_822) = FIELD EOL
minimal(stanzas) = (* 0 *) 
minimal(stanza_822) = (* 1 *) EOF
minimal(stanza) = (* 2 *) FIELD EOL
minimal(linecont) = (* 2 *) CONT EOL
minimal(fields) = (* 2 *) FIELD EOL
minimal(field) = (* 2 *) FIELD EOL
minimal(eols) = (* 1 *) EOL
minimal(doc_822) = (* 0 *) 
follow(stanzas) = #
follow(stanza_822) = #
follow(stanza) = EOL EOF #
follow(linecont) = FIELD EOL EOF #
follow(fields) = EOL EOF #
follow(field) = FIELD EOL EOF #
follow(eols) = FIELD EOF #
follow(doc_822) = #
Built an LR(0) automaton with 27 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 30 states.
Warning: 10 states have an end-of-stream conflict.
File "debian-formats.0.1.1-DF822_parser.mly", line 74, characters 3-3:
Warning: production stanzas -> is never reduced.
Warning: in total, 1 production is never reduced.
17 out of 30 states have a default reduction.
11 out of 30 states are represented.
0 out of 16 symbols keep track of their start position.
0 out of 16 symbols keep track of their end position.
12 out of 20 productions exploit shiftreduce optimization.
0 out of 30 states can peek at an error.
94 functions before inlining, 18 functions after inlining.
