Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 6 terminal symbols.
Grammar has 7 productions.
nullable(type_expr) = false
nullable(expr_eoi) = false
nullable(expr) = false
first(type_expr) = Typevar Ident
first(expr_eoi) = Ident
first(expr) = Ident
minimal(type_expr) = (* 1 *) Ident
minimal(expr_eoi) = (* 2 *) Ident Eoi
minimal(expr) = (* 1 *) Ident
follow(type_expr) = Rparen Lparen Eoi Colon
follow(expr_eoi) = #
follow(expr) = Rparen Lparen Eoi Colon
Built an LR(0) automaton with 15 states.
The grammar is not SLR(1) -- 1 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 15 states.
One shift/reduce conflict was silently solved.
7 out of 15 states have a default reduction.
4 out of 15 states are represented.
0 out of 12 symbols keep track of their start position.
0 out of 12 symbols keep track of their end position.
6 out of 8 productions exploit shiftreduce optimization.
0 out of 15 states can peek at an error.
47 functions before inlining, 11 functions after inlining.
