%{
(***********************************************************************)
(*                                                                     *)
(*                           xlib for Ocaml                            *)
(*                                                                     *)
(*       Fabrice Le Fessant, projet Para/SOR, INRIA Rocquencourt       *)
(*                                                                     *)
(*  Copyright 1998 Institut National de Recherche en Informatique et   *)
(*  Automatique.  Distributed only by permission.                      *)
(*                                                                     *)
(***********************************************************************)
%}
%start parse_filename
%start parse_passwd
%token EOF
%token EOL
%token <string> IDENT
%token SEP
%token TILDE
%type <token list> parse_filename
%type <string list list> parse_passwd
%%

parse_passwd:
  _1 = passwd_line _2 = EOL _3 = parse_passwd
    {                                ( _1 :: _3 )}
| _1 = passwd_line _2 = EOF
    {                                ( [_1] )}

passwd_line:
  _1 = IDENT _2 = SEP _3 = passwd_line
    {                         ( _1 :: _3 )}
| _1 = SEP _2 = passwd_line
    {                         ( "" :: _2 )}
| _1 = IDENT
    {                         ( [_1] )}
| 
    {                         ( [""] )}

parse_filename:
  _1 = TILDE _2 = parse_filename
    {                         ( TILDE :: _2 )}
| _1 = SEP _2 = parse_filename
    {                         ( SEP :: _2 )}
| _1 = IDENT _2 = parse_filename
    {                         ( (IDENT _1) :: _2 )}
| _1 = EOF
    {                         ( [] )}

%%




