Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 1 terminal symbols.
Grammar has 3 productions.
nullable(wrap(seq(wrap(A)))) = false
nullable(start) = false
nullable(seq(A)) = false
first(wrap(seq(wrap(A)))) = A
first(start) = A
first(seq(A)) = A
minimal(wrap(seq(wrap(A)))) = (* 1 *) A
minimal(start) = (* 1 *) A
minimal(seq(A)) = (* 1 *) A
follow(wrap(seq(wrap(A)))) = #
follow(start) = #
follow(seq(A)) = #
Built an LR(0) automaton with 5 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 5 states.
4 out of 5 states have a default reduction.
0 out of 5 states are represented.
0 out of 7 symbols keep track of their start position.
0 out of 7 symbols keep track of their end position.
4 out of 4 productions exploit shiftreduce optimization.
0 out of 5 states can peek at an error.
23 functions before inlining, 1 functions after inlining.
