File "featherweight.mly", line 47, characters 28-38:
Warning: the token APOSTROPHE is unused.
File "featherweight.mly", line 49, characters 28-33:
Warning: the token ARROW is unused.
File "featherweight.mly", line 50, characters 28-32:
Warning: the token BANG is unused.
File "featherweight.mly", line 51, characters 28-33:
Warning: the token BARGT is unused.
File "featherweight.mly", line 52, characters 28-37:
Warning: the token BARRCURLY is unused.
File "featherweight.mly", line 53, characters 28-38:
Warning: the token BARRSQUARE is unused.
File "featherweight.mly", line 55, characters 28-38:
Warning: the token COLONCOLON is unused.
File "featherweight.mly", line 56, characters 28-35:
Warning: the token COLONEQ is unused.
File "featherweight.mly", line 57, characters 28-37:
Warning: the token COLONHASH is unused.
File "featherweight.mly", line 59, characters 28-34:
Warning: the token DARROW is unused.
File "featherweight.mly", line 60, characters 28-35:
Warning: the token DDARROW is unused.
File "featherweight.mly", line 48, characters 28-34:
Warning: the token DQUOTE is unused.
File "featherweight.mly", line 62, characters 28-31:
Warning: the token EOF is unused.
File "featherweight.mly", line 64, characters 28-32:
Warning: the token EQEQ is unused.
File "featherweight.mly", line 65, characters 28-34:
Warning: the token EXISTS is unused.
File "featherweight.mly", line 42, characters 38-44:
Warning: the token FLOATV is unused.
File "featherweight.mly", line 66, characters 28-30:
Warning: the token GT is unused.
File "featherweight.mly", line 67, characters 28-32:
Warning: the token HASH is unused.
File "featherweight.mly", line 41, characters 36-40:
Warning: the token INTV is unused.
File "featherweight.mly", line 69, characters 28-37:
Warning: the token LCURLYBAR is unused.
File "featherweight.mly", line 70, characters 28-37:
Warning: the token LEFTARROW is unused.
File "featherweight.mly", line 72, characters 28-35:
Warning: the token LSQUARE is unused.
File "featherweight.mly", line 73, characters 28-38:
Warning: the token LSQUAREBAR is unused.
File "featherweight.mly", line 74, characters 28-30:
Warning: the token LT is unused.
File "featherweight.mly", line 77, characters 28-35:
Warning: the token RSQUARE is unused.
File "featherweight.mly", line 79, characters 28-33:
Warning: the token SLASH is unused.
File "featherweight.mly", line 80, characters 28-32:
Warning: the token STAR is unused.
File "featherweight.mly", line 43, characters 39-46:
Warning: the token STRINGV is unused.
File "featherweight.mly", line 81, characters 28-36:
Warning: the token TRIANGLE is unused.
File "featherweight.mly", line 82, characters 28-34:
Warning: the token USCORE is unused.
File "featherweight.mly", line 83, characters 28-32:
Warning: the token VBAR is unused.
Grammar has 22 nonterminal symbols, among which 1 start symbols.
Grammar has 48 terminal symbols.
Grammar has 44 productions.
nullable(toplevel) = false
nullable(termDefs) = true
nullable(termDef) = false
nullable(paramDefs) = true
nullable(paramDef) = false
nullable(methodDefs) = false
nullable(methodDef) = false
nullable(fieldDefs) = false
nullable(fieldDef) = false
nullable(fieldAssignmentDefs) = true
nullable(fieldAssignmentDef) = false
nullable(constructorDef) = false
nullable(classDecs) = false
nullable(classDec) = false
nullable(argDefs) = true
nullable(argDef) = false
nullable(TmVarDef) = false
nullable(TmThis) = false
nullable(TmObjectCreationDef) = false
nullable(TmMethodInvocationDef) = false
nullable(TmFieldAccessDef) = false
nullable(TmCastDef) = false
first(toplevel) = COMMAND CLASS
first(termDefs) = THIS NEW LPAREN ID
first(termDef) = THIS NEW LPAREN ID
first(paramDefs) = ID
first(paramDef) = ID
first(methodDefs) = SEMI ID
first(methodDef) = ID
first(fieldDefs) = SEMI ID
first(fieldDef) = ID
first(fieldAssignmentDefs) = THIS
first(fieldAssignmentDef) = THIS
first(constructorDef) = ID
first(classDecs) = COMMAND CLASS
first(classDec) = CLASS
first(argDefs) = ID
first(argDef) = ID
first(TmVarDef) = ID
first(TmThis) = THIS
first(TmObjectCreationDef) = NEW
first(TmMethodInvocationDef) = THIS NEW LPAREN ID
first(TmFieldAccessDef) = THIS NEW LPAREN ID
first(TmCastDef) = LPAREN
minimal(toplevel) = (* 3 *) COMMAND COLON ID
minimal(termDefs) = (* 0 *) 
minimal(termDef) = (* 1 *) ID
minimal(paramDefs) = (* 0 *) 
minimal(paramDef) = (* 2 *) ID ID
minimal(methodDefs) = (* 1 *) SEMI
minimal(methodDef) = (* 9 *) ID ID LPAREN RPAREN LCURLY RETURN ID SEMI RCURLY
minimal(fieldDefs) = (* 1 *) SEMI
minimal(fieldDef) = (* 2 *) ID ID
minimal(fieldAssignmentDefs) = (* 0 *) 
minimal(fieldAssignmentDef) = (* 6 *) THIS DOT ID EQ ID SEMI
minimal(constructorDef) = (* 9 *) ID LPAREN RPAREN LCURLY SUPER LPAREN RPAREN SEMI RCURLY
minimal(classDecs) = (* 1 *) COMMAND
minimal(classDec) = (* 15 *) CLASS ID EXTENDS ID LCURLY ID LPAREN RPAREN LCURLY SUPER LPAREN RPAREN SEMI RCURLY RCURLY
minimal(argDefs) = (* 0 *) 
minimal(argDef) = (* 1 *) ID
minimal(TmVarDef) = (* 1 *) ID
minimal(TmThis) = (* 1 *) THIS
minimal(TmObjectCreationDef) = (* 4 *) NEW ID LPAREN RPAREN
minimal(TmMethodInvocationDef) = (* 5 *) ID DOT ID LPAREN RPAREN
minimal(TmFieldAccessDef) = (* 3 *) ID DOT ID
minimal(TmCastDef) = (* 4 *) LPAREN ID RPAREN ID
follow(toplevel) = #
follow(termDefs) = RPAREN
follow(termDef) = SEMI RPAREN DOT COMMA #
follow(paramDefs) = RPAREN
follow(paramDef) = RPAREN COMMA
follow(methodDefs) = RCURLY
follow(methodDef) = SEMI ID
follow(fieldDefs) = ID
follow(fieldDef) = SEMI
follow(fieldAssignmentDefs) = RCURLY
follow(fieldAssignmentDef) = THIS RCURLY
follow(constructorDef) = SEMI RCURLY ID
follow(classDecs) = COLON
follow(classDec) = COMMAND CLASS
follow(argDefs) = RPAREN
follow(argDef) = RPAREN COMMA
follow(TmVarDef) = SEMI RPAREN DOT COMMA #
follow(TmThis) = SEMI RPAREN DOT COMMA #
follow(TmObjectCreationDef) = SEMI RPAREN DOT COMMA #
follow(TmMethodInvocationDef) = SEMI RPAREN DOT COMMA #
follow(TmFieldAccessDef) = SEMI RPAREN DOT COMMA #
follow(TmCastDef) = SEMI RPAREN DOT COMMA #
Built an LR(0) automaton with 105 states.
The grammar is not SLR(1) -- 6 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 105 states.
Warning: one state has shift/reduce conflicts.
Warning: one shift/reduce conflict was arbitrarily resolved.
Warning: 17 states have an end-of-stream conflict.
File "featherweight.mly", line 101, characters 1-24:
Warning: production toplevel -> classDecs COLON termDef is never reduced.
Warning: in total, 1 production is never reduced.
35 out of 105 states have a default reduction.
22 out of 105 states are represented.
0 out of 73 symbols keep track of their start position.
0 out of 73 symbols keep track of their end position.
24 out of 45 productions exploit shiftreduce optimization.
0 out of 105 states can peek at an error.
282 functions before inlining, 37 functions after inlining.
