File "filiot.mly", line 70, characters 7-10:
Warning: the token DOT is unused.
File "filiot.mly", line 90, characters 13-16:
Warning: the token INT is unused.
File "filiot.mly", line 69, characters 17-22:
Warning: the token TILDA is unused.
Grammar has 7 nonterminal symbols, among which 1 start symbols.
Grammar has 43 terminal symbols.
Grammar has 50 productions.
nullable(main) = true
nullable(VariablesDec) = false
nullable(QuantVariablesDec) = false
nullable(Formula) = false
nullable(Body) = false
nullable(BinPredPref) = false
nullable(BinPredInf) = false
first(main) = VAR TRUE STR SING ROOT NS LPAR LEAF LAB FC FALSE EX2 EX1 CHILD ALL2 ALL1
first(VariablesDec) = STR
first(QuantVariablesDec) = STR
first(Formula) = TRUE STR SING ROOT NS LPAR LEAF LAB FC FALSE EX2 EX1 CHILD ALL2 ALL1
first(Body) = VAR TRUE STR SING ROOT NS LPAR LEAF LAB FC FALSE EX2 EX1 CHILD ALL2 ALL1
first(BinPredPref) = STR NS LAB FC CHILD
first(BinPredInf) = SUB STR SIBSTRICT SIB PREFSTRICT PREF NOTIN ISIBSTRICT ISIB IPREFSTRICT IPREF IN EQ2 EQ1 DIFF2 DIFF1
minimal(main) = (* 0 *) 
minimal(VariablesDec) = (* 2 *) STR POINTVIRGULE
minimal(QuantVariablesDec) = (* 2 *) STR SEMICOLON
minimal(Formula) = (* 1 *) TRUE
minimal(Body) = (* 2 *) TRUE POINTVIRGULE
minimal(BinPredPref) = (* 1 *) CHILD
minimal(BinPredInf) = (* 1 *) IN
follow(main) = #
follow(VariablesDec) = TRUE STR SING ROOT NS LPAR LEAF LAB FC FALSE EX2 EX1 EOF CHILD ALL2 ALL1
follow(QuantVariablesDec) = error TRUE STR SING ROOT NS LPAR LEAF LAB FC FALSE EX2 EX1 CHILD ALL2 ALL1
follow(Formula) = RPAR POINTVIRGULE OR IMPLIES EQUIV AND
follow(Body) = EOF
follow(BinPredPref) = LPAR
follow(BinPredInf) = STR
Built an LR(0) automaton with 88 states.
The grammar is not SLR(1) -- 8 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 88 states.
32 shift/reduce conflicts were silently solved.
File "filiot.mly", line 94, characters 0-9:
Warning: the precedence level assigned to LPAR is never useful.
File "filiot.mly", line 94, characters 0-9:
Warning: the precedence level assigned to RPAR is never useful.
File "filiot.mly", line 95, characters 0-5:
Warning: the precedence level assigned to TILDA is never useful.
Warning: one state has an end-of-stream conflict.
File "filiot.mly", line 107, characters 1-1:
Warning: production main -> is never reduced.
Warning: in total, 1 production is never reduced.
46 out of 88 states have a default reduction.
18 out of 88 states are represented.
0 out of 53 symbols keep track of their start position.
0 out of 53 symbols keep track of their end position.
38 out of 51 productions exploit shiftreduce optimization.
4 out of 88 states can peek at an error.
239 functions before inlining, 31 functions after inlining.
