%{
open Doc_parsetree

%}
%start file
%token <int> CLOSE
%token <string> DIRECTIVE
%token EOF
%token <string> LBRACE
%token <int> OPEN
%token RBRACE
%token <int*int> TERMINATE
%token <string> TEXT
%token <string> VERB
%type <Doc_parsetree.comment list> file
%%

file:
  _1 = EOF
    {    ( [] )}
| _1 = OPEN _2 = ftext _3 = CLOSE _4 = file
    {    (
      { cmt_start = _1;
	cmt_end = _3;
	cmt_content = Ftext (List.rev _2)
      } :: _4 )}
| _1 = TERMINATE _2 = file
    {    (
      { cmt_start = fst _1;
	cmt_end = snd _1 ;
	cmt_content = Terminate
      } :: _2 )}

ftext:
  
    {    ( [] )}
| _1 = ftext _2 = DIRECTIVE
    {    ( (Directive _2) :: _1 )}
| _1 = ftext _2 = TEXT
    {    ( (String _2) :: _1 )}
| _1 = ftext _2 = LBRACE _3 = ftext _4 = RBRACE
    {    ( (Block (_2, List.rev _3)) :: _1 )}
| _1 = ftext _2 = VERB
    {    ( (Block ("src", [String _2])) :: _1 )}

%%


