Note: the nonterminal symbol list (from fp.mly) is renamed fp_list.
Grammar has 7 nonterminal symbols, among which 3 start symbols.
Grammar has 33 terminal symbols.
Grammar has 35 productions.
nullable(fp_list) = false
nullable(fctlist) = false
nullable(fct) = false
nullable(fatom) = false
nullable(exp) = false
nullable(comp) = false
nullable(cmd) = false
first(fp_list) = Lwhile Lvar Lsqu Ls Lr Lprim Lpar Lint Lins Lident Lcst Lbu Lapplytoall Lang LT LF
first(fctlist) = Lwhile Lsqu Ls Lr Lprim Lpar Lins Lident Lcst Lbu Lapplytoall
first(fct) = Lwhile Lsqu Ls Lr Lprim Lpar Lins Lident Lcst Lbu Lapplytoall
first(fatom) = Lwhile Lsqu Ls Lr Lprim Lpar Lins Lident Lcst Lbu Lapplytoall
first(exp) = Lwhile Lvar Lsqu Ls Lr Lprim Lpar Lint Lins Lident Lcst Lbu Lapplytoall Lang LT LF
first(comp) = Lwhile Lsqu Ls Lr Lprim Lpar Lins Lident Lcst Lbu Lapplytoall
first(cmd) = Lwhile Lvar Lsqu Ls Lr Lprim Lpar Lint Lins Lident Leol Lcst Lbu Lapplytoall Lang LUndef LT LShow LSave LQuit LLoad LF LDef
minimal(fp_list) = (* 1 *) LT
minimal(fctlist) = (* 1 *) Lprim
minimal(fct) = (* 1 *) Lprim
minimal(fatom) = (* 1 *) Lprim
minimal(exp) = (* 1 *) LT
minimal(comp) = (* 1 *) Lprim
minimal(cmd) = (* 1 *) Leol
follow(fp_list) = Rang
follow(fctlist) = Rsqu
follow(fct) = Rsqu Rpar Leval Leol Lcom #
follow(fatom) = Rsqu Rpar Lwhile Lvar Lsqu Lscl Ls Lr Lprim Lpar Lo Lint Lins Lident Leval Leol Lcst Lcond Lcom Lbu Lapplytoall Lang LT LF #
follow(exp) = Rsqu Rpar Rang Lwhile Lvar Lsqu Lscl Ls Lr Lprim Lpar Lo Lint Lins Lident Leval Leol Lcst Lcond Lcom Lbu Lapplytoall Lang LT LF #
follow(comp) = Rsqu Rpar Lscl Leval Leol Lcond Lcom #
follow(cmd) = #
Built an LR(0) automaton with 79 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 84 states.
File "fp.mly", line 29, characters 2-8:
Warning: the precedence level assigned to Lcond is never useful.
File "fp.mly", line 31, characters 2-7:
Warning: the precedence level assigned to Lcst is never useful.
File "fp.mly", line 27, characters 2-8:
Warning: the precedence level assigned to Leval is never useful.
File "fp.mly", line 30, characters 2-8:
Warning: the precedence level assigned to Lo is never useful.
File "fp.mly", line 28, characters 2-7:
Warning: the precedence level assigned to Lprim is never useful.
Warning: 22 states have an end-of-stream conflict.
35 out of 84 states have a default reduction.
23 out of 84 states are represented.
0 out of 45 symbols keep track of their start position.
0 out of 45 symbols keep track of their end position.
22 out of 38 productions exploit shiftreduce optimization.
0 out of 84 states can peek at an error.
221 functions before inlining, 34 functions after inlining.
