Grammar has 10 nonterminal symbols, among which 1 start symbols.
Grammar has 11 terminal symbols.
Grammar has 23 productions.
nullable(string_list) = false
nullable(pluralform_list) = false
nullable(pluralform) = false
nullable(msgid_pluralform) = false
nullable(msgfmt) = false
nullable(message_list) = false
nullable(message) = false
nullable(domain) = false
nullable(comment_list) = false
nullable(comment) = false
first(string_list) = STRING
first(pluralform_list) = MSGSTR
first(pluralform) = MSGSTR
first(msgid_pluralform) = MSGID_PLURAL
first(msgfmt) = MSGID EOF DOMAIN COMMENT_SPECIAL COMMENT_FILEPOS
first(message_list) = MSGID COMMENT_SPECIAL COMMENT_FILEPOS
first(message) = MSGID COMMENT_SPECIAL COMMENT_FILEPOS
first(domain) = DOMAIN
first(comment_list) = COMMENT_SPECIAL COMMENT_FILEPOS
first(comment) = COMMENT_SPECIAL COMMENT_FILEPOS
minimal(string_list) = (* 1 *) STRING
minimal(pluralform_list) = (* 5 *) MSGSTR LBRACKET NUMBER RBRACKET STRING
minimal(pluralform) = (* 5 *) MSGSTR LBRACKET NUMBER RBRACKET STRING
minimal(msgid_pluralform) = (* 2 *) MSGID_PLURAL STRING
minimal(msgfmt) = (* 1 *) EOF
minimal(message_list) = (* 4 *) MSGID STRING MSGSTR STRING
minimal(message) = (* 4 *) MSGID STRING MSGSTR STRING
minimal(domain) = (* 2 *) DOMAIN STRING
minimal(comment_list) = (* 1 *) COMMENT_FILEPOS
minimal(comment) = (* 1 *) COMMENT_FILEPOS
follow(string_list) = STRING MSGSTR MSGID_PLURAL MSGID DOMAIN COMMENT_SPECIAL COMMENT_FILEPOS #
follow(pluralform_list) = MSGSTR MSGID DOMAIN COMMENT_SPECIAL COMMENT_FILEPOS #
follow(pluralform) = MSGSTR MSGID DOMAIN COMMENT_SPECIAL COMMENT_FILEPOS #
follow(msgid_pluralform) = MSGSTR
follow(msgfmt) = MSGID DOMAIN COMMENT_SPECIAL COMMENT_FILEPOS #
follow(message_list) = MSGID DOMAIN COMMENT_SPECIAL COMMENT_FILEPOS #
follow(message) = MSGID DOMAIN COMMENT_SPECIAL COMMENT_FILEPOS #
follow(domain) = MSGID DOMAIN COMMENT_SPECIAL COMMENT_FILEPOS #
follow(comment_list) = MSGID COMMENT_SPECIAL COMMENT_FILEPOS
follow(comment) = MSGID COMMENT_SPECIAL COMMENT_FILEPOS
Built an LR(0) automaton with 40 states.
The grammar is not SLR(1) -- 4 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 40 states.
Warning: 4 states have shift/reduce conflicts.
Warning: 12 shift/reduce conflicts were arbitrarily resolved.
Warning: 19 states have an end-of-stream conflict.
File "gettext.0.3.8-gettextPo_parser.mly", line 114, characters 0-6:
Warning: symbol msgfmt is never accepted.
Warning: in total, 1 production is never reduced.
13 out of 40 states have a default reduction.
23 out of 40 states are represented.
0 out of 24 symbols keep track of their start position.
0 out of 24 symbols keep track of their end position.
14 out of 24 productions exploit shiftreduce optimization.
0 out of 40 states can peek at an error.
119 functions before inlining, 20 functions after inlining.
