Grammar has 23 nonterminal symbols, among which 1 start symbols.
Grammar has 26 terminal symbols.
Grammar has 67 productions.
nullable(version_line) = false
nullable(unpacksto_line) = false
nullable(spec) = false
nullable(sources_line) = false
nullable(revision_line) = false
nullable(package_line) = false
nullable(options_line) = false
nullable(options) = true
nullable(opt_target_line) = false
nullable(maintainer_line) = false
nullable(lines) = true
nullable(line) = false
nullable(homepage_line) = false
nullable(docfiles_line) = false
nullable(docfiles) = true
nullable(description_line) = false
nullable(deps) = true
nullable(depends_line) = false
nullable(dep) = false
nullable(confopts_line) = false
nullable(confopts) = true
nullable(bytecode_target_line) = false
nullable(build_depends_line) = false
first(version_line) = VERSION
first(unpacksto_line) = UNPACKSTO
first(spec) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
first(sources_line) = SOURCES
first(revision_line) = REVISION
first(package_line) = PACKAGE
first(options_line) = OPTIONS
first(options) = error OPTION
first(opt_target_line) = OPT_TARGET
first(maintainer_line) = MAINTAINER
first(lines) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
first(line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
first(homepage_line) = HOMEPAGE
first(docfiles_line) = DOCFILES
first(docfiles) = error STRING
first(description_line) = DESCRIPTION
first(deps) = error PKGNAME
first(depends_line) = DEPENDS
first(dep) = error PKGNAME
first(confopts_line) = CONFOPTS
first(confopts) = 
first(bytecode_target_line) = BC_TARGET
first(build_depends_line) = BUILD_DEPENDS
minimal(version_line) = (* 2 *) VERSION EOL
minimal(unpacksto_line) = (* 2 *) UNPACKSTO EOL
minimal(spec) = (* 1 *) EOF
minimal(sources_line) = (* 2 *) SOURCES EOL
minimal(revision_line) = (* 2 *) REVISION EOL
minimal(package_line) = (* 2 *) PACKAGE EOL
minimal(options_line) = (* 2 *) OPTIONS EOL
minimal(options) = (* 0 *) 
minimal(opt_target_line) = (* 2 *) OPT_TARGET EOL
minimal(maintainer_line) = (* 3 *) MAINTAINER STRING EOL
minimal(lines) = (* 0 *) 
minimal(line) = (* 2 *) PACKAGE EOL
minimal(homepage_line) = (* 2 *) HOMEPAGE EOL
minimal(docfiles_line) = (* 2 *) DOCFILES EOL
minimal(docfiles) = (* 0 *) 
minimal(description_line) = (* 2 *) DESCRIPTION STRINGPAIR
minimal(deps) = (* 0 *) 
minimal(depends_line) = (* 2 *) DEPENDS EOL
minimal(dep) = (* 1 *) PKGNAME
minimal(confopts_line) = (* 2 *) CONFOPTS EOL
minimal(confopts) = (* 0 *) 
minimal(bytecode_target_line) = (* 2 *) BC_TARGET EOL
minimal(build_depends_line) = (* 2 *) BUILD_DEPENDS EOL
follow(version_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(unpacksto_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(spec) = #
follow(sources_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(revision_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(package_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(options_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(options) = EOL
follow(opt_target_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(maintainer_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(lines) = EOF
follow(line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(homepage_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(docfiles_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(docfiles) = EOL
follow(description_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(deps) = EOL
follow(depends_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(dep) = error EOL COMMA
follow(confopts_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(confopts) = EOL
follow(bytecode_target_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
follow(build_depends_line) = VERSION UNPACKSTO SOURCES REVISION PACKAGE OPT_TARGET OPTIONS MAINTAINER HOMEPAGE EOF DOCFILES DESCRIPTION DEPENDS CONFOPTS BUILD_DEPENDS BC_TARGET
Built an LR(0) automaton with 109 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 109 states.
60 out of 109 states have a default reduction.
9 out of 109 states are represented.
0 out of 52 symbols keep track of their start position.
0 out of 52 symbols keep track of their end position.
55 out of 68 productions exploit shiftreduce optimization.
1 out of 109 states can peek at an error.
315 functions before inlining, 54 functions after inlining.
