Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 4 terminal symbols.
Grammar has 5 productions.
nullable(t) = false
nullable(s) = false
nullable(e) = false
first(t) = N LPAR
first(s) = N LPAR
first(e) = N LPAR
minimal(t) = (* 1 *) N
minimal(s) = (* 1 *) N
minimal(e) = (* 1 *) N
follow(t) = RPAR MINUS #
follow(s) = #
follow(e) = RPAR MINUS #
Built an LR(0) automaton with 10 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 10 states.
Warning: 5 states have an end-of-stream conflict.
File "grune924.mly", line 8, characters 2-3:
Warning: production s -> e is never reduced.
Warning: in total, 1 production is never reduced.
5 out of 10 states have a default reduction.
3 out of 10 states are represented.
0 out of 10 symbols keep track of their start position.
0 out of 10 symbols keep track of their end position.
6 out of 6 productions exploit shiftreduce optimization.
0 out of 10 states can peek at an error.
34 functions before inlining, 8 functions after inlining.
