Grammar has 11 nonterminal symbols, among which 1 start symbols.
Grammar has 28 terminal symbols.
Grammar has 36 productions.
nullable(semi_opt) = true
nullable(reg) = false
nullable(proc_list) = false
nullable(main) = false
nullable(k) = false
nullable(iol_list) = false
nullable(instr_option_list) = true
nullable(instr_option) = true
nullable(instr) = false
nullable(addr0) = false
nullable(addr) = false
first(semi_opt) = SEMI
first(reg) = SYMB_REG ARCH_REG
first(proc_list) = PROC
first(main) = SEMI PROC
first(k) = NUM META
first(iol_list) = STORE SEMI SC PIPE OPW OPIW OPI OP NAME LR LOAD LI J FENCETSO FENCEI FENCE BCC AMO
first(instr_option_list) = STORE SC PIPE OPW OPIW OPI OP NAME LR LOAD LI J FENCETSO FENCEI FENCE BCC AMO
first(instr_option) = STORE SC OPW OPIW OPI OP NAME LR LOAD LI J FENCETSO FENCEI FENCE BCC AMO
first(instr) = STORE SC OPW OPIW OPI OP LR LOAD LI J FENCETSO FENCEI FENCE BCC AMO
first(addr0) = NUM LPAR
first(addr) = NUM LPAR
minimal(semi_opt) = (* 0 *) 
minimal(reg) = (* 1 *) SYMB_REG
minimal(proc_list) = (* 2 *) PROC SEMI
minimal(main) = (* 4 *) PROC SEMI SEMI EOF
minimal(k) = (* 1 *) NUM
minimal(iol_list) = (* 1 *) SEMI
minimal(instr_option_list) = (* 0 *) 
minimal(instr_option) = (* 0 *) 
minimal(instr) = (* 1 *) FENCEI
minimal(addr0) = (* 3 *) LPAR SYMB_REG RPAR
minimal(addr) = (* 3 *) LPAR SYMB_REG RPAR
follow(semi_opt) = PROC
follow(reg) = SEMI RPAR PIPE COMMA
follow(proc_list) = STORE SEMI SC PIPE OPW OPIW OPI OP NAME LR LOAD LI J FENCETSO FENCEI FENCE BCC AMO
follow(main) = #
follow(k) = SEMI PIPE
follow(iol_list) = EOF
follow(instr_option_list) = SEMI
follow(instr_option) = SEMI PIPE
follow(instr) = SEMI PIPE
follow(addr0) = SEMI PIPE
follow(addr) = SEMI PIPE
Built an LR(0) automaton with 105 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 105 states.
File "herdtools7.7.51-RISCVParser.mly", line 55, characters 0-9:
Warning: the precedence level assigned to SEMI is never useful.
32 out of 105 states have a default reduction.
38 out of 105 states are represented.
0 out of 42 symbols keep track of their start position.
0 out of 42 symbols keep track of their end position.
26 out of 37 productions exploit shiftreduce optimization.
0 out of 105 states can peek at an error.
264 functions before inlining, 40 functions after inlining.
