File "herdtools7.7.51-X86Parser.mly", line 37, characters 8-14:
Warning: the token I_READ is unused.
Grammar has 12 nonterminal symbols, among which 1 start symbols.
Grammar has 40 terminal symbols.
Grammar has 48 productions.
nullable(semi_opt) = true
nullable(rm32) = false
nullable(reg) = false
nullable(proc_list) = false
nullable(operand) = false
nullable(main) = false
nullable(k) = false
nullable(iol_list) = false
nullable(instr_option_list) = true
nullable(instr_option) = true
nullable(instr) = false
nullable(effaddr) = false
first(semi_opt) = SEMI
first(rm32) = SYMB_REG LPAR LBRK ARCH_REG
first(reg) = SYMB_REG ARCH_REG
first(proc_list) = PROC
first(operand) = SYMB_REG NUM LPAR LBRK INTEL_NUM ARCH_REG
first(main) = SEMI PROC
first(k) = NUM
first(iol_list) = SEMI PIPE NAME I_XOR I_XCHG I_SFENCE I_SETNB I_OR I_MOVW I_MOVT I_MOVSD I_MOVQ I_MOVL I_MOVB I_MOV I_MFENCE I_LOCK I_LFENCE I_JNE I_JMP I_JE I_INC I_DEC I_CMPXCHG I_CMP I_CMOVC I_ADD
first(instr_option_list) = PIPE NAME I_XOR I_XCHG I_SFENCE I_SETNB I_OR I_MOVW I_MOVT I_MOVSD I_MOVQ I_MOVL I_MOVB I_MOV I_MFENCE I_LOCK I_LFENCE I_JNE I_JMP I_JE I_INC I_DEC I_CMPXCHG I_CMP I_CMOVC I_ADD
first(instr_option) = NAME I_XOR I_XCHG I_SFENCE I_SETNB I_OR I_MOVW I_MOVT I_MOVSD I_MOVQ I_MOVL I_MOVB I_MOV I_MFENCE I_LOCK I_LFENCE I_JNE I_JMP I_JE I_INC I_DEC I_CMPXCHG I_CMP I_CMOVC I_ADD
first(instr) = I_XOR I_XCHG I_SFENCE I_SETNB I_OR I_MOVW I_MOVT I_MOVSD I_MOVQ I_MOVL I_MOVB I_MOV I_MFENCE I_LOCK I_LFENCE I_JNE I_JMP I_JE I_INC I_DEC I_CMPXCHG I_CMP I_CMOVC I_ADD
first(effaddr) = SYMB_REG LPAR LBRK ARCH_REG
minimal(semi_opt) = (* 0 *) 
minimal(rm32) = (* 1 *) SYMB_REG
minimal(reg) = (* 1 *) SYMB_REG
minimal(proc_list) = (* 2 *) PROC SEMI
minimal(operand) = (* 1 *) SYMB_REG
minimal(main) = (* 4 *) PROC SEMI SEMI EOF
minimal(k) = (* 1 *) NUM
minimal(iol_list) = (* 1 *) SEMI
minimal(instr_option_list) = (* 0 *) 
minimal(instr_option) = (* 0 *) 
minimal(instr) = (* 1 *) I_MOVSD
minimal(effaddr) = (* 1 *) SYMB_REG
follow(semi_opt) = PROC I_XOR I_XCHG I_SFENCE I_SETNB I_OR I_MOVW I_MOVT I_MOVSD I_MOVQ I_MOVL I_MOVB I_MOV I_MFENCE I_LOCK I_LFENCE I_JNE I_JMP I_JE I_INC I_DEC I_CMPXCHG I_CMP I_CMOVC I_ADD
follow(rm32) = SEMI PIPE COMMA
follow(reg) = SEMI RPAR RBRK PIPE COMMA
follow(proc_list) = SEMI PIPE NAME I_XOR I_XCHG I_SFENCE I_SETNB I_OR I_MOVW I_MOVT I_MOVSD I_MOVQ I_MOVL I_MOVB I_MOV I_MFENCE I_LOCK I_LFENCE I_JNE I_JMP I_JE I_INC I_DEC I_CMPXCHG I_CMP I_CMOVC I_ADD
follow(operand) = SEMI PIPE
follow(main) = #
follow(k) = SEMI PIPE
follow(iol_list) = EOF
follow(instr_option_list) = SEMI
follow(instr_option) = SEMI PIPE
follow(instr) = SEMI PIPE
follow(effaddr) = SEMI PIPE COMMA
Built an LR(0) automaton with 110 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 110 states.
File "herdtools7.7.51-X86Parser.mly", line 43, characters 0-9:
Warning: the precedence level assigned to SEMI is never useful.
45 out of 110 states have a default reduction.
40 out of 110 states are represented.
0 out of 55 symbols keep track of their start position.
0 out of 55 symbols keep track of their end position.
33 out of 49 productions exploit shiftreduce optimization.
0 out of 110 states can peek at an error.
287 functions before inlining, 48 functions after inlining.
