File "hmx-sets.mly", line 69, characters 7-10:
Warning: the token TRY is unused.
File "hmx-sets.mly", line 72, characters 7-11:
Warning: the token WITH is unused.
Grammar has 8 nonterminal symbols, among which 1 start symbols.
Grammar has 25 terminal symbols.
Grammar has 30 productions.
nullable(phrase) = false
nullable(pattern_list) = true
nullable(pattern) = false
nullable(label_list) = true
nullable(expression2) = false
nullable(expression1) = false
nullable(expression0) = false
nullable(expression) = false
first(phrase) = UNIT NORMAL MATCH LPAREN LET LBRACE IDENT FUN EXC CHOOSE
first(pattern_list) = UNIT UNDERSCORE IDENT
first(pattern) = UNIT UNDERSCORE IDENT
first(label_list) = IDENT
first(expression2) = UNIT NORMAL MATCH LPAREN LBRACE IDENT EXC CHOOSE
first(expression1) = UNIT NORMAL MATCH LPAREN LBRACE IDENT EXC CHOOSE
first(expression0) = UNIT NORMAL MATCH LPAREN LBRACE IDENT EXC
first(expression) = UNIT NORMAL MATCH LPAREN LET LBRACE IDENT FUN EXC CHOOSE
minimal(phrase) = (* 2 *) IDENT SEMISEMI
minimal(pattern_list) = (* 0 *) 
minimal(pattern) = (* 1 *) IDENT
minimal(label_list) = (* 0 *) 
minimal(expression2) = (* 1 *) IDENT
minimal(expression1) = (* 1 *) IDENT
minimal(expression0) = (* 1 *) IDENT
minimal(expression) = (* 1 *) IDENT
follow(phrase) = #
follow(pattern_list) = EQUAL ARROW
follow(pattern) = UNIT UNDERSCORE IDENT EQUAL ARROW
follow(label_list) = RBRACE
follow(expression2) = SEMISEMI RPAREN IN
follow(expression1) = UNIT SEMISEMI SEMI RPAREN NORMAL MATCH LPAREN LBRACE IN IDENT EXC
follow(expression0) = UNIT TILDE SETMINUS SEMISEMI SEMI RPAREN QUESTION PLUS NORMAL MATCH LPAREN LBRACE IN IDENT EXC DOT
follow(expression) = SEMISEMI RPAREN IN
Built an LR(0) automaton with 59 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 59 states.
24 out of 59 states have a default reduction.
21 out of 59 states are represented.
0 out of 36 symbols keep track of their start position.
0 out of 36 symbols keep track of their end position.
19 out of 31 productions exploit shiftreduce optimization.
0 out of 59 states can peek at an error.
163 functions before inlining, 34 functions after inlining.
