Grammar has 9 nonterminal symbols, among which 1 start symbols.
Grammar has 3 terminal symbols.
Grammar has 9 productions.
nullable(prog) = false
nullable(a8) = false
nullable(a7) = false
nullable(a6) = false
nullable(a5) = false
nullable(a4) = false
nullable(a3) = false
nullable(a2) = false
nullable(a1) = true
first(prog) = A
first(a8) = A
first(a7) = A
first(a6) = A
first(a5) = A
first(a4) = A
first(a3) = A
first(a2) = A
first(a1) = 
minimal(prog) = (* 16 *) A B A B A A B B A C A B A B A B
minimal(a8) = (* 2 *) A B
minimal(a7) = (* 2 *) A B
minimal(a6) = (* 2 *) A B
minimal(a5) = (* 2 *) A C
minimal(a4) = (* 4 *) A A B B
minimal(a3) = (* 2 *) A B
minimal(a2) = (* 2 *) A B
minimal(a1) = (* 0 *) 
follow(prog) = #
follow(a8) = #
follow(a7) = A
follow(a6) = A
follow(a5) = A
follow(a4) = A
follow(a3) = A
follow(a2) = A
follow(a1) = A
Built an LR(0) automaton with 26 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 26 states.
10 out of 26 states have a default reduction.
0 out of 26 states are represented.
1 out of 15 symbols keep track of their start position.
3 out of 15 symbols keep track of their end position.
9 out of 10 productions exploit shiftreduce optimization.
0 out of 26 states can peek at an error.
77 functions before inlining, 2 functions after inlining.
