Grammar has 1 nonterminal symbols, among which 1 start symbols.
Grammar has 3 terminal symbols.
Grammar has 3 productions.
nullable(s) = false
first(s) = EOF A
minimal(s) = (* 1 *) EOF
follow(s) = #
Built an LR(0) automaton with 11 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 11 states.
4 out of 11 states have a default reduction.
0 out of 11 states are represented.
0 out of 7 symbols keep track of their start position.
0 out of 7 symbols keep track of their end position.
4 out of 4 productions exploit shiftreduce optimization.
0 out of 11 states can peek at an error.
33 functions before inlining, 3 functions after inlining.
