%start main
%token A
%token B
%token C
%token D
%token E
%type <unit> main
%%

main:
  _1 = A _1_inlined1 = B _2 = C a = D e = E
    {let a =
  let (_startpos__1_, _1) = (_startpos__1_inlined1_, _1_inlined1) in
  let _startpos = _startpos__1_ in
                            ( _startpos_a_, _startpos )
in
let _startpos_a_ = _startpos__1_inlined1_ in
let _startpos = _startpos__1_ in
                         ( a, _startpos_a_, _startpos, _startpos_e_ )}

%%


