Grammar has 1 nonterminal symbols, among which 1 start symbols.
Grammar has 5 terminal symbols.
Grammar has 1 productions.
nullable(main) = false
first(main) = A
minimal(main) = (* 5 *) A B C D E
follow(main) = #
Built an LR(0) automaton with 7 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 7 states.
2 out of 7 states have a default reduction.
0 out of 7 states are represented.
4 out of 9 symbols keep track of their start position.
0 out of 9 symbols keep track of their end position.
2 out of 2 productions exploit shiftreduce optimization.
0 out of 7 states can peek at an error.
23 functions before inlining, 2 functions after inlining.
