%start commandline
%token EOF
%token IN
%token LET
%token NAME
%token PLUS
%token REC
%type <unit> commandline
%%

commandline:
  _1 = LET _2 = term _3 = EOF
    {    ( () )}
| _1 = term _2 = EOF
    {    ( () )}

term:
  _1 = NAME
    {    ( () )}
| _1 = name _2 = PLUS
    {    ( () )}
| _1 = LET _2 = name _3 = IN _4 = term
    {    ( () )}
| _1 = REC _2 = term _3 = IN _4 = term
    {    ( () )}

name:
  _1 = NAME
    {    ( () )}

%%


