Grammar has 1 nonterminal symbols, among which 1 start symbols.
Grammar has 1 terminal symbols.
Grammar has 1 productions.
nullable(s) = false
first(s) = X
minimal(s) = (* 1 *) X
follow(s) = #
Built an LR(0) automaton with 3 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 3 states.
2 out of 3 states have a default reduction.
0 out of 3 states are represented.
0 out of 5 symbols keep track of their start position.
0 out of 5 symbols keep track of their end position.
2 out of 2 productions exploit shiftreduce optimization.
0 out of 3 states can peek at an error.
15 functions before inlining, 1 functions after inlining.
