File "labltk-ppyac.mly", line 28, characters 7-10:
Warning: the token EOF is unused.
%{
open Code
%}
%start code_list
%token <string> DEFINE
%token ELSE
%token ENDIF
%token EOF
%token <string> IFDEF
%token <string> IFNDEF
%token <string> OTHER
%token <string> UNDEF
%type <Code.code list> code_list
%%

code_list:
  
    {                ( [] )}
| _1 = code _2 = code_list
    {                   ( _1 :: _2 )}

code:
  _1 = DEFINE
    {           ( Define _1 )}
| _1 = UNDEF
    {          ( Undef _1 )}
| _1 = IFDEF _2 = code_list _3 = ELSE _4 = code_list _5 = ENDIF
    {                                         ( Ifdef (true, _1, _2, Some (_4)) )}
| _1 = IFNDEF _2 = code_list _3 = ELSE _4 = code_list _5 = ENDIF
    {                                          ( Ifdef (false, _1, _2, Some (_4)) )}
| _1 = IFDEF _2 = code_list _3 = ENDIF
    {                          ( Ifdef (true, _1, _2, None) )}
| _1 = IFNDEF _2 = code_list _3 = ENDIF
    {                           ( Ifdef (false, _1, _2, None) )}
| _1 = OTHER
    {          ( Line _1 )}

%%




