Grammar has 16 nonterminal symbols, among which 1 start symbols.
Grammar has 28 terminal symbols.
Grammar has 57 productions.
nullable(term) = false
nullable(sterm) = false
nullable(separated_nonempty_list(COMMA,context_item)) = false
nullable(rule) = false
nullable(param) = false
nullable(option(__anonymous_0)) = true
nullable(nonempty_list(rule)) = false
nullable(nonempty_list(param)) = false
nullable(loption(separated_nonempty_list(COMMA,context_item))) = true
nullable(list(sterm)) = true
nullable(list(param)) = true
nullable(line) = false
nullable(eval_config) = false
nullable(context_item) = false
nullable(context) = true
nullable(aterm) = false
first(term) = UNDERSCORE TYPE QID LEFTPAR ID
first(sterm) = UNDERSCORE TYPE QID LEFTPAR ID
first(separated_nonempty_list(COMMA,context_item)) = ID
first(rule) = LEFTSQU
first(param) = LEFTPAR
first(option(__anonymous_0)) = COLON
first(nonempty_list(rule)) = LEFTSQU
first(nonempty_list(param)) = LEFTPAR
first(loption(separated_nonempty_list(COMMA,context_item))) = ID
first(list(sterm)) = UNDERSCORE TYPE QID LEFTPAR ID
first(list(param)) = LEFTPAR
first(line) = REQUIRE NAME LEFTSQU KW_THM KW_INJ KW_DEF INFER ID EVAL EOF CHECKNOT CHECK ASSERTNOT ASSERT
first(eval_config) = LEFTSQU
first(context_item) = ID
first(context) = ID
first(aterm) = UNDERSCORE TYPE QID LEFTPAR ID
minimal(term) = (* 1 *) QID
minimal(sterm) = (* 1 *) QID
minimal(separated_nonempty_list(COMMA,context_item)) = (* 1 *) ID
minimal(rule) = (* 5 *) LEFTSQU RIGHTSQU QID LONGARROW QID
minimal(param) = (* 5 *) LEFTPAR ID COLON QID RIGHTPAR
minimal(option(__anonymous_0)) = (* 0 *) 
minimal(nonempty_list(rule)) = (* 5 *) LEFTSQU RIGHTSQU QID LONGARROW QID
minimal(nonempty_list(param)) = (* 5 *) LEFTPAR ID COLON QID RIGHTPAR
minimal(loption(separated_nonempty_list(COMMA,context_item))) = (* 0 *) 
minimal(list(sterm)) = (* 0 *) 
minimal(list(param)) = (* 0 *) 
minimal(line) = (* 1 *) EOF
minimal(eval_config) = (* 3 *) LEFTSQU ID RIGHTSQU
minimal(context_item) = (* 1 *) ID
minimal(context) = (* 0 *) 
minimal(aterm) = (* 1 *) QID
follow(term) = RIGHTSQU RIGHTPAR LONGARROW LEFTSQU DOT DEF COMMA ARROW
follow(sterm) = UNDERSCORE TYPE RIGHTSQU RIGHTPAR QID LONGARROW LEFTSQU LEFTPAR ID FATARROW EQUAL DOT DEF COMMA COLON ARROW
follow(separated_nonempty_list(COMMA,context_item)) = RIGHTSQU
follow(rule) = LEFTSQU DOT
follow(param) = LEFTPAR DEF COLON
follow(option(__anonymous_0)) = RIGHTSQU COMMA
follow(nonempty_list(rule)) = DOT
follow(nonempty_list(param)) = DEF COLON
follow(loption(separated_nonempty_list(COMMA,context_item))) = RIGHTSQU
follow(list(sterm)) = RIGHTSQU RIGHTPAR LONGARROW LEFTSQU FATARROW EQUAL DOT DEF COMMA COLON ARROW
follow(list(param)) = COLON
follow(line) = #
follow(eval_config) = UNDERSCORE TYPE QID LEFTPAR ID
follow(context_item) = RIGHTSQU COMMA
follow(context) = RIGHTSQU
follow(aterm) = RIGHTSQU RIGHTPAR LONGARROW LEFTSQU FATARROW EQUAL DOT DEF COMMA COLON ARROW
Built an LR(0) automaton with 158 states.
The grammar is not SLR(1) -- 7 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 158 states.
5 shift/reduce conflicts were silently solved.
44 out of 158 states have a default reduction.
52 out of 158 states are represented.
0 out of 47 symbols keep track of their start position.
0 out of 47 symbols keep track of their end position.
39 out of 58 productions exploit shiftreduce optimization.
0 out of 158 states can peek at an error.
396 functions before inlining, 33 functions after inlining.
