File "ldap.2.4.0-ldap_filterparser.mly", line 38, characters 7-11:
Warning: the token WHSP is unused.
Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 15 terminal symbols.
Grammar has 15 productions.
nullable(filterlist) = false
nullable(filter_and_eof) = false
nullable(filter) = false
first(filterlist) = LPAREN ATTRPRESENT ATTRLTE ATTRGTE ATTREXTENDEDMATCH ATTREXTENDEDDN ATTREQUALSUB ATTREQUAL ATTRAPPROX
first(filter_and_eof) = LPAREN ATTRPRESENT ATTRLTE ATTRGTE ATTREXTENDEDMATCH ATTREXTENDEDDN ATTREQUALSUB ATTREQUAL ATTRAPPROX
first(filter) = LPAREN ATTRPRESENT ATTRLTE ATTRGTE ATTREXTENDEDMATCH ATTREXTENDEDDN ATTREQUALSUB ATTREQUAL ATTRAPPROX
minimal(filterlist) = (* 1 *) ATTREQUALSUB
minimal(filter_and_eof) = (* 2 *) ATTREQUALSUB EOF
minimal(filter) = (* 1 *) ATTREQUALSUB
follow(filterlist) = RPAREN LPAREN ATTRPRESENT ATTRLTE ATTRGTE ATTREXTENDEDMATCH ATTREXTENDEDDN ATTREQUALSUB ATTREQUAL ATTRAPPROX
follow(filter_and_eof) = #
follow(filter) = RPAREN LPAREN EOF ATTRPRESENT ATTRLTE ATTRGTE ATTREXTENDEDMATCH ATTREXTENDEDDN ATTREQUALSUB ATTREQUAL ATTRAPPROX
Built an LR(0) automaton with 26 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 26 states.
16 out of 26 states have a default reduction.
7 out of 26 states are represented.
0 out of 21 symbols keep track of their start position.
0 out of 21 symbols keep track of their end position.
14 out of 16 productions exploit shiftreduce optimization.
0 out of 26 states can peek at an error.
77 functions before inlining, 14 functions after inlining.
