%{
  open Structures
%}
%start main
%token CP
%token DIRECTIVE
%token END
%token IMP
%token LIMP
%token NEG
%token NEXT
%token OP
%token PAR
%token RIMP
%token SEQ
%token TIMES
%token <string> VAR
%token VDASH
%left PAR SEQ
%left NEXT TIMES
%nonassoc NEG
%type <[`Directive of string | `Sequent of Structures.sequent]> main
%%

main:
  _1 = sequent _2 = END
    {              (`Sequent _1)}
| _1 = DIRECTIVE _2 = VAR
    {                (`Directive _2)}

formimp:
  _1 = VAR
    {       (`Var _1)}
| _1 = formimp _2 = PAR _3 = formimp
    {                      (`Par(_1,_3))}
| _1 = formimp _2 = TIMES _3 = formimp
    {                        (`Times(_1,_3))}
| _1 = formimp _2 = NEXT _3 = formimp
    {                       (`Next(_1,_3))}
| _1 = formimp _2 = SEQ _3 = formimp
    {                      (`Seq(_1,_3))}
| _1 = formimp _2 = IMP _3 = formimp
    {                      (`Imp(_1,_3))}
| _1 = formimp _2 = RIMP _3 = formimp
    {                       (`RImp(_1,_3))}
| _1 = formimp _2 = LIMP _3 = formimp
    {                       (`LImp(_1,_3))}
| _1 = OP _2 = formimp _3 = CP
    {                (_2)}
| _1 = formimp _2 = NEG
    {              (`Not(_1))}

sequent:
  _1 = formimp _2 = VDASH _3 = formimp
    {                      (Sequent(_1, _3))}
| _1 = VDASH _2 = formimp
    {                (Form(_2))}
| _1 = formimp
    {          (Form(_1))}

%%


