Grammar has 3 nonterminal symbols, among which 1 start symbols.
Grammar has 5 terminal symbols.
Grammar has 6 productions.
nullable(s) = false
nullable(f) = false
nullable(e) = false
first(s) = B A
first(f) = F
first(e) = F
minimal(s) = (* 3 *) A F C
minimal(f) = (* 1 *) F
minimal(e) = (* 1 *) F
follow(s) = #
follow(f) = D C
follow(e) = D C
Built an LR(0) automaton with 13 states.
The grammar is not SLR(1) -- 1 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 14 states.
5 out of 14 states have a default reduction.
2 out of 14 states are represented.
0 out of 11 symbols keep track of their start position.
0 out of 11 symbols keep track of their end position.
5 out of 7 productions exploit shiftreduce optimization.
0 out of 14 states can peek at an error.
44 functions before inlining, 6 functions after inlining.
