Grammar has 9 nonterminal symbols, among which 1 start symbols.
Grammar has 36 terminal symbols.
Grammar has 45 productions.
nullable(ltl) = false
nullable(logic_relation) = false
nullable(formula) = false
nullable(arith_relation_mul) = false
nullable(arith_relation) = false
nullable(access_or_const) = false
nullable(access_leaf) = false
nullable(access_array) = false
nullable(access) = false
first(ltl) = LTL_TRUE LTL_STAR LTL_RETURN LTL_NOT LTL_NEXT LTL_MINUS LTL_LPAREN LTL_LABEL LTL_INT LTL_GLOBALLY LTL_FATALLY LTL_FALSE LTL_CALL_OR_RETURN LTL_CALL LTL_ADRESSE
first(logic_relation) = LTL_STAR LTL_MINUS LTL_LPAREN LTL_LABEL LTL_INT LTL_ADRESSE
first(formula) = LTL_TRUE LTL_STAR LTL_RETURN LTL_NOT LTL_NEXT LTL_MINUS LTL_LPAREN LTL_LABEL LTL_INT LTL_GLOBALLY LTL_FATALLY LTL_FALSE LTL_CALL_OR_RETURN LTL_CALL LTL_ADRESSE
first(arith_relation_mul) = LTL_STAR LTL_MINUS LTL_LPAREN LTL_LABEL LTL_INT LTL_ADRESSE
first(arith_relation) = LTL_STAR LTL_MINUS LTL_LPAREN LTL_LABEL LTL_INT LTL_ADRESSE
first(access_or_const) = LTL_STAR LTL_MINUS LTL_LPAREN LTL_LABEL LTL_INT LTL_ADRESSE
first(access_leaf) = LTL_STAR LTL_LPAREN LTL_LABEL LTL_ADRESSE
first(access_array) = LTL_STAR LTL_LPAREN LTL_LABEL LTL_ADRESSE
first(access) = LTL_STAR LTL_LPAREN LTL_LABEL LTL_ADRESSE
minimal(ltl) = (* 2 *) LTL_TRUE EOF
minimal(logic_relation) = (* 1 *) LTL_INT
minimal(formula) = (* 1 *) LTL_TRUE
minimal(arith_relation_mul) = (* 1 *) LTL_INT
minimal(arith_relation) = (* 1 *) LTL_INT
minimal(access_or_const) = (* 1 *) LTL_INT
minimal(access_leaf) = (* 1 *) LTL_LABEL
minimal(access_array) = (* 1 *) LTL_LABEL
minimal(access) = (* 1 *) LTL_LABEL
follow(ltl) = #
follow(logic_relation) = LTL_UNTIL LTL_RPAREN LTL_RELEASE LTL_OR LTL_LEFT_RIGHT_ARROW LTL_IMPLIES LTL_AND EOF
follow(formula) = LTL_UNTIL LTL_RPAREN LTL_RELEASE LTL_OR LTL_LEFT_RIGHT_ARROW LTL_IMPLIES LTL_AND EOF
follow(arith_relation_mul) = LTL_UNTIL LTL_STAR LTL_RPAREN LTL_RELEASE LTL_PLUS LTL_OR LTL_NEQ LTL_MODULO LTL_MINUS LTL_LT LTL_LEFT_RIGHT_ARROW LTL_LE LTL_IMPLIES LTL_GT LTL_GE LTL_EQ LTL_DIV LTL_AND EOF
follow(arith_relation) = LTL_UNTIL LTL_RPAREN LTL_RELEASE LTL_OR LTL_NEQ LTL_LT LTL_LEFT_RIGHT_ARROW LTL_LE LTL_IMPLIES LTL_GT LTL_GE LTL_EQ LTL_AND EOF
follow(access_or_const) = LTL_UNTIL LTL_STAR LTL_RPAREN LTL_RIGHT_SQUARE LTL_RELEASE LTL_PLUS LTL_OR LTL_NEQ LTL_MODULO LTL_MINUS LTL_LT LTL_LEFT_RIGHT_ARROW LTL_LE LTL_IMPLIES LTL_GT LTL_GE LTL_EQ LTL_DIV LTL_AND EOF
follow(access_leaf) = LTL_UNTIL LTL_STAR LTL_RPAREN LTL_RIGHT_SQUARE LTL_RIGHT_ARROW LTL_RELEASE LTL_PLUS LTL_OR LTL_NEQ LTL_MODULO LTL_MINUS LTL_LT LTL_LEFT_SQUARE LTL_LEFT_RIGHT_ARROW LTL_LE LTL_IMPLIES LTL_GT LTL_GE LTL_EQ LTL_DOT LTL_DIV LTL_AND EOF
follow(access_array) = LTL_UNTIL LTL_STAR LTL_RPAREN LTL_RIGHT_SQUARE LTL_RIGHT_ARROW LTL_RELEASE LTL_PLUS LTL_OR LTL_NEQ LTL_MODULO LTL_MINUS LTL_LT LTL_LEFT_SQUARE LTL_LEFT_RIGHT_ARROW LTL_LE LTL_IMPLIES LTL_GT LTL_GE LTL_EQ LTL_DOT LTL_DIV LTL_AND EOF
follow(access) = LTL_UNTIL LTL_STAR LTL_RPAREN LTL_RIGHT_SQUARE LTL_RIGHT_ARROW LTL_RELEASE LTL_PLUS LTL_OR LTL_NEQ LTL_MODULO LTL_MINUS LTL_LT LTL_LEFT_SQUARE LTL_LEFT_RIGHT_ARROW LTL_LE LTL_IMPLIES LTL_GT LTL_GE LTL_EQ LTL_DOT LTL_DIV LTL_AND EOF
Built an LR(0) automaton with 93 states.
The grammar is not SLR(1) -- 15 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 93 states.
60 shift/reduce conflicts were silently solved.
File "ltlparser.mly", line 64, characters 0-6:
Warning: the precedence level assigned to LTL_DIV is never useful.
File "ltlparser.mly", line 58, characters 0-6:
Warning: the precedence level assigned to LTL_EQ is never useful.
File "ltlparser.mly", line 58, characters 0-6:
Warning: the precedence level assigned to LTL_GE is never useful.
File "ltlparser.mly", line 58, characters 0-6:
Warning: the precedence level assigned to LTL_GT is never useful.
File "ltlparser.mly", line 58, characters 0-6:
Warning: the precedence level assigned to LTL_LE is never useful.
File "ltlparser.mly", line 58, characters 0-6:
Warning: the precedence level assigned to LTL_LT is never useful.
File "ltlparser.mly", line 64, characters 0-6:
Warning: the precedence level assigned to LTL_MINUS is never useful.
File "ltlparser.mly", line 64, characters 0-6:
Warning: the precedence level assigned to LTL_MODULO is never useful.
File "ltlparser.mly", line 58, characters 0-6:
Warning: the precedence level assigned to LTL_NEQ is never useful.
File "ltlparser.mly", line 64, characters 0-6:
Warning: the precedence level assigned to LTL_PLUS is never useful.
File "ltlparser.mly", line 64, characters 0-6:
Warning: the precedence level assigned to LTL_STAR is never useful.
Warning: 5 states have shift/reduce conflicts.
Warning: 7 shift/reduce conflicts were arbitrarily resolved.
30 out of 93 states have a default reduction.
28 out of 93 states are represented.
0 out of 48 symbols keep track of their start position.
0 out of 48 symbols keep track of their end position.
18 out of 46 productions exploit shiftreduce optimization.
0 out of 93 states can peek at an error.
247 functions before inlining, 47 functions after inlining.
