File "mcc-frontends.mly", line 31, characters 7-14:
Warning: the token TokSemi is unused.
Grammar has 10 nonterminal symbols, among which 1 start symbols.
Grammar has 8 terminal symbols.
Grammar has 13 productions.
nullable(string_list_rev) = false
nullable(string_list) = false
nullable(section_list_rev) = false
nullable(section_list) = false
nullable(section) = false
nullable(main) = false
nullable(identifier) = false
nullable(assignment_list_rev) = false
nullable(assignment_list) = false
nullable(assignment) = false
first(string_list_rev) = TokString
first(string_list) = TokString
first(section_list_rev) = TokLeftBrack
first(section_list) = TokLeftBrack
first(section) = TokLeftBrack
first(main) = TokLeftBrack
first(identifier) = TokId
first(assignment_list_rev) = TokId
first(assignment_list) = TokId
first(assignment) = TokId
minimal(string_list_rev) = (* 1 *) TokString
minimal(string_list) = (* 1 *) TokString
minimal(section_list_rev) = (* 6 *) TokLeftBrack TokId TokRightBrack TokId TokEq TokString
minimal(section_list) = (* 6 *) TokLeftBrack TokId TokRightBrack TokId TokEq TokString
minimal(section) = (* 6 *) TokLeftBrack TokId TokRightBrack TokId TokEq TokString
minimal(main) = (* 7 *) TokLeftBrack TokId TokRightBrack TokId TokEq TokString TokEof
minimal(identifier) = (* 1 *) TokId
minimal(assignment_list_rev) = (* 3 *) TokId TokEq TokString
minimal(assignment_list) = (* 3 *) TokId TokEq TokString
minimal(assignment) = (* 3 *) TokId TokEq TokString
follow(string_list_rev) = TokLeftBrack TokId TokEof TokComma
follow(string_list) = TokLeftBrack TokId TokEof
follow(section_list_rev) = TokLeftBrack TokEof
follow(section_list) = TokEof
follow(section) = TokLeftBrack TokEof
follow(main) = #
follow(identifier) = TokRightBrack TokEq
follow(assignment_list_rev) = TokLeftBrack TokId TokEof
follow(assignment_list) = TokLeftBrack TokEof
follow(assignment) = TokLeftBrack TokId TokEof
Built an LR(0) automaton with 22 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 22 states.
11 out of 22 states have a default reduction.
5 out of 22 states are represented.
0 out of 21 symbols keep track of their start position.
0 out of 21 symbols keep track of their end position.
11 out of 14 productions exploit shiftreduce optimization.
0 out of 22 states can peek at an error.
74 functions before inlining, 9 functions after inlining.
