File "mcc-fj.mly", line 195, characters 35-44:
Warning: the token TokAssign is unused.
File "mcc-fj.mly", line 204, characters 20-27:
Warning: the token TokCase is unused.
File "mcc-fj.mly", line 210, characters 20-30:
Warning: the token TokDefault is unused.
File "mcc-fj.mly", line 219, characters 20-27:
Warning: the token TokGoto is unused.
File "mcc-fj.mly", line 255, characters 20-28:
Warning: the token TokQuest is unused.
File "mcc-fj.mly", line 260, characters 20-33:
Warning: the token TokRightArrow is unused.
File "mcc-fj.mly", line 238, characters 20-29:
Warning: the token TokSwitch is unused.
File "mcc-fj.mly", line 242, characters 20-29:
Warning: the token TokThrows is unused.
Grammar has 56 nonterminal symbols, among which 1 start symbols.
Grammar has 83 terminal symbols.
Grammar has 172 productions.
nullable(var_list) = false
nullable(var_defs) = false
nullable(var_decl_list) = false
nullable(var_decl) = false
nullable(type_spec) = false
nullable(type_mod) = false
nullable(stmt_list) = true
nullable(stmt) = false
nullable(rev_var_list) = false
nullable(rev_var_decl_list) = false
nullable(rev_type_mod_list) = true
nullable(rev_stmt_list) = true
nullable(rev_member_defs) = true
nullable(rev_interface_body) = true
nullable(rev_init_def_list) = false
nullable(rev_import_list) = false
nullable(rev_dotted_name) = false
nullable(rev_class_or_interface_defs) = true
nullable(rev_catches) = true
nullable(rev_brackets) = false
nullable(rev_arg_list) = false
nullable(prog) = false
nullable(opt_var_decl_list) = true
nullable(opt_package_stmt) = true
nullable(opt_label) = true
nullable(opt_import_list) = true
nullable(opt_implements) = true
nullable(opt_finally) = true
nullable(opt_extends_list) = true
nullable(opt_extends) = true
nullable(opt_expr) = true
nullable(new_type) = false
nullable(new_expr) = false
nullable(new_const) = false
nullable(new_array) = false
nullable(ncast_expr) = false
nullable(member_def) = false
nullable(interface_def) = false
nullable(init_def_list) = false
nullable(init_def) = false
nullable(import_stmt) = false
nullable(id_brackets) = false
nullable(fun_def) = false
nullable(fun_decl) = false
nullable(expr) = false
nullable(direct_decl) = false
nullable(const_def) = false
nullable(class_or_interface_defs) = true
nullable(class_or_interface_def_content) = false
nullable(class_or_interface_def) = false
nullable(class_def) = false
nullable(class_body) = true
nullable(cast_expr) = false
nullable(brackets) = false
nullable(binop) = false
nullable(arg_list) = true
first(var_list) = TokId
first(var_defs) = TokId
first(var_decl_list) = TokId
first(var_decl) = TokId
first(type_spec) = TokId
first(type_mod) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokFinal TokConst TokAbstract
first(stmt_list) = TokWhile TokTry TokTrue TokThrow TokString TokSemi TokReturn TokPlusPlus TokNil TokNew TokMinusMinus TokMinus TokLeftParen TokLeftBrace TokInt TokIf TokId TokFor TokFloat TokFalse TokDo TokContinue TokChar TokBreak TokBang
first(stmt) = TokWhile TokTry TokTrue TokThrow TokString TokSemi TokReturn TokPlusPlus TokNil TokNew TokMinusMinus TokMinus TokLeftParen TokLeftBrace TokInt TokIf TokId TokFor TokFloat TokFalse TokDo TokContinue TokChar TokBreak TokBang
first(rev_var_list) = TokId
first(rev_var_decl_list) = TokId
first(rev_type_mod_list) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokFinal TokConst TokAbstract
first(rev_stmt_list) = TokWhile TokTry TokTrue TokThrow TokString TokSemi TokReturn TokPlusPlus TokNil TokNew TokMinusMinus TokMinus TokLeftParen TokLeftBrace TokInt TokIf TokId TokFor TokFloat TokFalse TokDo TokContinue TokChar TokBreak TokBang
first(rev_member_defs) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokId TokFinal TokConst TokAbstract
first(rev_interface_body) = TokId
first(rev_init_def_list) = TokId
first(rev_import_list) = TokImport
first(rev_dotted_name) = TokId
first(rev_class_or_interface_defs) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokFinal TokConst TokClass TokAbstract
first(rev_catches) = TokCatch
first(rev_brackets) = TokLeftBrack
first(rev_arg_list) = TokTrue TokThrow TokString TokPlusPlus TokNil TokNew TokMinusMinus TokMinus TokLeftParen TokInt TokId TokFloat TokFalse TokChar TokBang
first(prog) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokPackage TokNative TokInterface TokImport TokFinal TokEof TokConst TokClass TokAbstract
first(opt_var_decl_list) = TokId
first(opt_package_stmt) = TokPackage
first(opt_label) = TokId
first(opt_import_list) = TokImport
first(opt_implements) = TokImplements
first(opt_finally) = TokFinally
first(opt_extends_list) = TokExtends
first(opt_extends) = TokExtends
first(opt_expr) = TokTrue TokThrow TokString TokPlusPlus TokNil TokNew TokMinusMinus TokMinus TokLeftParen TokInt TokId TokFloat TokFalse TokChar TokBang
first(new_type) = TokId
first(new_expr) = TokId
first(new_const) = TokId
first(new_array) = TokId
first(ncast_expr) = TokTrue TokThrow TokString TokPlusPlus TokNil TokNew TokMinusMinus TokMinus TokLeftParen TokInt TokId TokFloat TokFalse TokChar TokBang
first(member_def) = TokId
first(interface_def) = TokInterface
first(init_def_list) = TokId
first(init_def) = TokId
first(import_stmt) = TokImport
first(id_brackets) = TokId
first(fun_def) = TokId
first(fun_decl) = TokId
first(expr) = TokTrue TokThrow TokString TokPlusPlus TokNil TokNew TokMinusMinus TokMinus TokLeftParen TokInt TokId TokFloat TokFalse TokChar TokBang
first(direct_decl) = TokId
first(const_def) = TokId
first(class_or_interface_defs) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokFinal TokConst TokClass TokAbstract
first(class_or_interface_def_content) = TokInterface TokClass
first(class_or_interface_def) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokFinal TokConst TokClass TokAbstract
first(class_def) = TokClass
first(class_body) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokId TokFinal TokConst TokAbstract
first(cast_expr) = TokLeftParen TokId
first(brackets) = TokDoubleBrack
first(binop) = TokStar TokSlash TokPlus TokPipe TokPercent TokMinus TokLsr TokLsl TokHat TokAsr TokAmp
first(arg_list) = TokTrue TokThrow TokString TokPlusPlus TokNil TokNew TokMinusMinus TokMinus TokLeftParen TokInt TokId TokFloat TokFalse TokChar TokBang
minimal(var_list) = (* 1 *) TokId
minimal(var_defs) = (* 3 *) TokId TokId TokSemi
minimal(var_decl_list) = (* 2 *) TokId TokId
minimal(var_decl) = (* 2 *) TokId TokId
minimal(type_spec) = (* 1 *) TokId
minimal(type_mod) = (* 1 *) TokPublic
minimal(stmt_list) = (* 0 *) 
minimal(stmt) = (* 1 *) TokSemi
minimal(rev_var_list) = (* 1 *) TokId
minimal(rev_var_decl_list) = (* 2 *) TokId TokId
minimal(rev_type_mod_list) = (* 0 *) 
minimal(rev_stmt_list) = (* 0 *) 
minimal(rev_member_defs) = (* 0 *) 
minimal(rev_interface_body) = (* 0 *) 
minimal(rev_init_def_list) = (* 1 *) TokId
minimal(rev_import_list) = (* 3 *) TokImport TokId TokSemi
minimal(rev_dotted_name) = (* 1 *) TokId
minimal(rev_class_or_interface_defs) = (* 0 *) 
minimal(rev_catches) = (* 0 *) 
minimal(rev_brackets) = (* 3 *) TokLeftBrack TokInt TokRightBrack
minimal(rev_arg_list) = (* 1 *) TokInt
minimal(prog) = (* 1 *) TokEof
minimal(opt_var_decl_list) = (* 0 *) 
minimal(opt_package_stmt) = (* 0 *) 
minimal(opt_label) = (* 0 *) 
minimal(opt_import_list) = (* 0 *) 
minimal(opt_implements) = (* 0 *) 
minimal(opt_finally) = (* 0 *) 
minimal(opt_extends_list) = (* 0 *) 
minimal(opt_extends) = (* 0 *) 
minimal(opt_expr) = (* 0 *) 
minimal(new_type) = (* 2 *) TokId TokDoubleBrack
minimal(new_expr) = (* 3 *) TokId TokLeftParen TokRightParen
minimal(new_const) = (* 3 *) TokId TokLeftParen TokRightParen
minimal(new_array) = (* 1 *) TokId
minimal(ncast_expr) = (* 1 *) TokInt
minimal(member_def) = (* 3 *) TokId TokId TokSemi
minimal(interface_def) = (* 4 *) TokInterface TokId TokLeftBrace TokRightBrace
minimal(init_def_list) = (* 1 *) TokId
minimal(init_def) = (* 1 *) TokId
minimal(import_stmt) = (* 3 *) TokImport TokId TokSemi
minimal(id_brackets) = (* 1 *) TokId
minimal(fun_def) = (* 4 *) TokId TokId TokLeftBrace TokRightBrace
minimal(fun_decl) = (* 3 *) TokId TokLeftParen TokRightParen
minimal(expr) = (* 1 *) TokInt
minimal(direct_decl) = (* 1 *) TokId
minimal(const_def) = (* 3 *) TokId TokLeftBrace TokRightBrace
minimal(class_or_interface_defs) = (* 0 *) 
minimal(class_or_interface_def_content) = (* 4 *) TokClass TokId TokLeftBrace TokRightBrace
minimal(class_or_interface_def) = (* 4 *) TokClass TokId TokLeftBrace TokRightBrace
minimal(class_def) = (* 4 *) TokClass TokId TokLeftBrace TokRightBrace
minimal(class_body) = (* 0 *) 
minimal(cast_expr) = (* 1 *) TokId
minimal(brackets) = (* 1 *) TokDoubleBrack
minimal(binop) = (* 1 *) TokPlus
minimal(arg_list) = (* 0 *) 
follow(var_list) = TokLeftBrace
follow(var_defs) = TokWhile TokVolatile TokTry TokTrue TokTransient TokThrow TokSynchronized TokString TokStrictfp TokStatic TokSemi TokRightBrace TokReturn TokPublic TokProtected TokPrivate TokPlusPlus TokNil TokNew TokNative TokMinusMinus TokMinus TokLeftParen TokLeftBrace TokInt TokIf TokId TokFor TokFloat TokFinal TokFalse TokElse TokDo TokContinue TokConst TokChar TokBreak TokBang TokAbstract
follow(var_decl_list) = TokRightParen
follow(var_decl) = TokSemi TokRightParen TokComma
follow(type_spec) = TokId
follow(type_mod) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokId TokFinal TokConst TokClass TokAbstract
follow(stmt_list) = TokRightBrace
follow(stmt) = TokWhile TokTry TokTrue TokThrow TokString TokSemi TokRightBrace TokReturn TokPlusPlus TokNil TokNew TokMinusMinus TokMinus TokLeftParen TokLeftBrace TokInt TokIf TokId TokFor TokFloat TokFalse TokElse TokDo TokContinue TokChar TokBreak TokBang
follow(rev_var_list) = TokLeftBrace TokComma
follow(rev_var_decl_list) = TokSemi TokRightParen TokComma
follow(rev_type_mod_list) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokId TokFinal TokConst TokClass TokAbstract
follow(rev_stmt_list) = TokWhile TokTry TokTrue TokThrow TokString TokSemi TokRightBrace TokReturn TokPlusPlus TokNil TokNew TokMinusMinus TokMinus TokLeftParen TokLeftBrace TokInt TokIf TokId TokFor TokFloat TokFalse TokDo TokContinue TokChar TokBreak TokBang
follow(rev_member_defs) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokRightBrace TokPublic TokProtected TokPrivate TokNative TokId TokFinal TokConst TokAbstract
follow(rev_interface_body) = TokRightBrace TokId
follow(rev_init_def_list) = TokSemi TokComma
follow(rev_import_list) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokImport TokFinal TokEof TokConst TokClass TokAbstract
follow(rev_dotted_name) = TokSemi TokDot
follow(rev_class_or_interface_defs) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokFinal TokEof TokConst TokClass TokAbstract
follow(rev_catches) = TokWhile TokTry TokTrue TokThrow TokString TokSemi TokRightBrace TokReturn TokPlusPlus TokNil TokNew TokMinusMinus TokMinus TokLeftParen TokLeftBrace TokInt TokIf TokId TokFor TokFloat TokFinally TokFalse TokElse TokDo TokContinue TokChar TokCatch TokBreak TokBang
follow(rev_brackets) = TokStar TokSlash TokSemi TokRightParen TokRightBrack TokPlusPlus TokPlus TokPipe TokPercent TokNotEq TokMinusMinus TokMinus TokLt TokLsr TokLsl TokLeftBrack TokLe TokLOr TokLAnd TokInstanceof TokHat TokGt TokGe TokEqEq TokEq TokComma TokAsr TokAmp
follow(rev_arg_list) = TokRightParen TokComma
follow(prog) = #
follow(opt_var_decl_list) = TokRightParen
follow(opt_package_stmt) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokImport TokFinal TokEof TokConst TokClass TokAbstract
follow(opt_label) = TokSemi
follow(opt_import_list) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokFinal TokEof TokConst TokClass TokAbstract
follow(opt_implements) = TokLeftBrace
follow(opt_finally) = TokWhile TokTry TokTrue TokThrow TokString TokSemi TokRightBrace TokReturn TokPlusPlus TokNil TokNew TokMinusMinus TokMinus TokLeftParen TokLeftBrace TokInt TokIf TokId TokFor TokFloat TokFalse TokElse TokDo TokContinue TokChar TokBreak TokBang
follow(opt_extends_list) = TokLeftBrace
follow(opt_extends) = TokLeftBrace TokImplements
follow(opt_expr) = TokSemi TokRightParen
follow(new_type) = TokLeftParen TokLeftBrack TokDoubleBrack
follow(new_expr) = TokStar TokSlash TokSemi TokRightParen TokRightBrack TokPlusPlus TokPlus TokPipe TokPercent TokNotEq TokMinusMinus TokMinus TokLt TokLsr TokLsl TokLe TokLOr TokLAnd TokInstanceof TokHat TokGt TokGe TokEqEq TokEq TokComma TokAsr TokAmp
follow(new_const) = TokStar TokSlash TokSemi TokRightParen TokRightBrack TokPlusPlus TokPlus TokPipe TokPercent TokNotEq TokMinusMinus TokMinus TokLt TokLsr TokLsl TokLeftParen TokLeftBrack TokLe TokLOr TokLAnd TokInstanceof TokHat TokGt TokGe TokEqEq TokEq TokDoubleBrack TokComma TokAsr TokAmp
follow(new_array) = TokLeftBrack
follow(ncast_expr) = TokStar TokSlash TokSemi TokRightParen TokRightBrack TokPlusPlus TokPlus TokPipe TokPercent TokNotEq TokMinusMinus TokMinus TokLt TokLsr TokLsl TokLe TokLOr TokLAnd TokInstanceof TokHat TokGt TokGe TokEqEq TokEq TokComma TokAsr TokAmp
follow(member_def) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokRightBrace TokPublic TokProtected TokPrivate TokNative TokId TokFinal TokConst TokAbstract
follow(interface_def) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokFinal TokEof TokConst TokClass TokAbstract
follow(init_def_list) = TokSemi
follow(init_def) = TokSemi TokComma
follow(import_stmt) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokImport TokFinal TokEof TokConst TokClass TokAbstract
follow(id_brackets) = TokSemi TokRightParen TokLeftParen TokLeftBrace TokId TokEq TokComma
follow(fun_def) = TokWhile TokVolatile TokTry TokTrue TokTransient TokThrow TokSynchronized TokString TokStrictfp TokStatic TokSemi TokRightBrace TokReturn TokPublic TokProtected TokPrivate TokPlusPlus TokNil TokNew TokNative TokMinusMinus TokMinus TokLeftParen TokLeftBrace TokInt TokIf TokId TokFor TokFloat TokFinal TokFalse TokElse TokDo TokContinue TokConst TokChar TokBreak TokBang TokAbstract
follow(fun_decl) = TokSemi TokRightParen TokLeftParen TokLeftBrace TokEq TokDoubleBrack TokComma
follow(expr) = TokStar TokSlash TokSemi TokRightParen TokRightBrack TokPlusPlus TokPlus TokPipe TokPercent TokNotEq TokMinusMinus TokMinus TokLt TokLsr TokLsl TokLe TokLOr TokLAnd TokInstanceof TokHat TokGt TokGe TokEqEq TokEq TokComma TokAsr TokAmp
follow(direct_decl) = TokSemi TokRightParen TokLeftBrace TokEq TokComma
follow(const_def) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokRightBrace TokPublic TokProtected TokPrivate TokNative TokId TokFinal TokConst TokAbstract
follow(class_or_interface_defs) = TokEof
follow(class_or_interface_def_content) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokFinal TokEof TokConst TokClass TokAbstract
follow(class_or_interface_def) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokFinal TokEof TokConst TokClass TokAbstract
follow(class_def) = TokVolatile TokTransient TokSynchronized TokStrictfp TokStatic TokPublic TokProtected TokPrivate TokNative TokInterface TokFinal TokEof TokConst TokClass TokAbstract
follow(class_body) = TokRightBrace
follow(cast_expr) = TokStar TokSlash TokSemi TokRightParen TokRightBrack TokPlusPlus TokPlus TokPipe TokPercent TokNotEq TokMinusMinus TokMinus TokLt TokLsr TokLsl TokLeftParen TokLeftBrack TokLe TokLOr TokLAnd TokInstanceof TokHat TokGt TokGe TokEqEq TokEq TokDot TokComma TokAsr TokAmp
follow(brackets) = TokSemi TokRightParen TokLeftParen TokLeftBrace TokId TokEq TokDoubleBrack TokComma
follow(binop) = TokEq
follow(arg_list) = TokRightParen
Built an LR(0) automaton with 291 states.
The grammar is not SLR(1) -- 31 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 291 states.
537 shift/reduce conflicts were silently solved.
File "mcc-fj.mly", line 303, characters 0-5:
Warning: the precedence level assigned to TokCatch is never useful.
File "mcc-fj.mly", line 282, characters 0-5:
Warning: the precedence level assigned to TokComma is never useful.
File "mcc-fj.mly", line 303, characters 0-5:
Warning: the precedence level assigned to TokFinally is never useful.
File "mcc-fj.mly", line 299, characters 0-6:
Warning: the precedence level assigned to TokFor is never useful.
File "mcc-fj.mly", line 302, characters 0-9:
Warning: the precedence level assigned to TokTry is never useful.
File "mcc-fj.mly", line 299, characters 0-6:
Warning: the precedence level assigned to TokWhile is never useful.
File "mcc-fj.mly", line 301, characters 0-9:
Warning: the precedence level assigned to prec_ifthenelse is never useful.
File "mcc-fj.mly", line 296, characters 0-5:
Warning: the precedence level assigned to prec_subscript is never useful.
File "mcc-fj.mly", line 813, characters 58-72:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 817, characters 62-72:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 834, characters 54-64:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 675, characters 40-54:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 680, characters 70-80:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 747, characters 33-43:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 749, characters 35-45:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 1010, characters 64-74:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 903, characters 48-62:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 907, characters 61-75:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 1001, characters 113-121:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 943, characters 72-87:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 947, characters 98-104:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 955, characters 62-70:
Warning: this %prec declaration is never useful.
File "mcc-fj.mly", line 979, characters 84-90:
Warning: this %prec declaration is never useful.
109 out of 291 states have a default reduction.
77 out of 291 states are represented.
0 out of 142 symbols keep track of their start position.
0 out of 142 symbols keep track of their end position.
89 out of 173 productions exploit shiftreduce optimization.
0 out of 291 states can peek at an error.
817 functions before inlining, 131 functions after inlining.
