File "mcc-fc.mly", line 682, characters 6-12:
Warning: the token TokOp2 is unused.
Grammar has 97 nonterminal symbols, among which 1 start symbols.
Grammar has 75 terminal symbols.
Grammar has 297 productions.
nullable(var_defs) = false
nullable(union_enum) = false
nullable(uenum_spec_id) = false
nullable(uenum_spec) = false
nullable(uenum_declaration_list_cat) = true
nullable(uenum_declaration_list) = false
nullable(uenum_declaration) = false
nullable(uenum_decl_list) = false
nullable(type_qual) = false
nullable(type_params) = false
nullable(type_param_list) = false
nullable(type_mod) = false
nullable(type_direct_decl) = false
nullable(type_defs) = false
nullable(type_decl_list) = false
nullable(type_decl) = false
nullable(type_builtin) = false
nullable(tuple_spec_id) = false
nullable(tuple_spec) = false
nullable(tuple_declaration_list) = false
nullable(tuple_decl) = false
nullable(struct_type_spec) = false
nullable(struct_spec_id) = false
nullable(struct_spec) = false
nullable(struct_or_union) = false
nullable(struct_field_pattern) = false
nullable(struct_declaration_list_cat) = true
nullable(struct_declaration_list) = false
nullable(struct_declaration) = false
nullable(struct_decl_spec) = false
nullable(struct_decl_list) = false
nullable(struct_decl) = false
nullable(storage_class_spec) = false
nullable(stmt_list) = true
nullable(stmt) = false
nullable(simp_type_spec) = false
nullable(simp_decl_spec) = false
nullable(rev_uenum_decl_list) = false
nullable(rev_type_decl_list) = false
nullable(rev_tuple_decl_list) = false
nullable(rev_struct_field_pattern_list) = false
nullable(rev_struct_decl_list) = false
nullable(rev_stmt_list) = true
nullable(rev_patt_init_decl_list) = false
nullable(rev_param_list) = false
nullable(rev_init_list) = false
nullable(rev_id_init_decl_list) = false
nullable(rev_enum_decl_list) = false
nullable(rev_args) = false
nullable(rev_all_defs) = true
nullable(prog) = false
nullable(pattern) = false
nullable(patt_init_decl_list) = false
nullable(patt_init_decl) = false
nullable(patt_direct_decl) = false
nullable(patt_decl2) = false
nullable(patt_decl) = false
nullable(param_list) = false
nullable(param_decl) = false
nullable(opt_type_params) = true
nullable(opt_param_list) = true
nullable(opt_expr) = true
nullable(opt_comma) = true
nullable(operator) = false
nullable(open_block) = false
nullable(nc_expr) = false
nullable(init_field) = false
nullable(init) = false
nullable(id_init_decl_list) = false
nullable(id_init_decl) = false
nullable(id_decl) = false
nullable(id) = false
nullable(fun_param_list) = false
nullable(fun_def) = false
nullable(expr) = false
nullable(enum_spec_id) = false
nullable(enum_spec) = false
nullable(enum_declaration_list) = false
nullable(enum_decl) = false
nullable(direct_decl) = false
nullable(direct_abstract_decl) = false
nullable(decl_type_specifiers_opt) = true
nullable(decl_type_specifiers) = false
nullable(decl_type_specifier) = false
nullable(decl_struct_type_specifiers_opt) = true
nullable(decl_struct_type_specifiers) = false
nullable(decl_struct_type_specifier) = false
nullable(decl_specifiers_opt) = true
nullable(decl_specifiers) = false
nullable(decl_specifier) = false
nullable(decl_spec) = false
nullable(close_block) = false
nullable(cast_decl) = false
nullable(args) = true
nullable(all_defs) = true
nullable(all_def) = false
nullable(abstract_decl) = false
first(var_defs) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
first(union_enum) = TokUnion TokEnum
first(uenum_spec_id) = TokUnion TokEnum
first(uenum_spec) = TokUnion TokEnum
first(uenum_declaration_list_cat) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokId TokExtern TokEnum TokConst TokAuto
first(uenum_declaration_list) = TokLeftBrace
first(uenum_declaration) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokId TokExtern TokEnum TokConst TokAuto
first(uenum_decl_list) = TokStar TokLeftParen TokId TokAddr
first(type_qual) = TokVolatile TokConst
first(type_params) = TokTypeVar TokLeftParen
first(type_param_list) = TokTypeVar
first(type_mod) = TokUnsigned TokSigned TokShort TokLong
first(type_direct_decl) = TokPoly TokLeftParen TokId
first(type_defs) = TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
first(type_decl_list) = TokStar TokPoly TokLeftParen TokId TokAddr
first(type_decl) = TokStar TokPoly TokLeftParen TokId TokAddr
first(type_builtin) = TokTypeVoid TokTypeInt TokTypeFloat TokTypeDouble TokTypeChar
first(tuple_spec_id) = TokTuple
first(tuple_spec) = TokTuple
first(tuple_declaration_list) = TokLeftBrace
first(tuple_decl) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
first(struct_type_spec) = TokUnion TokTuple TokStruct TokEnum
first(struct_spec_id) = TokUnion TokStruct
first(struct_spec) = TokUnion TokStruct
first(struct_or_union) = TokUnion TokStruct
first(struct_field_pattern) = TokTypeId TokString TokLeftParen TokLeftBrace TokInt TokId TokFloat TokChar
first(struct_declaration_list_cat) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
first(struct_declaration_list) = TokLeftBrace
first(struct_declaration) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
first(struct_decl_spec) = TokVolatile TokUnion TokTuple TokStruct TokStatic TokRegister TokExtern TokEnum TokConst TokAuto
first(struct_decl_list) = TokStar TokLeftParen TokId TokColon TokAddr
first(struct_decl) = TokStar TokLeftParen TokId TokColon TokAddr
first(storage_class_spec) = TokStatic TokRegister TokExtern TokAuto
first(stmt_list) = TokWhile TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokTry TokSwitch TokStruct TokString TokStatic TokStar TokSizeof TokSigned TokShort TokSemi TokReturn TokRegister TokRaise TokPrePostOp12 TokPreOp12 TokPoly TokOperator TokOp10 TokLong TokLeftParen TokLeftBrace TokInt TokIf TokId TokGoto TokFor TokFloat TokExtern TokEnum TokDo TokDefault TokContinue TokConst TokChar TokCase TokBreak TokAuto TokAddr
first(stmt) = TokWhile TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokTry TokSwitch TokStruct TokString TokStatic TokStar TokSizeof TokSigned TokShort TokSemi TokReturn TokRegister TokRaise TokPrePostOp12 TokPreOp12 TokPoly TokOperator TokOp10 TokLong TokLeftParen TokLeftBrace TokInt TokIf TokId TokGoto TokFor TokFloat TokExtern TokEnum TokDo TokDefault TokContinue TokConst TokChar TokCase TokBreak TokAuto TokAddr
first(simp_type_spec) = TokTypeVar TokTypeId TokPoly
first(simp_decl_spec) = TokVolatile TokUnsigned TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokConst TokAuto
first(rev_uenum_decl_list) = TokStar TokLeftParen TokId TokAddr
first(rev_type_decl_list) = TokStar TokPoly TokLeftParen TokId TokAddr
first(rev_tuple_decl_list) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
first(rev_struct_field_pattern_list) = TokTypeId TokString TokLeftParen TokLeftBrace TokInt TokId TokFloat TokChar
first(rev_struct_decl_list) = TokStar TokLeftParen TokId TokColon TokAddr
first(rev_stmt_list) = TokWhile TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokTry TokSwitch TokStruct TokString TokStatic TokStar TokSizeof TokSigned TokShort TokSemi TokReturn TokRegister TokRaise TokPrePostOp12 TokPreOp12 TokPoly TokOperator TokOp10 TokLong TokLeftParen TokLeftBrace TokInt TokIf TokId TokGoto TokFor TokFloat TokExtern TokEnum TokDo TokDefault TokContinue TokConst TokChar TokCase TokBreak TokAuto TokAddr
first(rev_patt_init_decl_list) = TokString TokStar TokLeftParen TokLeftBrace TokInt TokId TokFloat TokChar TokAddr
first(rev_param_list) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokElide TokConst TokAuto
first(rev_init_list) = TokTypeId TokString TokStar TokSizeof TokPrePostOp12 TokPreOp12 TokOperator TokOp10 TokLeftParen TokLeftBrace TokInt TokId TokFloat TokChar TokAddr
first(rev_id_init_decl_list) = TokStar TokLeftParen TokId TokAddr
first(rev_enum_decl_list) = TokId
first(rev_args) = TokString TokStar TokSizeof TokPrePostOp12 TokPreOp12 TokOperator TokOp10 TokLeftParen TokInt TokId TokFloat TokChar TokAddr
first(rev_all_defs) = TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
first(prog) = TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEof TokEnum TokConst TokAuto
first(pattern) = TokString TokLeftParen TokLeftBrace TokInt TokId TokFloat TokChar
first(patt_init_decl_list) = TokString TokStar TokLeftParen TokLeftBrace TokInt TokId TokFloat TokChar TokAddr
first(patt_init_decl) = TokString TokStar TokLeftParen TokLeftBrace TokInt TokId TokFloat TokChar TokAddr
first(patt_direct_decl) = TokLeftParen TokId
first(patt_decl2) = TokStar TokLeftParen TokId TokAddr
first(patt_decl) = TokString TokStar TokLeftParen TokLeftBrace TokInt TokId TokFloat TokChar TokAddr
first(param_list) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokElide TokConst TokAuto
first(param_decl) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokElide TokConst TokAuto
first(opt_type_params) = TokTypeVar TokLeftParen
first(opt_param_list) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokElide TokConst TokAuto
first(opt_expr) = TokString TokStar TokSizeof TokPrePostOp12 TokPreOp12 TokOperator TokOp10 TokLeftParen TokInt TokId TokFloat TokChar TokAddr
first(opt_comma) = TokComma
first(operator) = TokStar TokPrePostOp12 TokPreOp12 TokOr TokOp9 TokOp8 TokOp7 TokOp5 TokOp4 TokOp13 TokOp11 TokOp10 TokOp1 TokEq TokComma TokAnd TokAddr
first(open_block) = TokLeftBrace
first(nc_expr) = TokString TokStar TokSizeof TokPrePostOp12 TokPreOp12 TokOperator TokOp10 TokLeftParen TokInt TokId TokFloat TokChar TokAddr
first(init_field) = TokTypeId TokString TokStar TokSizeof TokPrePostOp12 TokPreOp12 TokOperator TokOp10 TokLeftParen TokLeftBrace TokInt TokId TokFloat TokChar TokAddr
first(init) = TokString TokStar TokSizeof TokPrePostOp12 TokPreOp12 TokOperator TokOp10 TokLeftParen TokLeftBrace TokInt TokId TokFloat TokChar TokAddr
first(id_init_decl_list) = TokStar TokLeftParen TokId TokAddr
first(id_init_decl) = TokStar TokLeftParen TokId TokAddr
first(id_decl) = TokStar TokLeftParen TokId TokAddr
first(id) = TokTypeId TokId
first(fun_param_list) = TokLeftParen
first(fun_def) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
first(expr) = TokString TokStar TokSizeof TokPrePostOp12 TokPreOp12 TokOperator TokOp10 TokLeftParen TokInt TokId TokFloat TokChar TokAddr
first(enum_spec_id) = TokEnum
first(enum_spec) = TokEnum
first(enum_declaration_list) = TokLeftBrace
first(enum_decl) = TokId
first(direct_decl) = TokLeftParen TokId
first(direct_abstract_decl) = TokLeftParen TokLeftBrack
first(decl_type_specifiers_opt) = TokVolatile TokStatic TokRegister TokExtern TokConst TokAuto
first(decl_type_specifiers) = TokVolatile TokStatic TokRegister TokExtern TokConst TokAuto
first(decl_type_specifier) = TokVolatile TokStatic TokRegister TokExtern TokConst TokAuto
first(decl_struct_type_specifiers_opt) = TokVolatile TokConst
first(decl_struct_type_specifiers) = TokVolatile TokConst
first(decl_struct_type_specifier) = TokVolatile TokConst
first(decl_specifiers_opt) = TokVolatile TokUnsigned TokStatic TokSigned TokShort TokRegister TokLong TokExtern TokConst TokAuto
first(decl_specifiers) = TokVolatile TokUnsigned TokStatic TokSigned TokShort TokRegister TokLong TokExtern TokConst TokAuto
first(decl_specifier) = TokVolatile TokUnsigned TokStatic TokSigned TokShort TokRegister TokLong TokExtern TokConst TokAuto
first(decl_spec) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
first(close_block) = TokRightBrace
first(cast_decl) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
first(args) = TokString TokStar TokSizeof TokPrePostOp12 TokPreOp12 TokOperator TokOp10 TokLeftParen TokInt TokId TokFloat TokChar TokAddr
first(all_defs) = TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
first(all_def) = TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
first(abstract_decl) = TokStar TokLeftParen TokLeftBrack TokAddr
minimal(var_defs) = (* 3 *) TokShort TokChar TokSemi
minimal(union_enum) = (* 2 *) TokEnum TokUnion
minimal(uenum_spec_id) = (* 3 *) TokEnum TokUnion TokId
minimal(uenum_spec) = (* 3 *) TokEnum TokUnion TokId
minimal(uenum_declaration_list_cat) = (* 0 *) 
minimal(uenum_declaration_list) = (* 2 *) TokLeftBrace TokRightBrace
minimal(uenum_declaration) = (* 2 *) TokId TokSemi
minimal(uenum_decl_list) = (* 1 *) TokId
minimal(type_qual) = (* 1 *) TokConst
minimal(type_params) = (* 1 *) TokTypeVar
minimal(type_param_list) = (* 1 *) TokTypeVar
minimal(type_mod) = (* 1 *) TokShort
minimal(type_direct_decl) = (* 1 *) TokId
minimal(type_defs) = (* 2 *) TokShort TokSemi
minimal(type_decl_list) = (* 1 *) TokId
minimal(type_decl) = (* 1 *) TokId
minimal(type_builtin) = (* 1 *) TokTypeVoid
minimal(tuple_spec_id) = (* 2 *) TokTuple TokId
minimal(tuple_spec) = (* 2 *) TokTuple TokId
minimal(tuple_declaration_list) = (* 4 *) TokLeftBrace TokShort TokSemi TokRightBrace
minimal(tuple_decl) = (* 2 *) TokShort TokSemi
minimal(struct_type_spec) = (* 2 *) TokStruct TokId
minimal(struct_spec_id) = (* 2 *) TokStruct TokId
minimal(struct_spec) = (* 2 *) TokStruct TokId
minimal(struct_or_union) = (* 1 *) TokStruct
minimal(struct_field_pattern) = (* 1 *) TokChar
minimal(struct_declaration_list_cat) = (* 0 *) 
minimal(struct_declaration_list) = (* 2 *) TokLeftBrace TokRightBrace
minimal(struct_declaration) = (* 3 *) TokShort TokId TokSemi
minimal(struct_decl_spec) = (* 2 *) TokStruct TokId
minimal(struct_decl_list) = (* 1 *) TokId
minimal(struct_decl) = (* 1 *) TokId
minimal(storage_class_spec) = (* 1 *) TokAuto
minimal(stmt_list) = (* 0 *) 
minimal(stmt) = (* 1 *) TokSemi
minimal(simp_type_spec) = (* 1 *) TokTypeVar
minimal(simp_decl_spec) = (* 1 *) TokShort
minimal(rev_uenum_decl_list) = (* 1 *) TokId
minimal(rev_type_decl_list) = (* 1 *) TokId
minimal(rev_tuple_decl_list) = (* 2 *) TokShort TokSemi
minimal(rev_struct_field_pattern_list) = (* 1 *) TokChar
minimal(rev_struct_decl_list) = (* 1 *) TokId
minimal(rev_stmt_list) = (* 0 *) 
minimal(rev_patt_init_decl_list) = (* 1 *) TokChar
minimal(rev_param_list) = (* 1 *) TokShort
minimal(rev_init_list) = (* 1 *) TokChar
minimal(rev_id_init_decl_list) = (* 1 *) TokId
minimal(rev_enum_decl_list) = (* 1 *) TokId
minimal(rev_args) = (* 1 *) TokChar
minimal(rev_all_defs) = (* 0 *) 
minimal(prog) = (* 1 *) TokEof
minimal(pattern) = (* 1 *) TokChar
minimal(patt_init_decl_list) = (* 1 *) TokChar
minimal(patt_init_decl) = (* 1 *) TokChar
minimal(patt_direct_decl) = (* 3 *) TokId TokLeftBrack TokRightBrack
minimal(patt_decl2) = (* 2 *) TokStar TokId
minimal(patt_decl) = (* 1 *) TokChar
minimal(param_list) = (* 1 *) TokShort
minimal(param_decl) = (* 1 *) TokShort
minimal(opt_type_params) = (* 0 *) 
minimal(opt_param_list) = (* 0 *) 
minimal(opt_expr) = (* 0 *) 
minimal(opt_comma) = (* 0 *) 
minimal(operator) = (* 1 *) TokComma
minimal(open_block) = (* 1 *) TokLeftBrace
minimal(nc_expr) = (* 1 *) TokChar
minimal(init_field) = (* 1 *) TokChar
minimal(init) = (* 1 *) TokChar
minimal(id_init_decl_list) = (* 1 *) TokId
minimal(id_init_decl) = (* 1 *) TokId
minimal(id_decl) = (* 1 *) TokId
minimal(id) = (* 1 *) TokId
minimal(fun_param_list) = (* 2 *) TokLeftParen TokRightParen
minimal(fun_def) = (* 5 *) TokStruct TokId TokId TokLeftBrace TokRightBrace
minimal(expr) = (* 1 *) TokChar
minimal(enum_spec_id) = (* 2 *) TokEnum TokId
minimal(enum_spec) = (* 2 *) TokEnum TokId
minimal(enum_declaration_list) = (* 2 *) TokLeftBrace TokRightBrace
minimal(enum_decl) = (* 1 *) TokId
minimal(direct_decl) = (* 1 *) TokId
minimal(direct_abstract_decl) = (* 2 *) TokLeftBrack TokRightBrack
minimal(decl_type_specifiers_opt) = (* 0 *) 
minimal(decl_type_specifiers) = (* 1 *) TokAuto
minimal(decl_type_specifier) = (* 1 *) TokAuto
minimal(decl_struct_type_specifiers_opt) = (* 0 *) 
minimal(decl_struct_type_specifiers) = (* 1 *) TokConst
minimal(decl_struct_type_specifier) = (* 1 *) TokConst
minimal(decl_specifiers_opt) = (* 0 *) 
minimal(decl_specifiers) = (* 1 *) TokShort
minimal(decl_specifier) = (* 1 *) TokAuto
minimal(decl_spec) = (* 1 *) TokShort
minimal(close_block) = (* 1 *) TokRightBrace
minimal(cast_decl) = (* 1 *) TokShort
minimal(args) = (* 0 *) 
minimal(all_defs) = (* 0 *) 
minimal(all_def) = (* 2 *) TokShort TokSemi
minimal(abstract_decl) = (* 1 *) TokStar
follow(var_defs) = TokWhile TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokTry TokSwitch TokStruct TokString TokStatic TokStar TokSizeof TokSigned TokShort TokSemi TokRightParen TokRightBrace TokReturn TokRegister TokRaise TokPrePostOp12 TokPreOp12 TokPoly TokOperator TokOp10 TokLong TokLeftParen TokLeftBrace TokInt TokIf TokId TokGoto TokFor TokFloat TokFinally TokExtern TokEof TokEnum TokElse TokDo TokDefault TokContinue TokConst TokChar TokCatch TokCase TokBreak TokAuto TokAddr
follow(union_enum) = TokTypeVar TokTypeId TokLeftParen TokLeftBrace TokId
follow(uenum_spec_id) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokLeftBrace TokId TokExtern TokConst TokComma TokColon TokAuto TokAddr
follow(uenum_spec) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokId TokExtern TokConst TokComma TokColon TokAuto TokAddr
follow(uenum_declaration_list_cat) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRightBrace TokRegister TokPoly TokLong TokId TokExtern TokEnum TokConst TokAuto
follow(uenum_declaration_list) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokId TokExtern TokConst TokComma TokColon TokAuto TokAddr
follow(uenum_declaration) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRightBrace TokRegister TokPoly TokLong TokId TokExtern TokEnum TokConst TokAuto
follow(uenum_decl_list) = TokSemi
follow(type_qual) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokString TokStatic TokStar TokSigned TokShort TokSemi TokRightParen TokRegister TokPoly TokLong TokLeftParen TokLeftBrack TokLeftBrace TokInt TokId TokFloat TokExtern TokEnum TokConst TokComma TokColon TokChar TokAuto TokAddr
follow(type_params) = TokTypeId TokLeftBrace TokId
follow(type_param_list) = TokRightParen TokComma
follow(type_mod) = TokVolatile TokUnsigned TokTypeVoid TokTypeInt TokTypeFloat TokTypeDouble TokTypeChar TokString TokStatic TokStar TokSigned TokShort TokSemi TokRightParen TokRegister TokPoly TokLong TokLeftParen TokLeftBrack TokLeftBrace TokInt TokId TokFloat TokExtern TokConst TokComma TokColon TokChar TokAuto TokAddr
follow(type_direct_decl) = TokSemi TokRightParen TokLeftParen TokLeftBrack TokComma
follow(type_defs) = TokWhile TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokTry TokSwitch TokStruct TokString TokStatic TokStar TokSizeof TokSigned TokShort TokSemi TokRightParen TokRightBrace TokReturn TokRegister TokRaise TokPrePostOp12 TokPreOp12 TokPoly TokOperator TokOp10 TokLong TokLeftParen TokLeftBrace TokInt TokIf TokId TokGoto TokFor TokFloat TokFinally TokExtern TokEof TokEnum TokElse TokDo TokDefault TokContinue TokConst TokChar TokCatch TokCase TokBreak TokAuto TokAddr
follow(type_decl_list) = TokSemi
follow(type_decl) = TokSemi TokRightParen TokComma
follow(type_builtin) = TokVolatile TokUnsigned TokString TokStatic TokStar TokSigned TokShort TokSemi TokRightParen TokRegister TokPoly TokLong TokLeftParen TokLeftBrack TokLeftBrace TokInt TokId TokFloat TokExtern TokConst TokComma TokColon TokChar TokAuto TokAddr
follow(tuple_spec_id) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokLeftBrace TokId TokExtern TokConst TokComma TokColon TokAuto TokAddr
follow(tuple_spec) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokId TokExtern TokConst TokComma TokColon TokAuto TokAddr
follow(tuple_declaration_list) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokId TokExtern TokConst TokComma TokColon TokAuto TokAddr
follow(tuple_decl) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRightBrace TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
follow(struct_type_spec) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokId TokExtern TokConst TokComma TokColon TokAuto TokAddr
follow(struct_spec_id) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokLeftBrace TokId TokExtern TokConst TokComma TokColon TokAuto TokAddr
follow(struct_spec) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokId TokExtern TokConst TokComma TokColon TokAuto TokAddr
follow(struct_or_union) = TokTypeVar TokTypeId TokLeftParen TokLeftBrace TokId
follow(struct_field_pattern) = TokRightBrace TokComma
follow(struct_declaration_list_cat) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRightBrace TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
follow(struct_declaration_list) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokId TokExtern TokConst TokComma TokColon TokAuto TokAddr
follow(struct_declaration) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRightBrace TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
follow(struct_decl_spec) = TokStar TokSemi TokRightParen TokPoly TokLeftParen TokLeftBrack TokId TokComma TokColon TokAddr
follow(struct_decl_list) = TokSemi
follow(struct_decl) = TokSemi TokComma
follow(storage_class_spec) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokString TokStatic TokStar TokSigned TokShort TokSemi TokRightParen TokRegister TokPoly TokLong TokLeftParen TokLeftBrack TokLeftBrace TokInt TokId TokFloat TokExtern TokEnum TokConst TokComma TokColon TokChar TokAuto TokAddr
follow(stmt_list) = TokRightBrace
follow(stmt) = TokWhile TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokTry TokSwitch TokStruct TokString TokStatic TokStar TokSizeof TokSigned TokShort TokSemi TokRightParen TokRightBrace TokReturn TokRegister TokRaise TokPrePostOp12 TokPreOp12 TokPoly TokOperator TokOp10 TokLong TokLeftParen TokLeftBrace TokInt TokIf TokId TokGoto TokFor TokFloat TokFinally TokExtern TokEnum TokElse TokDo TokDefault TokContinue TokConst TokChar TokCatch TokCase TokBreak TokAuto TokAddr
follow(simp_type_spec) = TokVolatile TokString TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokLeftBrace TokInt TokId TokFloat TokExtern TokConst TokComma TokColon TokChar TokAuto TokAddr
follow(simp_decl_spec) = TokString TokStar TokSemi TokRightParen TokPoly TokLeftParen TokLeftBrack TokLeftBrace TokInt TokId TokFloat TokComma TokColon TokChar TokAddr
follow(rev_uenum_decl_list) = TokSemi TokComma
follow(rev_type_decl_list) = TokSemi TokComma
follow(rev_tuple_decl_list) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRightBrace TokRegister TokPoly TokLong TokExtern TokEnum TokConst TokAuto
follow(rev_struct_field_pattern_list) = TokRightBrace TokComma
follow(rev_struct_decl_list) = TokSemi TokComma
follow(rev_stmt_list) = TokWhile TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokTry TokSwitch TokStruct TokString TokStatic TokStar TokSizeof TokSigned TokShort TokSemi TokRightBrace TokReturn TokRegister TokRaise TokPrePostOp12 TokPreOp12 TokPoly TokOperator TokOp10 TokLong TokLeftParen TokLeftBrace TokInt TokIf TokId TokGoto TokFor TokFloat TokExtern TokEnum TokDo TokDefault TokContinue TokConst TokChar TokCase TokBreak TokAuto TokAddr
follow(rev_patt_init_decl_list) = TokSemi TokComma
follow(rev_param_list) = TokRightParen TokComma
follow(rev_init_list) = TokRightBrace TokComma
follow(rev_id_init_decl_list) = TokSemi TokComma
follow(rev_enum_decl_list) = TokRightBrace TokComma
follow(rev_args) = TokRightParen TokComma
follow(rev_all_defs) = TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokStatic TokSigned TokShort TokRegister TokPoly TokLong TokExtern TokEof TokEnum TokConst TokAuto
follow(prog) = #
follow(pattern) = TokSemi TokRightParen TokRightBrace TokEq TokComma TokColon
follow(patt_init_decl_list) = TokSemi
follow(patt_init_decl) = TokSemi TokComma
follow(patt_direct_decl) = TokSemi TokRightParen TokLeftParen TokLeftBrack TokEq TokComma
follow(patt_decl2) = TokSemi TokRightParen TokEq TokComma
follow(patt_decl) = TokSemi TokRightParen TokEq TokComma
follow(param_list) = TokRightParen
follow(param_decl) = TokRightParen TokComma
follow(opt_type_params) = TokTypeId TokLeftBrace TokId
follow(opt_param_list) = TokRightParen
follow(opt_expr) = TokSemi TokRightParen TokRightBrack
follow(opt_comma) = TokRightBrace
follow(operator) = TokStar TokSemi TokRightParen TokRightBrack TokRightBrace TokQuest TokPrePostOp12 TokOr TokOp9 TokOp8 TokOp7 TokOp5 TokOp4 TokOp13 TokOp11 TokOp10 TokOp1 TokLeftParen TokLeftBrack TokEq TokDot TokComma TokColon TokAnd TokAddr
follow(open_block) = TokWhile TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokTry TokSwitch TokStruct TokString TokStatic TokStar TokSizeof TokSigned TokShort TokSemi TokRightBrace TokReturn TokRegister TokRaise TokPrePostOp12 TokPreOp12 TokPoly TokOperator TokOp10 TokLong TokLeftParen TokLeftBrace TokInt TokIf TokId TokGoto TokFor TokFloat TokExtern TokEnum TokDo TokDefault TokContinue TokConst TokChar TokCase TokBreak TokAuto TokAddr
follow(nc_expr) = TokStar TokSemi TokRightParen TokRightBrack TokRightBrace TokQuest TokPrePostOp12 TokOr TokOp9 TokOp8 TokOp7 TokOp5 TokOp4 TokOp13 TokOp11 TokOp10 TokOp1 TokLeftParen TokLeftBrack TokEq TokDot TokComma TokColon TokAnd TokAddr
follow(init_field) = TokRightBrace TokComma
follow(init) = TokSemi TokRightBrace TokComma
follow(id_init_decl_list) = TokSemi
follow(id_init_decl) = TokSemi TokComma
follow(id_decl) = TokSemi TokRightParen TokLeftBrace TokEq TokComma TokColon
follow(id) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRightBrack TokRightBrace TokRegister TokQuest TokPrePostOp12 TokPoly TokOr TokOp9 TokOp8 TokOp7 TokOp5 TokOp4 TokOp13 TokOp11 TokOp10 TokOp1 TokLeftParen TokLeftBrack TokLeftBrace TokId TokExtern TokEq TokDot TokConst TokComma TokColon TokAuto TokAnd TokAddr
follow(fun_param_list) = TokRightParen TokLeftParen TokLeftBrack TokComma
follow(fun_def) = TokWhile TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokTry TokSwitch TokStruct TokString TokStatic TokStar TokSizeof TokSigned TokShort TokSemi TokRightParen TokRightBrace TokReturn TokRegister TokRaise TokPrePostOp12 TokPreOp12 TokPoly TokOperator TokOp10 TokLong TokLeftParen TokLeftBrace TokInt TokIf TokId TokGoto TokFor TokFloat TokFinally TokExtern TokEof TokEnum TokElse TokDo TokDefault TokContinue TokConst TokChar TokCatch TokCase TokBreak TokAuto TokAddr
follow(expr) = TokSemi TokRightParen TokRightBrack TokComma
follow(enum_spec_id) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokLeftBrace TokId TokExtern TokConst TokComma TokColon TokAuto TokAddr
follow(enum_spec) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokId TokExtern TokConst TokComma TokColon TokAuto TokAddr
follow(enum_declaration_list) = TokVolatile TokStatic TokStar TokSemi TokRightParen TokRegister TokPoly TokLeftParen TokLeftBrack TokId TokExtern TokConst TokComma TokColon TokAuto TokAddr
follow(enum_decl) = TokRightBrace TokComma
follow(direct_decl) = TokSemi TokRightParen TokLeftParen TokLeftBrack TokLeftBrace TokEq TokComma TokColon
follow(direct_abstract_decl) = TokRightParen TokLeftParen TokLeftBrack TokComma
follow(decl_type_specifiers_opt) = TokString TokStar TokSemi TokRightParen TokPoly TokLeftParen TokLeftBrack TokLeftBrace TokInt TokId TokFloat TokComma TokColon TokChar TokAddr
follow(decl_type_specifiers) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokString TokStatic TokStar TokSigned TokShort TokSemi TokRightParen TokRegister TokPoly TokLong TokLeftParen TokLeftBrack TokLeftBrace TokInt TokId TokFloat TokExtern TokEnum TokConst TokComma TokColon TokChar TokAuto TokAddr
follow(decl_type_specifier) = TokVolatile TokUnsigned TokUnion TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokStruct TokString TokStatic TokStar TokSigned TokShort TokSemi TokRightParen TokRegister TokPoly TokLong TokLeftParen TokLeftBrack TokLeftBrace TokInt TokId TokFloat TokExtern TokEnum TokConst TokComma TokColon TokChar TokAuto TokAddr
follow(decl_struct_type_specifiers_opt) = TokStar TokRightParen TokPoly TokLeftParen TokLeftBrack TokId TokComma TokAddr
follow(decl_struct_type_specifiers) = TokVolatile TokStar TokRightParen TokPoly TokLeftParen TokLeftBrack TokId TokConst TokComma TokAddr
follow(decl_struct_type_specifier) = TokVolatile TokStar TokRightParen TokPoly TokLeftParen TokLeftBrack TokId TokConst TokComma TokAddr
follow(decl_specifiers_opt) = TokTypeVoid TokTypeInt TokTypeFloat TokTypeDouble TokTypeChar TokString TokStar TokSemi TokRightParen TokPoly TokLeftParen TokLeftBrack TokLeftBrace TokInt TokId TokFloat TokComma TokColon TokChar TokAddr
follow(decl_specifiers) = TokVolatile TokUnsigned TokTypeVoid TokTypeInt TokTypeFloat TokTypeDouble TokTypeChar TokString TokStatic TokStar TokSigned TokShort TokSemi TokRightParen TokRegister TokPoly TokLong TokLeftParen TokLeftBrack TokLeftBrace TokInt TokId TokFloat TokExtern TokConst TokComma TokColon TokChar TokAuto TokAddr
follow(decl_specifier) = TokVolatile TokUnsigned TokTypeVoid TokTypeInt TokTypeFloat TokTypeDouble TokTypeChar TokString TokStatic TokStar TokSigned TokShort TokSemi TokRightParen TokRegister TokPoly TokLong TokLeftParen TokLeftBrack TokLeftBrace TokInt TokId TokFloat TokExtern TokConst TokComma TokColon TokChar TokAuto TokAddr
follow(decl_spec) = TokStar TokRightParen TokPoly TokLeftParen TokId TokAddr
follow(close_block) = TokWhile TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokTry TokSwitch TokStruct TokString TokStatic TokStar TokSizeof TokSigned TokShort TokSemi TokRightParen TokRightBrace TokReturn TokRegister TokRaise TokPrePostOp12 TokPreOp12 TokPoly TokOperator TokOp10 TokLong TokLeftParen TokLeftBrace TokInt TokIf TokId TokGoto TokFor TokFloat TokFinally TokExtern TokEnum TokElse TokDo TokDefault TokContinue TokConst TokChar TokCatch TokCase TokBreak TokAuto TokAddr
follow(cast_decl) = TokRightParen
follow(args) = TokRightParen
follow(all_defs) = TokEof
follow(all_def) = TokWhile TokVolatile TokUnsigned TokUnion TokTypedef TokTypeVoid TokTypeVar TokTypeInt TokTypeId TokTypeFloat TokTypeDouble TokTypeChar TokTuple TokTry TokSwitch TokStruct TokString TokStatic TokStar TokSizeof TokSigned TokShort TokSemi TokRightParen TokRightBrace TokReturn TokRegister TokRaise TokPrePostOp12 TokPreOp12 TokPoly TokOperator TokOp10 TokLong TokLeftParen TokLeftBrace TokInt TokIf TokId TokGoto TokFor TokFloat TokFinally TokExtern TokEof TokEnum TokElse TokDo TokDefault TokContinue TokConst TokChar TokCatch TokCase TokBreak TokAuto TokAddr
follow(abstract_decl) = TokRightParen TokComma
Built an LR(0) automaton with 519 states.
The grammar is not SLR(1) -- 68 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 519 states.
421 shift/reduce conflicts were silently solved.
File "mcc-fc.mly", line 679, characters 0-5:
Warning: the precedence level assigned to TokComma is never useful.
File "mcc-fc.mly", line 682, characters 0-5:
Warning: the precedence level assigned to TokOp2 is never useful.
File "mcc-fc.mly", line 692, characters 0-6:
Warning: the precedence level assigned to TokPreOp12 is never useful.
File "mcc-fc.mly", line 693, characters 0-5:
Warning: the precedence level assigned to TokRightBrack is never useful.
File "mcc-fc.mly", line 693, characters 0-5:
Warning: the precedence level assigned to prec_apply is never useful.
File "mcc-fc.mly", line 693, characters 0-5:
Warning: the precedence level assigned to prec_subscript is never useful.
File "mcc-fc.mly", line 1588, characters 73-87:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1594, characters 52-66:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1600, characters 52-62:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1605, characters 31-41:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1496, characters 64-78:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1502, characters 70-80:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1791, characters 39-49:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1847, characters 59-73:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1851, characters 56-66:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1447, characters 69-83:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1453, characters 75-85:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1457, characters 58-72:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1465, characters 64-74:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1395, characters 69-83:
Warning: this %prec declaration is never useful.
File "mcc-fc.mly", line 1401, characters 75-85:
Warning: this %prec declaration is never useful.
219 out of 519 states have a default reduction.
169 out of 519 states are represented.
0 out of 175 symbols keep track of their start position.
0 out of 175 symbols keep track of their end position.
171 out of 298 productions exploit shiftreduce optimization.
0 out of 519 states can peek at an error.
1439 functions before inlining, 225 functions after inlining.
