File "mcc-naml.mly", line 156, characters 22-31:
Warning: the token TokAssert is unused.
File "mcc-naml.mly", line 223, characters 10-23:
Warning: the token prec_expr_l11 is unused.
File "mcc-naml.mly", line 221, characters 10-23:
Warning: the token prec_expr_l13 is unused.
File "mcc-naml.mly", line 220, characters 10-23:
Warning: the token prec_expr_l14 is unused.
File "mcc-naml.mly", line 232, characters 10-22:
Warning: the token prec_expr_l3 is unused.
File "mcc-naml.mly", line 227, characters 10-22:
Warning: the token prec_expr_l7 is unused.
File "mcc-naml.mly", line 226, characters 10-22:
Warning: the token prec_expr_l8 is unused.
File "mcc-naml.mly", line 234, characters 12-24:
Warning: the token prec_expr_n1 is unused.
File "mcc-naml.mly", line 222, characters 12-25:
Warning: the token prec_expr_n12 is unused.
File "mcc-naml.mly", line 219, characters 11-24:
Warning: the token prec_expr_n15 is unused.
File "mcc-naml.mly", line 233, characters 12-24:
Warning: the token prec_expr_n2 is unused.
File "mcc-naml.mly", line 231, characters 12-24:
Warning: the token prec_expr_n4 is unused.
File "mcc-naml.mly", line 224, characters 11-24:
Warning: the token prec_expr_r10 is unused.
File "mcc-naml.mly", line 212, characters 11-24:
Warning: the token prec_expr_r18 is unused.
File "mcc-naml.mly", line 229, characters 11-23:
Warning: the token prec_expr_r6 is unused.
File "mcc-naml.mly", line 225, characters 11-23:
Warning: the token prec_expr_r9 is unused.
File "mcc-naml.mly", line 231, characters 39-51:
Warning: the token prec_ty_cons is unused.
File "mcc-naml.mly", line 217, characters 11-22:
Warning: the token prec_ty_fun is unused.
File "mcc-naml.mly", line 228, characters 12-25:
Warning: the token prec_ty_tuple is unused.
Grammar has 60 nonterminal symbols, among which 3 start symbols.
Grammar has 78 terminal symbols.
Grammar has 227 productions.
nullable(when_opt) = true
nullable(vpath_cap) = false
nullable(vpath) = false
nullable(type_tuple_aux) = false
nullable(type_tuple) = false
nullable(type_params) = true
nullable(type_param_list) = false
nullable(type_info) = true
nullable(type_expr_list) = false
nullable(type_expr_limited) = false
nullable(type_expr) = false
nullable(type_definition) = false
nullable(type_def_list) = false
nullable(type_def) = false
nullable(topstmt) = false
nullable(spec_list) = true
nullable(spec) = false
nullable(pure_vpath) = false
nullable(prog) = false
nullable(pattern_tuple) = false
nullable(pattern_record) = false
nullable(pattern_no_tuple) = false
nullable(pattern_match_list) = false
nullable(pattern_match) = false
nullable(pattern_list) = false
nullable(pattern_limited) = false
nullable(pattern) = false
nullable(param_list) = false
nullable(operator) = false
nullable(mutable_opt) = true
nullable(mpath) = false
nullable(module_type_constraints) = false
nullable(module_type) = false
nullable(module_expr) = false
nullable(module_contrain_opt) = true
nullable(module_args) = true
nullable(let_rec_opt) = true
nullable(let_binding_list) = false
nullable(let_binding) = false
nullable(interface) = false
nullable(ident) = false
nullable(field_decl_list_aux) = false
nullable(field_decl_list) = false
nullable(ext_mpath) = false
nullable(expr_simp) = false
nullable(expr_record_aux) = false
nullable(expr_record) = false
nullable(expr_fun) = false
nullable(expr_arg) = false
nullable(expr) = false
nullable(exception_def_simp) = false
nullable(exception_def) = false
nullable(def_list) = true
nullable(def) = false
nullable(constr_decl_list) = false
nullable(constr_decl) = false
nullable(constr_cap_ident) = false
nullable(const_expr_not_cons) = false
nullable(const_expr) = false
nullable(cap_ident) = false
first(when_opt) = TokWhen
first(vpath_cap) = TokLParen TokLList TokCapId
first(vpath) = TokLParen TokId TokCapId
first(type_tuple_aux) = TokMeta TokLParen TokId TokCapId TokAny
first(type_tuple) = TokMeta TokLParen TokId TokCapId TokAny
first(type_params) = TokMeta TokLParen
first(type_param_list) = TokMeta
first(type_info) = TokEq
first(type_expr_list) = TokMeta TokLParen TokId TokCapId TokAny
first(type_expr_limited) = TokMeta TokLParen TokId TokCapId TokAny
first(type_expr) = TokMeta TokLParen TokId TokCapId TokAny
first(type_definition) = TokType
first(type_def_list) = TokMeta TokLParen TokId
first(type_def) = TokMeta TokLParen TokId
first(topstmt) = TokType TokOpen TokModule TokLet TokInclude TokExternal TokException TokEOF
first(spec_list) = TokVal TokType TokSemiSemi TokOpen TokModule TokInclude TokExternal TokException
first(spec) = TokVal TokType TokOpen TokModule TokInclude TokExternal TokException
first(pure_vpath) = TokId TokCapId
first(prog) = TokType TokOpen TokModule TokLet TokInclude TokExternal TokException TokEOF
first(pattern_tuple) = TokString TokLRecord TokLParen TokLList TokInt TokId TokFloat TokChar TokCapId TokAny
first(pattern_record) = TokLParen TokId TokCapId
first(pattern_no_tuple) = TokString TokLRecord TokLParen TokLList TokInt TokId TokFloat TokChar TokCapId TokAny
first(pattern_match_list) = TokString TokLRecord TokLParen TokLList TokInt TokId TokFloat TokChar TokCapId TokAny
first(pattern_match) = TokString TokLRecord TokLParen TokLList TokInt TokId TokFloat TokChar TokCapId TokAny
first(pattern_list) = TokString TokLRecord TokLParen TokLList TokInt TokId TokFloat TokChar TokCapId TokAny
first(pattern_limited) = TokString TokLRecord TokLParen TokLList TokInt TokId TokFloat TokChar TokCapId TokAny
first(pattern) = TokString TokLRecord TokLParen TokLList TokInt TokId TokFloat TokChar TokCapId TokAny
first(param_list) = TokString TokLRecord TokLParen TokLList TokInt TokId TokFloat TokChar TokCapId TokAny
first(operator) = TokStar TokOpPreN1 TokOpMinusDot TokOpMinus TokOpInR6 TokOpInR16 TokOpInR10 TokOpInN12 TokOpInL8 TokOpInL7 TokOpInL14 TokOpInL13 TokOpInL11 TokEq
first(mutable_opt) = TokMutable
first(mpath) = TokCapId
first(module_type_constraints) = TokSig TokLParen TokFunctor TokCapId
first(module_type) = TokSig TokLParen TokFunctor TokCapId
first(module_expr) = TokStruct TokLParen TokFunctor TokCapId
first(module_contrain_opt) = TokIs
first(module_args) = TokLParen
first(let_rec_opt) = TokRec
first(let_binding_list) = TokString TokLRecord TokLParen TokLList TokInt TokId TokFloat TokChar TokCapId TokAny
first(let_binding) = TokString TokLRecord TokLParen TokLList TokInt TokId TokFloat TokChar TokCapId TokAny
first(interface) = TokVal TokType TokSemiSemi TokOpen TokModule TokInclude TokExternal TokException TokEOF
first(ident) = TokLParen TokId
first(field_decl_list_aux) = TokMutable TokId
first(field_decl_list) = TokMutable TokId
first(ext_mpath) = TokCapId
first(expr_simp) = TokWhile TokString TokOpPreN1 TokLRecord TokLParen TokLList TokLArray TokInt TokId TokFor TokFloat TokChar TokCapId TokBegin
first(expr_record_aux) = TokLParen TokId TokCapId
first(expr_record) = TokLParen TokId TokCapId
first(expr_fun) = TokWhile TokString TokOpPreN1 TokLRecord TokLParen TokLList TokLArray TokInt TokId TokFor TokFloat TokChar TokCapId TokBegin
first(expr_arg) = TokWhile TokString TokOpPreN1 TokLRecord TokLParen TokLList TokLArray TokInt TokId TokFor TokFloat TokChar TokCapId TokBegin
first(expr) = TokWhile TokTry TokString TokOpPreN1 TokOpMinusDot TokOpMinus TokMatch TokLet TokLRecord TokLParen TokLList TokLArray TokInt TokIf TokId TokFunction TokFun TokFor TokFloat TokChar TokCapId TokBegin
first(exception_def_simp) = TokException
first(exception_def) = TokException
first(def_list) = TokType TokOpen TokModule TokLet TokInclude TokExternal TokException
first(def) = TokType TokOpen TokModule TokLet TokInclude TokExternal TokException
first(constr_decl_list) = TokLParen TokLList TokCons TokCapId
first(constr_decl) = TokLParen TokLList TokCons TokCapId
first(constr_cap_ident) = TokLParen TokLList TokCons TokCapId
first(const_expr_not_cons) = TokInt TokFloat TokChar
first(const_expr) = TokLParen TokLList TokInt TokFloat TokChar TokCapId
first(cap_ident) = TokLParen TokLList TokCapId
minimal(when_opt) = (* 0 *) 
minimal(vpath_cap) = (* 1 *) TokCapId
minimal(vpath) = (* 1 *) TokId
minimal(type_tuple_aux) = (* 1 *) TokAny
minimal(type_tuple) = (* 1 *) TokAny
minimal(type_params) = (* 0 *) 
minimal(type_param_list) = (* 2 *) TokMeta TokId
minimal(type_info) = (* 0 *) 
minimal(type_expr_list) = (* 1 *) TokAny
minimal(type_expr_limited) = (* 1 *) TokAny
minimal(type_expr) = (* 1 *) TokAny
minimal(type_definition) = (* 2 *) TokType TokId
minimal(type_def_list) = (* 1 *) TokId
minimal(type_def) = (* 1 *) TokId
minimal(topstmt) = (* 1 *) TokEOF
minimal(spec_list) = (* 0 *) 
minimal(spec) = (* 2 *) TokType TokId
minimal(pure_vpath) = (* 1 *) TokId
minimal(prog) = (* 1 *) TokEOF
minimal(pattern_tuple) = (* 1 *) TokId
minimal(pattern_record) = (* 3 *) TokId TokEq TokId
minimal(pattern_no_tuple) = (* 1 *) TokId
minimal(pattern_match_list) = (* 3 *) TokId TokRArrow TokInt
minimal(pattern_match) = (* 3 *) TokId TokRArrow TokInt
minimal(pattern_list) = (* 1 *) TokId
minimal(pattern_limited) = (* 1 *) TokId
minimal(pattern) = (* 1 *) TokId
minimal(param_list) = (* 1 *) TokId
minimal(operator) = (* 1 *) TokOpPreN1
minimal(mutable_opt) = (* 0 *) 
minimal(mpath) = (* 1 *) TokCapId
minimal(module_type_constraints) = (* 5 *) TokCapId TokWith TokCapId TokEq TokCapId
minimal(module_type) = (* 1 *) TokCapId
minimal(module_expr) = (* 1 *) TokCapId
minimal(module_contrain_opt) = (* 0 *) 
minimal(module_args) = (* 0 *) 
minimal(let_rec_opt) = (* 0 *) 
minimal(let_binding_list) = (* 3 *) TokId TokEq TokInt
minimal(let_binding) = (* 3 *) TokId TokEq TokInt
minimal(interface) = (* 1 *) TokEOF
minimal(ident) = (* 1 *) TokId
minimal(field_decl_list_aux) = (* 3 *) TokId TokIs TokAny
minimal(field_decl_list) = (* 3 *) TokId TokIs TokAny
minimal(ext_mpath) = (* 1 *) TokCapId
minimal(expr_simp) = (* 1 *) TokInt
minimal(expr_record_aux) = (* 3 *) TokId TokEq TokInt
minimal(expr_record) = (* 3 *) TokId TokEq TokInt
minimal(expr_fun) = (* 1 *) TokInt
minimal(expr_arg) = (* 1 *) TokInt
minimal(expr) = (* 1 *) TokInt
minimal(exception_def_simp) = (* 2 *) TokException TokCapId
minimal(exception_def) = (* 2 *) TokException TokCapId
minimal(def_list) = (* 0 *) 
minimal(def) = (* 2 *) TokType TokId
minimal(constr_decl_list) = (* 1 *) TokCapId
minimal(constr_decl) = (* 1 *) TokCapId
minimal(constr_cap_ident) = (* 1 *) TokCapId
minimal(const_expr_not_cons) = (* 1 *) TokInt
minimal(const_expr) = (* 1 *) TokCapId
minimal(cap_ident) = (* 1 *) TokCapId
follow(when_opt) = TokRArrow
follow(vpath_cap) = TokWith TokWhile TokWhen TokType TokTo TokThen TokString TokStar TokSemiSemi TokSemi TokSSOr TokSSAnd TokRRecord TokRParen TokRList TokRArrow TokRArray TokOpen TokOpPreN1 TokOpMinusDot TokOpMinus TokOpInR6 TokOpInR16 TokOpInR10 TokOpInN12 TokOpInL8 TokOpInL7 TokOpInL14 TokOpInL13 TokOpInL11 TokModule TokLet TokLRecord TokLParen TokLList TokLArray TokIs TokInt TokInclude TokIn TokId TokFor TokFloat TokExternal TokException TokEq TokEnd TokElse TokEOF TokDownto TokDotDot TokDone TokDo TokCons TokComma TokChar TokCapId TokBegin TokAs TokAny TokAnd TokAlt
follow(vpath) = TokWith TokWhile TokVal TokType TokTo TokThen TokString TokStar TokSemiSemi TokSemi TokSSOr TokSSAnd TokRRecord TokRParen TokRList TokRArrow TokRArray TokOpen TokOpPreN1 TokOpMinusDot TokOpMinus TokOpInR6 TokOpInR16 TokOpInR10 TokOpInN12 TokOpInL8 TokOpInL7 TokOpInL14 TokOpInL13 TokOpInL11 TokModule TokLet TokLRecord TokLParen TokLList TokLArrow TokLArray TokIs TokInt TokInclude TokIn TokId TokFor TokFloat TokExternal TokException TokEq TokEnd TokElse TokEOF TokDownto TokDot TokDone TokDo TokCons TokComma TokChar TokCapId TokBegin TokAnd TokAlt
follow(type_tuple_aux) = TokVal TokType TokStar TokSemiSemi TokOpen TokModule TokLet TokInclude TokExternal TokException TokEnd TokEOF TokAnd TokAlt
follow(type_tuple) = TokWith TokVal TokType TokSemiSemi TokSemi TokRRecord TokRParen TokRArrow TokOpen TokModule TokLet TokInclude TokExternal TokException TokEq TokEnd TokEOF TokComma TokAnd
follow(type_params) = TokId TokCapId
follow(type_param_list) = TokRParen TokComma
follow(type_info) = TokVal TokType TokSemiSemi TokOpen TokModule TokLet TokInclude TokExternal TokException TokEnd TokEOF TokAnd
follow(type_expr_list) = TokComma
follow(type_expr_limited) = TokWith TokVal TokType TokStar TokSemiSemi TokSemi TokRRecord TokRParen TokRArrow TokOpen TokModule TokLet TokLParen TokInclude TokId TokExternal TokException TokEq TokEnd TokEOF TokComma TokCapId TokAnd TokAlt
follow(type_expr) = TokWith TokVal TokType TokSemiSemi TokSemi TokRRecord TokRParen TokOpen TokModule TokLet TokInclude TokExternal TokException TokEq TokEnd TokEOF TokComma TokAnd
follow(type_definition) = TokVal TokType TokSemiSemi TokOpen TokModule TokLet TokInclude TokExternal TokException TokEnd TokEOF
follow(type_def_list) = TokVal TokType TokSemiSemi TokOpen TokModule TokLet TokInclude TokExternal TokException TokEnd TokEOF
follow(type_def) = TokVal TokType TokSemiSemi TokOpen TokModule TokLet TokInclude TokExternal TokException TokEnd TokEOF TokAnd
follow(topstmt) = #
follow(spec_list) = TokVal TokType TokSemiSemi TokOpen TokModule TokInclude TokExternal TokException TokEnd TokEOF
follow(spec) = TokVal TokType TokSemiSemi TokOpen TokModule TokInclude TokExternal TokException TokEnd TokEOF
follow(pure_vpath) = TokEq
follow(prog) = #
follow(pattern_tuple) = TokWhen TokSemi TokRRecord TokRParen TokRList TokRArrow TokIs TokEq TokAs TokAlt
follow(pattern_record) = TokRRecord
follow(pattern_no_tuple) = TokWhen TokSemi TokRRecord TokRParen TokRList TokRArrow TokIs TokEq TokCons TokComma TokAs TokAlt
follow(pattern_match_list) = TokWith TokType TokTo TokThen TokStar TokSemiSemi TokSemi TokSSOr TokSSAnd TokRRecord TokRParen TokRList TokRArrow TokRArray TokOpen TokOpMinusDot TokOpMinus TokOpInR6 TokOpInR16 TokOpInR10 TokOpInN12 TokOpInL8 TokOpInL7 TokOpInL14 TokOpInL13 TokOpInL11 TokModule TokLet TokIs TokInclude TokIn TokExternal TokException TokEq TokEnd TokElse TokEOF TokDownto TokDone TokDo TokCons TokComma TokAnd TokAlt
follow(pattern_match) = TokWith TokType TokTo TokThen TokStar TokSemiSemi TokSemi TokSSOr TokSSAnd TokRRecord TokRParen TokRList TokRArrow TokRArray TokOpen TokOpMinusDot TokOpMinus TokOpInR6 TokOpInR16 TokOpInR10 TokOpInN12 TokOpInL8 TokOpInL7 TokOpInL14 TokOpInL13 TokOpInL11 TokModule TokLet TokIs TokInclude TokIn TokExternal TokException TokEq TokEnd TokElse TokEOF TokDownto TokDone TokDo TokCons TokComma TokAnd TokAlt
follow(pattern_list) = TokRList
follow(pattern_limited) = TokWhen TokString TokSemi TokRRecord TokRParen TokRList TokRArrow TokLRecord TokLParen TokLList TokIs TokInt TokId TokFloat TokEq TokCons TokComma TokChar TokCapId TokAs TokAny TokAlt
follow(pattern) = TokWhen TokSemi TokRRecord TokRParen TokRList TokRArrow TokIs TokEq TokAs TokAlt
follow(param_list) = TokWhen TokRArrow TokIs TokEq
follow(operator) = TokRParen
follow(mutable_opt) = TokId
follow(mpath) = TokWith TokVal TokType TokSemiSemi TokRParen TokOpen TokModule TokLet TokLParen TokIs TokInclude TokExternal TokException TokEq TokEnd TokEOF
follow(module_type_constraints) = TokWith TokVal TokType TokSemiSemi TokRParen TokOpen TokModule TokLet TokInclude TokExternal TokException TokEq TokEnd TokEOF TokAnd
follow(module_type) = TokWith TokVal TokType TokSemiSemi TokRParen TokOpen TokModule TokLet TokInclude TokExternal TokException TokEq TokEnd TokEOF
follow(module_expr) = TokType TokSemiSemi TokRParen TokOpen TokModule TokLet TokLParen TokIs TokInclude TokExternal TokException TokEnd TokEOF
follow(module_contrain_opt) = TokEq
follow(module_args) = TokLParen TokIs TokEq
follow(let_rec_opt) = TokString TokLRecord TokLParen TokLList TokInt TokId TokFloat TokChar TokCapId TokAny
follow(let_binding_list) = TokType TokSemiSemi TokOpen TokModule TokLet TokInclude TokIn TokExternal TokException TokEnd TokEOF
follow(let_binding) = TokType TokSemiSemi TokOpen TokModule TokLet TokInclude TokIn TokExternal TokException TokEnd TokEOF TokAnd
follow(interface) = #
follow(ident) = TokWith TokWhile TokWhen TokVal TokType TokTo TokThen TokString TokStar TokSemiSemi TokSemi TokSSOr TokSSAnd TokRRecord TokRParen TokRList TokRArrow TokRArray TokOpen TokOpPreN1 TokOpMinusDot TokOpMinus TokOpInR6 TokOpInR16 TokOpInR10 TokOpInN12 TokOpInL8 TokOpInL7 TokOpInL14 TokOpInL13 TokOpInL11 TokModule TokLet TokLRecord TokLParen TokLList TokLArrow TokLArray TokIs TokInt TokInclude TokIn TokId TokFor TokFloat TokExternal TokException TokEq TokEnd TokElse TokEOF TokDownto TokDot TokDone TokDo TokCons TokComma TokChar TokCapId TokBegin TokAs TokAny TokAnd TokAlt
follow(field_decl_list_aux) = TokSemi TokRRecord
follow(field_decl_list) = TokRRecord
follow(ext_mpath) = TokWith TokVal TokType TokSemiSemi TokRParen TokOpen TokModule TokLet TokLParen TokInclude TokExternal TokException TokEq TokEnd TokEOF TokDot TokAnd
follow(expr_simp) = TokWith TokWhile TokType TokTo TokThen TokString TokStar TokSemiSemi TokSemi TokSSOr TokSSAnd TokRRecord TokRParen TokRList TokRArrow TokRArray TokOpen TokOpPreN1 TokOpMinusDot TokOpMinus TokOpInR6 TokOpInR16 TokOpInR10 TokOpInN12 TokOpInL8 TokOpInL7 TokOpInL14 TokOpInL13 TokOpInL11 TokModule TokLet TokLRecord TokLParen TokLList TokLArray TokIs TokInt TokInclude TokIn TokId TokFor TokFloat TokExternal TokException TokEq TokEnd TokElse TokEOF TokDownto TokDot TokDone TokDo TokCons TokComma TokChar TokCapId TokBegin TokAnd TokAlt
follow(expr_record_aux) = TokSemi TokRRecord
follow(expr_record) = TokRRecord
follow(expr_fun) = TokWith TokWhile TokType TokTo TokThen TokString TokStar TokSemiSemi TokSemi TokSSOr TokSSAnd TokRRecord TokRParen TokRList TokRArrow TokRArray TokOpen TokOpPreN1 TokOpMinusDot TokOpMinus TokOpInR6 TokOpInR16 TokOpInR10 TokOpInN12 TokOpInL8 TokOpInL7 TokOpInL14 TokOpInL13 TokOpInL11 TokModule TokLet TokLRecord TokLParen TokLList TokLArray TokIs TokInt TokInclude TokIn TokId TokFor TokFloat TokExternal TokException TokEq TokEnd TokElse TokEOF TokDownto TokDone TokDo TokCons TokComma TokChar TokCapId TokBegin TokAnd TokAlt
follow(expr_arg) = TokWith TokWhile TokType TokTo TokThen TokString TokStar TokSemiSemi TokSemi TokSSOr TokSSAnd TokRRecord TokRParen TokRList TokRArrow TokRArray TokOpen TokOpPreN1 TokOpMinusDot TokOpMinus TokOpInR6 TokOpInR16 TokOpInR10 TokOpInN12 TokOpInL8 TokOpInL7 TokOpInL14 TokOpInL13 TokOpInL11 TokModule TokLet TokLRecord TokLParen TokLList TokLArray TokIs TokInt TokInclude TokIn TokId TokFor TokFloat TokExternal TokException TokEq TokEnd TokElse TokEOF TokDownto TokDone TokDo TokCons TokComma TokChar TokCapId TokBegin TokAnd TokAlt
follow(expr) = TokWith TokType TokTo TokThen TokStar TokSemiSemi TokSemi TokSSOr TokSSAnd TokRRecord TokRParen TokRList TokRArrow TokRArray TokOpen TokOpMinusDot TokOpMinus TokOpInR6 TokOpInR16 TokOpInR10 TokOpInN12 TokOpInL8 TokOpInL7 TokOpInL14 TokOpInL13 TokOpInL11 TokModule TokLet TokIs TokInclude TokIn TokExternal TokException TokEq TokEnd TokElse TokEOF TokDownto TokDone TokDo TokCons TokComma TokAnd TokAlt
follow(exception_def_simp) = TokVal TokType TokSemiSemi TokOpen TokModule TokLet TokInclude TokExternal TokException TokEnd TokEOF
follow(exception_def) = TokType TokSemiSemi TokOpen TokModule TokLet TokInclude TokExternal TokException TokEnd TokEOF
follow(def_list) = TokEnd TokEOF
follow(def) = TokType TokSemiSemi TokOpen TokModule TokLet TokInclude TokExternal TokException TokEnd TokEOF
follow(constr_decl_list) = TokVal TokType TokSemiSemi TokOpen TokModule TokLet TokInclude TokExternal TokException TokEnd TokEOF TokAnd TokAlt
follow(constr_decl) = TokVal TokType TokSemiSemi TokOpen TokModule TokLet TokInclude TokExternal TokException TokEnd TokEOF TokAnd TokAlt
follow(constr_cap_ident) = TokOf
follow(const_expr_not_cons) = TokWith TokWhile TokWhen TokType TokTo TokThen TokString TokStar TokSemiSemi TokSemi TokSSOr TokSSAnd TokRRecord TokRParen TokRList TokRArrow TokRArray TokOpen TokOpPreN1 TokOpMinusDot TokOpMinus TokOpInR6 TokOpInR16 TokOpInR10 TokOpInN12 TokOpInL8 TokOpInL7 TokOpInL14 TokOpInL13 TokOpInL11 TokModule TokLet TokLRecord TokLParen TokLList TokLArray TokIs TokInt TokInclude TokIn TokId TokFor TokFloat TokExternal TokException TokEq TokEnd TokElse TokEOF TokDownto TokDotDot TokDot TokDone TokDo TokCons TokComma TokChar TokCapId TokBegin TokAs TokAny TokAnd TokAlt
follow(const_expr) = TokWhen TokString TokSemi TokRRecord TokRParen TokRList TokRArrow TokLRecord TokLParen TokLList TokIs TokInt TokId TokFloat TokEq TokDotDot TokCons TokComma TokChar TokCapId TokAs TokAny TokAlt
follow(cap_ident) = TokWith TokWhile TokWhen TokVal TokType TokTo TokThen TokString TokStar TokSemiSemi TokSemi TokSSOr TokSSAnd TokRRecord TokRParen TokRList TokRArrow TokRArray TokOpen TokOpPreN1 TokOpMinusDot TokOpMinus TokOpInR6 TokOpInR16 TokOpInR10 TokOpInN12 TokOpInL8 TokOpInL7 TokOpInL14 TokOpInL13 TokOpInL11 TokOf TokModule TokLet TokLRecord TokLParen TokLList TokLArray TokIs TokInt TokInclude TokIn TokId TokFor TokFloat TokExternal TokException TokEq TokEnd TokElse TokEOF TokDownto TokDotDot TokDone TokDo TokCons TokComma TokChar TokCapId TokBegin TokAs TokAny TokAnd TokAlt
Built an LR(0) automaton with 507 states.
The grammar is not SLR(1) -- 43 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 507 states.
517 shift/reduce conflicts were silently solved.
File "mcc-naml.mly", line 236, characters 0-9:
Warning: the precedence level assigned to TokBegin is never useful.
File "mcc-naml.mly", line 235, characters 0-9:
Warning: the precedence level assigned to TokCapId is never useful.
File "mcc-naml.mly", line 210, characters 0-9:
Warning: the precedence level assigned to TokChar is never useful.
File "mcc-naml.mly", line 210, characters 0-9:
Warning: the precedence level assigned to TokFloat is never useful.
File "mcc-naml.mly", line 211, characters 0-9:
Warning: the precedence level assigned to TokFun is never useful.
File "mcc-naml.mly", line 211, characters 0-9:
Warning: the precedence level assigned to TokFunction is never useful.
File "mcc-naml.mly", line 210, characters 0-9:
Warning: the precedence level assigned to TokId is never useful.
File "mcc-naml.mly", line 213, characters 0-9:
Warning: the precedence level assigned to TokIf is never useful.
File "mcc-naml.mly", line 210, characters 0-9:
Warning: the precedence level assigned to TokInt is never useful.
File "mcc-naml.mly", line 236, characters 0-9:
Warning: the precedence level assigned to TokLArray is never useful.
File "mcc-naml.mly", line 218, characters 0-6:
Warning: the precedence level assigned to TokLArrow is never useful.
File "mcc-naml.mly", line 236, characters 0-9:
Warning: the precedence level assigned to TokLList is never useful.
File "mcc-naml.mly", line 236, characters 0-9:
Warning: the precedence level assigned to TokLRecord is never useful.
File "mcc-naml.mly", line 211, characters 0-9:
Warning: the precedence level assigned to TokLet is never useful.
File "mcc-naml.mly", line 211, characters 0-9:
Warning: the precedence level assigned to TokMatch is never useful.
File "mcc-naml.mly", line 217, characters 0-6:
Warning: the precedence level assigned to TokRArrow is never useful.
File "mcc-naml.mly", line 210, characters 0-9:
Warning: the precedence level assigned to TokString is never useful.
File "mcc-naml.mly", line 211, characters 0-9:
Warning: the precedence level assigned to TokTry is never useful.
File "mcc-naml.mly", line 215, characters 0-9:
Warning: the precedence level assigned to prec_as is never useful.
File "mcc-naml.mly", line 210, characters 0-9:
Warning: the precedence level assigned to prec_expr_const is never useful.
File "mcc-naml.mly", line 223, characters 0-5:
Warning: the precedence level assigned to prec_expr_l11 is never useful.
File "mcc-naml.mly", line 221, characters 0-5:
Warning: the precedence level assigned to prec_expr_l13 is never useful.
File "mcc-naml.mly", line 220, characters 0-5:
Warning: the precedence level assigned to prec_expr_l14 is never useful.
File "mcc-naml.mly", line 232, characters 0-5:
Warning: the precedence level assigned to prec_expr_l3 is never useful.
File "mcc-naml.mly", line 227, characters 0-5:
Warning: the precedence level assigned to prec_expr_l7 is never useful.
File "mcc-naml.mly", line 226, characters 0-5:
Warning: the precedence level assigned to prec_expr_l8 is never useful.
File "mcc-naml.mly", line 234, characters 0-9:
Warning: the precedence level assigned to prec_expr_n1 is never useful.
File "mcc-naml.mly", line 222, characters 0-9:
Warning: the precedence level assigned to prec_expr_n12 is never useful.
File "mcc-naml.mly", line 219, characters 0-6:
Warning: the precedence level assigned to prec_expr_n15 is never useful.
File "mcc-naml.mly", line 233, characters 0-9:
Warning: the precedence level assigned to prec_expr_n2 is never useful.
File "mcc-naml.mly", line 231, characters 0-9:
Warning: the precedence level assigned to prec_expr_n4 is never useful.
File "mcc-naml.mly", line 224, characters 0-6:
Warning: the precedence level assigned to prec_expr_r10 is never useful.
File "mcc-naml.mly", line 212, characters 0-6:
Warning: the precedence level assigned to prec_expr_r18 is never useful.
File "mcc-naml.mly", line 229, characters 0-6:
Warning: the precedence level assigned to prec_expr_r6 is never useful.
File "mcc-naml.mly", line 225, characters 0-6:
Warning: the precedence level assigned to prec_expr_r9 is never useful.
File "mcc-naml.mly", line 219, characters 0-6:
Warning: the precedence level assigned to prec_pat_tuple is never useful.
File "mcc-naml.mly", line 231, characters 0-9:
Warning: the precedence level assigned to prec_ty_cons is never useful.
File "mcc-naml.mly", line 217, characters 0-6:
Warning: the precedence level assigned to prec_ty_fun is never useful.
File "mcc-naml.mly", line 228, characters 0-9:
Warning: the precedence level assigned to prec_ty_tuple is never useful.
File "mcc-naml.mly", line 708, characters 53-66:
Warning: this %prec declaration is never useful.
File "mcc-naml.mly", line 710, characters 44-57:
Warning: this %prec declaration is never useful.
File "mcc-naml.mly", line 715, characters 51-64:
Warning: this %prec declaration is never useful.
File "mcc-naml.mly", line 752, characters 39-54:
Warning: this %prec declaration is never useful.
File "mcc-naml.mly", line 564, characters 52-66:
Warning: this %prec declaration is never useful.
File "mcc-naml.mly", line 566, characters 34-41:
Warning: this %prec declaration is never useful.
File "mcc-naml.mly", line 567, characters 55-62:
Warning: this %prec declaration is never useful.
File "mcc-naml.mly", line 571, characters 57-64:
Warning: this %prec declaration is never useful.
File "mcc-naml.mly", line 646, characters 52-65:
Warning: this %prec declaration is never useful.
141 out of 507 states have a default reduction.
189 out of 507 states are represented.
0 out of 143 symbols keep track of their start position.
0 out of 143 symbols keep track of their end position.
92 out of 230 productions exploit shiftreduce optimization.
0 out of 507 states can peek at an error.
1312 functions before inlining, 201 functions after inlining.
