%{
  open Fonts_type

  let encoding_table = ref (Array.create 256 "")
%}
%start enc_main
%start pfb_human_main
%token DUMB
%token <int> ID_ENCODING
%token <string> NAME_CHARSTRING
%token <string> NAME_ENCODING
%type <string list> enc_main
%type <(string array) * (string list)> pfb_human_main
%%

pfb_human_main:
  _1 = DUMB _2 = encoding _3 = DUMB _4 = charstrings _5 = DUMB
    {                                   ( 
  let rencoding_table = !encoding_table in
  encoding_table := Array.create 256 "";
  (rencoding_table,_4))}

encoding:
  
    {  ()}
| _1 = ID_ENCODING _2 = NAME_ENCODING _3 = encoding
    {                                     ((!encoding_table).(_1)<-_2 )}

charstrings:
  
    {  ([])}
| _1 = NAME_CHARSTRING _2 = charstrings
    {                              ( _1::_2)}

enc_main:
  _1 = DUMB _2 = enc_aux _3 = DUMB
    {                    (_2)}

enc_aux:
  
    {  ([])}
| _1 = NAME_ENCODING _2 = enc_aux
    {                        (_1::_2)}

%%


