Grammar has 5 nonterminal symbols, among which 2 start symbols.
Grammar has 4 terminal symbols.
Grammar has 8 productions.
nullable(pfb_human_main) = false
nullable(encoding) = true
nullable(enc_main) = false
nullable(enc_aux) = true
nullable(charstrings) = true
first(pfb_human_main) = DUMB
first(encoding) = ID_ENCODING
first(enc_main) = DUMB
first(enc_aux) = NAME_ENCODING
first(charstrings) = NAME_CHARSTRING
minimal(pfb_human_main) = (* 3 *) DUMB DUMB DUMB
minimal(encoding) = (* 0 *) 
minimal(enc_main) = (* 2 *) DUMB DUMB
minimal(enc_aux) = (* 0 *) 
minimal(charstrings) = (* 0 *) 
follow(pfb_human_main) = #
follow(encoding) = DUMB
follow(enc_main) = #
follow(enc_aux) = DUMB
follow(charstrings) = DUMB
Built an LR(0) automaton with 19 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 19 states.
7 out of 19 states have a default reduction.
6 out of 19 states are represented.
0 out of 13 symbols keep track of their start position.
0 out of 13 symbols keep track of their end position.
4 out of 10 productions exploit shiftreduce optimization.
0 out of 19 states can peek at an error.
60 functions before inlining, 15 functions after inlining.
