Grammar has 7 nonterminal symbols, among which 1 start symbols.
Grammar has 14 terminal symbols.
Grammar has 16 productions.
nullable(recursive) = true
nullable(left_associative_level(multiplicative_term_,ADDOP,mkbinop)) = false
nullable(left_associative_level(application_term_,MULOP,mkbinop)) = false
nullable(entry) = false
nullable(atomic_term_) = false
nullable(application_term_) = false
nullable(any_term_) = false
first(recursive) = REC
first(left_associative_level(multiplicative_term_,ADDOP,mkbinop)) = PRINT LPAREN INTLITERAL IDENT
first(left_associative_level(application_term_,MULOP,mkbinop)) = PRINT LPAREN INTLITERAL IDENT
first(entry) = PRINT LPAREN LET INTLITERAL IDENT FUN
first(atomic_term_) = LPAREN INTLITERAL IDENT
first(application_term_) = PRINT LPAREN INTLITERAL IDENT
first(any_term_) = PRINT LPAREN LET INTLITERAL IDENT FUN
minimal(recursive) = (* 0 *) 
minimal(left_associative_level(multiplicative_term_,ADDOP,mkbinop)) = (* 1 *) IDENT
minimal(left_associative_level(application_term_,MULOP,mkbinop)) = (* 1 *) IDENT
minimal(entry) = (* 2 *) IDENT EOF
minimal(atomic_term_) = (* 1 *) IDENT
minimal(application_term_) = (* 1 *) IDENT
minimal(any_term_) = (* 1 *) IDENT
follow(recursive) = IDENT
follow(left_associative_level(multiplicative_term_,ADDOP,mkbinop)) = RPAREN IN EOF ADDOP
follow(left_associative_level(application_term_,MULOP,mkbinop)) = RPAREN MULOP IN EOF ADDOP
follow(entry) = #
follow(atomic_term_) = RPAREN MULOP LPAREN INTLITERAL IN IDENT EOF ADDOP
follow(application_term_) = RPAREN MULOP LPAREN INTLITERAL IN IDENT EOF ADDOP
follow(any_term_) = RPAREN IN EOF
Built an LR(0) automaton with 32 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 32 states.
11 out of 32 states have a default reduction.
10 out of 32 states are represented.
11 out of 24 symbols keep track of their start position.
8 out of 24 symbols keep track of their end position.
9 out of 17 productions exploit shiftreduce optimization.
0 out of 32 states can peek at an error.
94 functions before inlining, 17 functions after inlining.
