%start b
%start name_clash_1_a
%token BAR
%token FOO
%type <unit> b
%type <unit> name_clash_1_a
%%

name_clash_1_a:
  _1 = name_clash_1_a1
    {    ( () )}

name_clash_1_a1:
  _1 = FOO
    {      ( () )}

b:
  _1 = name_clash_2_a
    {    ( _1 )}

name_clash_2_a:
  _1 = BAR
    {      ( () )}

%%


Note: the nonterminal symbol a (from name-clash-1.mly) is renamed name_clash_1_a1.
Note: the nonterminal symbol a (from name-clash-2.mly) is renamed name_clash_2_a.
