File "ocaml_parser_menhir.mly", line 594, characters 29-36:
Warning: the token COMMENT is unused.
File "ocaml_parser_menhir.mly", line 595, characters 30-39:
Warning: the token DOCSTRING is unused.
File "ocaml_parser_menhir.mly", line 597, characters 7-10:
Warning: the token EOL is unused.
File "ocaml_parser_menhir.mly", line 515, characters 7-22:
Warning: the token GREATERRBRACKET is unused.
Grammar has 223 nonterminal symbols, among which 7 start symbols.
Grammar has 119 terminal symbols.
Grammar has 809 productions.
Built an LR(0) automaton with 1672 states.
The grammar is not SLR(1) -- 119 states have a conflict.
The construction mode is lalr.
Built an LR(1) automaton with 1672 states.
1053 shift/reduce conflicts were silently solved.
File "ocaml_parser_menhir.mly", line 645, characters 0-9:
Warning: the precedence level assigned to LBRACKETATAT is never useful.
File "ocaml_parser_menhir.mly", line 659, characters 0-9:
Warning: the precedence level assigned to LBRACKETPERCENTPERCENT is never useful.
File "ocaml_parser_menhir.mly", line 1104, characters 66-76:
Warning: this %prec declaration is never useful.
Warning: 466 states have an end-of-stream conflict.
File "ocaml_parser_menhir.mly", line 788, characters 14-14:
Warning: production use_file_tail -> is never reduced.
Warning: in total, 1 production is never reduced.
621 out of 1672 states have a default reduction.
844 out of 1672 states are represented.
210 out of 351 symbols keep track of their start position.
256 out of 351 symbols keep track of their end position.
The action table is 200640 entries; 18163 non-zero; 18356 compressed.
The action table occupies roughly 36800 bytes.
The goto table is 384560 entries; 4861 non-zero; 8949 compressed.
The goto table occupies roughly 17992 bytes.
The error table occupies roughly 25112 bytes.
The default_reduction table occupies roughly 3376 bytes.
The lhs table occupies roughly 848 bytes.
The trace table occupies roughly 8 bytes.
