Note: the nonterminal symbol list (from ocamldoc-odoc_text.mly) is renamed ocamldoc_odoc_text_list.
File "ocamldoc-odoc_text.mly", line 30, characters 7-12:
Warning: the token ERROR is unused.
Grammar has 11 nonterminal symbols, among which 1 start symbols.
Grammar has 44 terminal symbols.
Grammar has 54 productions.
nullable(text_element_list) = false
nullable(text_element) = false
nullable(text) = false
nullable(string) = false
nullable(shortcut_list2) = false
nullable(shortcut_list) = false
nullable(shortcut_enum2) = false
nullable(shortcut_enum) = false
nullable(ocamldoc_odoc_text_list) = false
nullable(main) = false
nullable(item) = false
first(text_element_list) = VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF ENUM EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF
first(text_element) = VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF ENUM EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF
first(text) = VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF ENUM EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF
first(string) = Char
first(shortcut_list2) = SHORTCUT_LIST_ITEM
first(shortcut_list) = VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF ENUM EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF
first(shortcut_enum2) = SHORTCUT_ENUM_ITEM
first(shortcut_enum) = VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF ENUM EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF
first(ocamldoc_odoc_text_list) = ITEM Char
first(main) = VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF
first(item) = ITEM
minimal(text_element_list) = (* 1 *) INDEX_LIST
minimal(text_element) = (* 1 *) INDEX_LIST
minimal(text) = (* 1 *) INDEX_LIST
minimal(string) = (* 1 *) Char
minimal(shortcut_list2) = (* 2 *) SHORTCUT_LIST_ITEM INDEX_LIST
minimal(shortcut_list) = (* 1 *) INDEX_LIST
minimal(shortcut_enum2) = (* 2 *) SHORTCUT_ENUM_ITEM INDEX_LIST
minimal(shortcut_enum) = (* 1 *) INDEX_LIST
minimal(ocamldoc_odoc_text_list) = (* 1 *) Char
minimal(main) = (* 1 *) EOF
minimal(item) = (* 3 *) ITEM INDEX_LIST END
follow(text_element_list) = SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM EOF END_SHORTCUT_LIST END
follow(text_element) = VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITALIC INDEX_LIST EXC_REF EOF ENUM END_SHORTCUT_LIST END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF
follow(text) = SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM EOF END_SHORTCUT_LIST END
follow(string) = VERB VAL_REF Title TYP_REF SUPERSCRIPT SUBSCRIPT SHORTCUT_LIST_ITEM SHORTCUT_ENUM_ITEM SEC_REF RIGHT MOD_REF MOD_LIST_REF MODT_REF MET_REF LIST LINK LEFT LATEX ITEM ITALIC INDEX_LIST EXC_REF EOF ENUM END_VERB END_SHORTCUT_LIST END_LATEX END_CODE_PRE END_CODE END EMP ELE_REF Char CODE_PRE CODE CLT_REF CLA_REF CENTER BOLD BLANK_LINE BEGIN_SHORTCUT_LIST_ITEM BEGIN_SHORTCUT_ENUM_ITEM ATT_REF
follow(shortcut_list2) = EOF END_SHORTCUT_LIST
follow(shortcut_list) = EOF END_SHORTCUT_LIST
follow(shortcut_enum2) = EOF END_SHORTCUT_LIST
follow(shortcut_enum) = EOF END_SHORTCUT_LIST
follow(ocamldoc_odoc_text_list) = END Char
follow(main) = #
follow(item) = ITEM END Char
Built an LR(0) automaton with 123 states.
The grammar is not SLR(1) -- 5 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 123 states.
Warning: 5 states have shift/reduce conflicts.
Warning: 5 shift/reduce conflicts were arbitrarily resolved.
47 out of 123 states have a default reduction.
43 out of 123 states are represented.
0 out of 58 symbols keep track of their start position.
0 out of 58 symbols keep track of their end position.
42 out of 55 productions exploit shiftreduce optimization.
0 out of 123 states can peek at an error.
318 functions before inlining, 45 functions after inlining.
