Grammar has 5 nonterminal symbols, among which 1 start symbols.
Grammar has 5 terminal symbols.
Grammar has 9 productions.
nullable(options) = true
nullable(name_string) = false
nullable(main) = false
nullable(components) = true
nullable(component) = false
first(options) = Name
first(name_string) = String Name
first(main) = Newline Name Eof
first(components) = Newline Name
first(component) = Name
minimal(options) = (* 0 *) 
minimal(name_string) = (* 1 *) Name
minimal(main) = (* 1 *) Eof
minimal(components) = (* 0 *) 
minimal(component) = (* 2 *) Name Newline
follow(options) = Newline
follow(name_string) = Newline Name
follow(main) = #
follow(components) = Eof
follow(component) = Newline Name Eof
Built an LR(0) automaton with 17 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 17 states.
8 out of 17 states have a default reduction.
5 out of 17 states are represented.
0 out of 13 symbols keep track of their start position.
0 out of 13 symbols keep track of their end position.
5 out of 10 productions exploit shiftreduce optimization.
0 out of 17 states can peek at an error.
55 functions before inlining, 12 functions after inlining.
