Note: the nonterminal symbol list (from oclisp.mly) is renamed oclisp_list.
File "oclisp.mly", line 2, characters 25-28:
Warning: the token EOF is unused.
Grammar has 5 nonterminal symbols, among which 1 start symbols.
Grammar has 6 terminal symbols.
Grammar has 10 productions.
nullable(sexp) = false
nullable(oclisp_list) = false
nullable(main) = false
nullable(inside_list) = false
nullable(atom) = false
first(sexp) = QUOTE NAME LBRACKET
first(oclisp_list) = LBRACKET
first(main) = QUOTE NAME LBRACKET
first(inside_list) = QUOTE NAME LBRACKET
first(atom) = NAME
minimal(sexp) = (* 1 *) NAME
minimal(oclisp_list) = (* 2 *) LBRACKET RBRACKET
minimal(main) = (* 1 *) NAME
minimal(inside_list) = (* 1 *) NAME
minimal(atom) = (* 1 *) NAME
follow(sexp) = RBRACKET QUOTE NAME LBRACKET DOT #
follow(oclisp_list) = RBRACKET QUOTE NAME LBRACKET DOT #
follow(main) = #
follow(inside_list) = RBRACKET
follow(atom) = RBRACKET QUOTE NAME LBRACKET DOT #
Built an LR(0) automaton with 16 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 25 states.
16 out of 25 states have a default reduction.
7 out of 25 states are represented.
0 out of 14 symbols keep track of their start position.
0 out of 14 symbols keep track of their end position.
6 out of 11 productions exploit shiftreduce optimization.
0 out of 25 states can peek at an error.
72 functions before inlining, 18 functions after inlining.
