Note: the nonterminal symbol list (from octavius.1.2.0-octParser.mly) is renamed octavius_1_2_0_octParser_list.
File "octavius.1.2.0-octParser.mly", line 187, characters 7-10:
Warning: the token EOF is unused.
File "octavius.1.2.0-octParser.mly", line 202, characters 10-22:
Warning: the token Reduce_error is unused.
Grammar has 30 nonterminal symbols, among which 2 start symbols.
Grammar has 51 terminal symbols.
Grammar has 141 productions.
nullable(whitespace) = true
nullable(text_tag) = false
nullable(text_item_after_line) = false
nullable(text_item) = false
nullable(text_element) = false
nullable(text_body_with_line) = false
nullable(text_body) = false
nullable(text) = true
nullable(tags) = false
nullable(string_item) = false
nullable(string_char) = false
nullable(string_body) = false
nullable(string) = true
nullable(simple_tag) = false
nullable(shortcut_text_body) = false
nullable(shortcut_list_final) = false
nullable(shortcut_list) = false
nullable(shortcut_enum_final) = false
nullable(shortcut_enum) = false
nullable(reference_parts) = false
nullable(reference_part) = false
nullable(octavius_1_2_0_octParser_list) = false
nullable(newline) = false
nullable(main) = true
nullable(item) = false
nullable(html_text_element) = false
nullable(html_list) = false
nullable(html_item) = false
nullable(blanks) = false
nullable(blank_line) = false
first(whitespace) = NEWLINE BLANK
first(text_tag) = See Raise RETURN Param INLINE DEPRECATED Custom Before AUTHOR
first(text_item_after_line) = Verb Title Target Style Special_Ref Ref Pre_Code PLUS MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BEGIN
first(text_item) = Verb Title Target Style Special_Ref Ref Pre_Code PLUS MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BEGIN
first(text_element) = Verb Title Target Style Special_Ref Ref Pre_Code LIST ENUM Code BEGIN
first(text_body_with_line) = Verb Title Target Style Special_Ref Ref Pre_Code PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BLANK BEGIN
first(text_body) = Verb Title Target Style Special_Ref Ref Pre_Code PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BLANK BEGIN
first(text) = error Verb Title Target Style Special_Ref Ref Pre_Code PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BLANK BEGIN
first(tags) = Version Since See Raise RETURN Param INLINE DEPRECATED Custom Canonical Before AUTHOR
first(string_item) = PLUS NEWLINE MINUS Char BLANK
first(string_char) = PLUS MINUS Char
first(string_body) = PLUS NEWLINE MINUS Char BLANK
first(string) = error PLUS NEWLINE MINUS Char BLANK
first(simple_tag) = Version Since Canonical
first(shortcut_text_body) = NEWLINE BLANK
first(shortcut_list_final) = MINUS
first(shortcut_list) = MINUS
first(shortcut_enum_final) = PLUS
first(shortcut_enum) = PLUS
first(reference_parts) = Ref_part
first(reference_part) = Ref_part
first(octavius_1_2_0_octParser_list) = Item
first(newline) = NEWLINE BLANK
first(main) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST INLINE HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM DEPRECATED Custom Code Char Canonical Before BLANK BEGIN AUTHOR
first(item) = Item
first(html_text_element) = HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold
first(html_list) = HTML_Item
first(html_item) = HTML_Item
first(blanks) = BLANK
first(blank_line) = NEWLINE BLANK
minimal(whitespace) = (* 0 *) 
minimal(text_tag) = (* 1 *) AUTHOR
minimal(text_item_after_line) = (* 1 *) Ref
minimal(text_item) = (* 1 *) MINUS
minimal(text_element) = (* 1 *) Ref
minimal(text_body_with_line) = (* 1 *) NEWLINE
minimal(text_body) = (* 1 *) MINUS
minimal(text) = (* 0 *) 
minimal(tags) = (* 1 *) Version
minimal(string_item) = (* 1 *) Char
minimal(string_char) = (* 1 *) Char
minimal(string_body) = (* 1 *) Char
minimal(string) = (* 0 *) 
minimal(simple_tag) = (* 1 *) Version
minimal(shortcut_text_body) = (* 2 *) BLANK MINUS
minimal(shortcut_list_final) = (* 1 *) MINUS
minimal(shortcut_list) = (* 2 *) MINUS error
minimal(shortcut_enum_final) = (* 1 *) PLUS
minimal(shortcut_enum) = (* 2 *) PLUS error
minimal(reference_parts) = (* 1 *) Ref_part
minimal(reference_part) = (* 1 *) Ref_part
minimal(octavius_1_2_0_octParser_list) = (* 2 *) Item END
minimal(newline) = (* 1 *) NEWLINE
minimal(main) = (* 0 *) 
minimal(item) = (* 2 *) Item END
minimal(html_text_element) = (* 2 *) HTML_Title HTML_END_Title
minimal(html_list) = (* 2 *) HTML_Item HTML_END_ITEM
minimal(html_item) = (* 2 *) HTML_Item HTML_END_ITEM
minimal(blanks) = (* 1 *) BLANK
minimal(blank_line) = (* 2 *) NEWLINE NEWLINE
follow(whitespace) = error Version Since See Raise RETURN Param Item INLINE HTML_Item HTML_END_Title HTML_END_RIGHT HTML_END_LIST HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_ENUM HTML_END_CENTER HTML_END_BOLD END DEPRECATED Custom Canonical Before AUTHOR #
follow(text_tag) = Version Since See Raise RETURN Param INLINE DEPRECATED Custom Canonical Before AUTHOR #
follow(text_item_after_line) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST INLINE HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Canonical Before BLANK BEGIN AUTHOR #
follow(text_item) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST INLINE HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Canonical Before BLANK BEGIN AUTHOR #
follow(text_element) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST INLINE HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Canonical Before BLANK BEGIN AUTHOR #
follow(text_body_with_line) = Verb Title Target Style Special_Ref Ref Pre_Code PLUS MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BEGIN
follow(text_body) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST INLINE HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Canonical Before BLANK BEGIN AUTHOR #
follow(text) = error Version Since See Raise RETURN Param INLINE HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD END DEPRECATED Custom Canonical Before AUTHOR #
follow(tags) = Version Since See Raise RETURN Param INLINE DEPRECATED Custom Canonical Before AUTHOR #
follow(string_item) = Version Since See Raise RETURN Param PLUS NEWLINE MINUS INLINE DEPRECATED Custom Char Canonical Before BLANK AUTHOR #
follow(string_char) = Version Since See Raise RETURN Param PLUS NEWLINE MINUS INLINE DEPRECATED Custom Char Canonical Before BLANK AUTHOR #
follow(string_body) = Version Since See Raise RETURN Param PLUS NEWLINE MINUS INLINE DEPRECATED Custom Char Canonical Before BLANK AUTHOR #
follow(string) = Version Since See Raise RETURN Param INLINE DEPRECATED Custom Canonical Before AUTHOR #
follow(simple_tag) = error Version Since See Raise RETURN Param NEWLINE INLINE DEPRECATED Custom Canonical Before BLANK AUTHOR #
follow(shortcut_text_body) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST INLINE HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Canonical Before BLANK BEGIN AUTHOR #
follow(shortcut_list_final) = error Version Since See Raise RETURN Param INLINE HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD END DEPRECATED Custom Canonical Before AUTHOR #
follow(shortcut_list) = Verb Title Target Style Special_Ref Ref Pre_Code PLUS MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BEGIN
follow(shortcut_enum_final) = error Version Since See Raise RETURN Param INLINE HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD END DEPRECATED Custom Canonical Before AUTHOR #
follow(shortcut_enum) = Verb Title Target Style Special_Ref Ref Pre_Code PLUS MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BEGIN
follow(reference_parts) = DOT #
follow(reference_part) = DOT #
follow(octavius_1_2_0_octParser_list) = error NEWLINE Item END BLANK
follow(newline) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST Item INLINE HTML_Title HTML_Right HTML_List HTML_Left HTML_Item HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LIST HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_ENUM HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Canonical Before BLANK BEGIN AUTHOR #
follow(main) = #
follow(item) = error NEWLINE Item END BLANK
follow(html_text_element) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST INLINE HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Canonical Before BLANK BEGIN AUTHOR #
follow(html_list) = error NEWLINE HTML_Item HTML_END_LIST HTML_END_ENUM BLANK
follow(html_item) = error NEWLINE HTML_Item HTML_END_LIST HTML_END_ENUM BLANK
follow(blanks) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST Item INLINE HTML_Title HTML_Right HTML_List HTML_Left HTML_Item HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LIST HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_ENUM HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Canonical Before BLANK BEGIN AUTHOR #
follow(blank_line) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST Item INLINE HTML_Title HTML_Right HTML_List HTML_Left HTML_Item HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LIST HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_ENUM HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Canonical Before BLANK BEGIN AUTHOR #
Built an LR(0) automaton with 216 states.
The grammar is not SLR(1) -- 28 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 355 states.
22 shift/reduce conflicts were silently solved.
File "octavius.1.2.0-octParser.mly", line 202, characters 0-9:
Warning: the precedence level assigned to Reduce_error is never useful.
Warning: 154 states have an end-of-stream conflict.
File "octavius.1.2.0-octParser.mly", line 214, characters 0-15:
Warning: symbol reference_parts is never accepted.
File "octavius.1.2.0-octParser.mly", line 209, characters 2-6:
Warning: production main -> text is never reduced.
File "octavius.1.2.0-octParser.mly", line 210, characters 2-11:
Warning: production main -> text tags is never reduced.
Warning: in total, 3 productions are never reduced.
204 out of 355 states have a default reduction.
126 out of 355 states are represented.
0 out of 85 symbols keep track of their start position.
0 out of 85 symbols keep track of their end position.
112 out of 143 productions exploit shiftreduce optimization.
94 out of 355 states can peek at an error.
887 functions before inlining, 236 functions after inlining.
