%{

open Odds.Algebra

%}
%start entry
%token D
%token DASH
%token EOF
%token <int> INTEGER
%token LPAREN
%token PLUS
%token RPAREN
%token SLASH
%token STAR
%left DASH PLUS
%left SLASH STAR
%nonassoc NEG
%left D
%type <int Odds.t> entry
%%

entry:
  t = formula _2 = EOF
    {                 ( t )}

formula:
  i = INTEGER
    {             ( !i )}
| _1 = LPAREN t = formula _3 = RPAREN
    {                             ( t )}
| l = formula _2 = D r = formula
    {                         ( dice l r )}
| l = formula _2 = PLUS r = formula
    {                            ( l + r )}
| l = formula _2 = DASH r = formula
    {                            ( l - r )}
| l = formula _2 = STAR r = formula
    {                            ( l * r )}
| l = formula _2 = SLASH r = formula
    {                             ( l / r )}
| _1 = DASH t = formula %prec NEG
    {                            ( ~- t )}

%%




