Grammar has 2 nonterminal symbols, among which 1 start symbols.
Grammar has 9 terminal symbols.
Grammar has 9 productions.
nullable(formula) = false
nullable(entry) = false
first(formula) = LPAREN INTEGER DASH
first(entry) = LPAREN INTEGER DASH
minimal(formula) = (* 1 *) INTEGER
minimal(entry) = (* 2 *) INTEGER EOF
follow(formula) = STAR SLASH RPAREN PLUS EOF DASH D
follow(entry) = #
Built an LR(0) automaton with 20 states.
The grammar is not SLR(1) -- 6 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 20 states.
30 shift/reduce conflicts were silently solved.
5 out of 20 states have a default reduction.
8 out of 20 states are represented.
0 out of 14 symbols keep track of their start position.
0 out of 14 symbols keep track of their end position.
4 out of 10 productions exploit shiftreduce optimization.
0 out of 20 states can peek at an error.
58 functions before inlining, 12 functions after inlining.
