File "omake.0.9.8.7-omake_shell_parse.mly", line 148, characters 34-43:
Warning: the token TokDefine is unused.
Grammar has 5 nonterminal symbols, among which 1 start symbols.
Grammar has 13 terminal symbols.
Grammar has 19 productions.
nullable(word) = false
nullable(rev_command) = false
nullable(prog) = false
nullable(pipe) = false
nullable(command) = false
first(word) = TokValues
first(rev_command) = TokValues
first(prog) = TokValues TokLeftParen TokEof
first(pipe) = TokValues TokLeftParen
first(command) = TokValues
minimal(word) = (* 1 *) TokValues
minimal(rev_command) = (* 1 *) TokValues
minimal(prog) = (* 1 *) TokEof
minimal(pipe) = (* 1 *) TokValues
minimal(command) = (* 1 *) TokValues
follow(word) = TokValues TokSemiColon TokRightParen TokPipe TokOr TokLessThan TokGreaterThan TokGreaterGreaterThan TokEof TokAnd TokAmp
follow(rev_command) = TokValues TokSemiColon TokRightParen TokPipe TokOr TokLessThan TokGreaterThan TokGreaterGreaterThan TokEof TokAnd TokAmp
follow(prog) = #
follow(pipe) = TokSemiColon TokRightParen TokPipe TokOr TokLessThan TokGreaterThan TokGreaterGreaterThan TokEof TokAnd TokAmp
follow(command) = TokSemiColon TokRightParen TokPipe TokOr TokLessThan TokGreaterThan TokGreaterGreaterThan TokEof TokAnd TokAmp
Built an LR(0) automaton with 34 states.
The grammar is not SLR(1) -- 5 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 34 states.
40 shift/reduce conflicts were silently solved.
File "omake.0.9.8.7-omake_shell_parse.mly", line 279, characters 48-62:
Warning: this %prec declaration is never useful.
File "omake.0.9.8.7-omake_shell_parse.mly", line 286, characters 55-76:
Warning: this %prec declaration is never useful.
14 out of 34 states have a default reduction.
13 out of 34 states are represented.
0 out of 21 symbols keep track of their start position.
0 out of 21 symbols keep track of their end position.
14 out of 20 productions exploit shiftreduce optimization.
0 out of 34 states can peek at an error.
99 functions before inlining, 16 functions after inlining.
