Warning: the declaration %on_error_reduce ioption(A)
has no effect: this symbol is marked %inline and is expanded away.
Grammar has 1 nonterminal symbols, among which 1 start symbols.
Grammar has 2 terminal symbols.
Grammar has 2 productions.
nullable(main) = false
first(main) = B A
minimal(main) = (* 1 *) B
follow(main) = #
Built an LR(0) automaton with 5 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 5 states.
3 out of 5 states have a default reduction.
0 out of 5 states are represented.
0 out of 6 symbols keep track of their start position.
0 out of 6 symbols keep track of their end position.
3 out of 3 productions exploit shiftreduce optimization.
0 out of 5 states can peek at an error.
20 functions before inlining, 3 functions after inlining.
