Note: the nonterminal symbol list (from opam-doc.0.9.3-info_parser.mly) is renamed opam_doc_0_9_3_info_parser_list.
File "opam-doc.0.9.3-info_parser.mly", line 160, characters 7-10:
Warning: the token EOF is unused.
File "opam-doc.0.9.3-info_parser.mly", line 169, characters 10-21:
Warning: the token Reduce_eror is unused.
Grammar has 25 nonterminal symbols, among which 1 start symbols.
Grammar has 47 terminal symbols.
Grammar has 128 productions.
nullable(whitespace) = true
nullable(text_item_with_line) = false
nullable(text_item_no_line) = false
nullable(text_item) = false
nullable(text_element) = false
nullable(text_body) = false
nullable(text) = true
nullable(simple_text_item) = false
nullable(shortcuts_final) = false
nullable(shortcuts) = false
nullable(shortcut_text_item) = false
nullable(shortcut_text_body) = false
nullable(shortcut_list_final) = false
nullable(shortcut_list) = false
nullable(shortcut_enum_final) = false
nullable(shortcut_enum) = false
nullable(opam_doc_0_9_3_info_parser_list) = false
nullable(newline) = false
nullable(item) = false
nullable(info) = true
nullable(html_text_element) = false
nullable(html_list) = false
nullable(html_item) = false
nullable(blanks) = false
nullable(blank_line) = false
first(whitespace) = NEWLINE BLANK
first(text_item_with_line) = PLUS MINUS
first(text_item_no_line) = PLUS MINUS
first(text_item) = Verb Title Target Style Special_Ref Ref Pre_Code PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BLANK BEGIN
first(text_element) = Verb Title Target Style Special_Ref Ref Pre_Code LIST ENUM Code BEGIN
first(text_body) = Verb Title Target Style Special_Ref Ref Pre_Code PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BLANK BEGIN
first(text) = error Verb Title Target Style Special_Ref Ref Pre_Code PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BLANK BEGIN
first(simple_text_item) = Verb Title Target Style Special_Ref Ref Pre_Code LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BEGIN
first(shortcuts_final) = PLUS MINUS
first(shortcuts) = PLUS MINUS
first(shortcut_text_item) = Verb Title Target Style Special_Ref Ref Pre_Code PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BLANK BEGIN
first(shortcut_text_body) = NEWLINE BLANK
first(shortcut_list_final) = MINUS
first(shortcut_list) = MINUS
first(shortcut_enum_final) = PLUS
first(shortcut_enum) = PLUS
first(opam_doc_0_9_3_info_parser_list) = Item
first(newline) = NEWLINE BLANK
first(item) = Item
first(info) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM DEPRECATED Custom Code Char Before BLANK BEGIN Author
first(html_text_element) = HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold
first(html_list) = HTML_Item
first(html_item) = HTML_Item
first(blanks) = BLANK
first(blank_line) = NEWLINE BLANK
minimal(whitespace) = (* 0 *) 
minimal(text_item_with_line) = (* 3 *) MINUS error Ref
minimal(text_item_no_line) = (* 1 *) MINUS
minimal(text_item) = (* 1 *) Ref
minimal(text_element) = (* 1 *) Ref
minimal(text_body) = (* 1 *) Ref
minimal(text) = (* 0 *) 
minimal(simple_text_item) = (* 1 *) Ref
minimal(shortcuts_final) = (* 1 *) MINUS
minimal(shortcuts) = (* 2 *) MINUS error
minimal(shortcut_text_item) = (* 1 *) Ref
minimal(shortcut_text_body) = (* 2 *) BLANK Ref
minimal(shortcut_list_final) = (* 1 *) MINUS
minimal(shortcut_list) = (* 2 *) MINUS error
minimal(shortcut_enum_final) = (* 1 *) PLUS
minimal(shortcut_enum) = (* 2 *) PLUS error
minimal(opam_doc_0_9_3_info_parser_list) = (* 2 *) Item END
minimal(newline) = (* 1 *) NEWLINE
minimal(item) = (* 2 *) Item END
minimal(info) = (* 0 *) 
minimal(html_text_element) = (* 2 *) HTML_Title HTML_END_Title
minimal(html_list) = (* 2 *) HTML_Item HTML_END_ITEM
minimal(html_item) = (* 2 *) HTML_Item HTML_END_ITEM
minimal(blanks) = (* 1 *) BLANK
minimal(blank_line) = (* 2 *) NEWLINE NEWLINE
follow(whitespace) = error Version Since See Raise RETURN Param Item HTML_Item HTML_END_Title HTML_END_RIGHT HTML_END_LIST HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_ENUM HTML_END_CENTER HTML_END_BOLD END DEPRECATED Custom Before Author #
follow(text_item_with_line) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Before BLANK BEGIN Author #
follow(text_item_no_line) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Before BLANK BEGIN Author #
follow(text_item) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Before BLANK BEGIN Author #
follow(text_element) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Before BLANK BEGIN Author #
follow(text_body) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Before BLANK BEGIN Author #
follow(text) = error Version Since See Raise RETURN Param HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD END DEPRECATED Custom Before Author #
follow(simple_text_item) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Before BLANK BEGIN Author #
follow(shortcuts_final) = error Version Since See Raise RETURN Param HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD END DEPRECATED Custom Before Author #
follow(shortcuts) = Verb Title Target Style Special_Ref Ref Pre_Code PLUS MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BEGIN
follow(shortcut_text_item) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Before BLANK BEGIN Author #
follow(shortcut_text_body) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Before BLANK BEGIN Author #
follow(shortcut_list_final) = error Version Since See Raise RETURN Param HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD END DEPRECATED Custom Before Author #
follow(shortcut_list) = Verb Title Target Style Special_Ref Ref Pre_Code PLUS MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BEGIN
follow(shortcut_enum_final) = error Version Since See Raise RETURN Param HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD END DEPRECATED Custom Before Author #
follow(shortcut_enum) = Verb Title Target Style Special_Ref Ref Pre_Code PLUS MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_Center HTML_Bold ENUM Code Char BEGIN
follow(opam_doc_0_9_3_info_parser_list) = error NEWLINE Item END BLANK
follow(newline) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST Item HTML_Title HTML_Right HTML_List HTML_Left HTML_Item HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LIST HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_ENUM HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Before BLANK BEGIN Author #
follow(item) = error NEWLINE Item END BLANK
follow(info) = Version Since See Raise RETURN Param DEPRECATED Custom Before Author #
follow(html_text_element) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST HTML_Title HTML_Right HTML_List HTML_Left HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Before BLANK BEGIN Author #
follow(html_list) = error NEWLINE HTML_Item HTML_END_LIST HTML_END_ENUM BLANK
follow(html_item) = error NEWLINE HTML_Item HTML_END_LIST HTML_END_ENUM BLANK
follow(blanks) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST Item HTML_Title HTML_Right HTML_List HTML_Left HTML_Item HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LIST HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_ENUM HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Before BLANK BEGIN Author #
follow(blank_line) = error Version Verb Title Target Style Special_Ref Since See Ref Raise RETURN Pre_Code Param PLUS NEWLINE MINUS LIST Item HTML_Title HTML_Right HTML_List HTML_Left HTML_Item HTML_Italic HTML_Enum HTML_END_Title HTML_END_RIGHT HTML_END_LIST HTML_END_LEFT HTML_END_ITEM HTML_END_ITALIC HTML_END_ENUM HTML_END_CENTER HTML_END_BOLD HTML_Center HTML_Bold ENUM END DEPRECATED Custom Code Char Before BLANK BEGIN Author #
Built an LR(0) automaton with 195 states.
The grammar is not SLR(1) -- 28 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 342 states.
22 shift/reduce conflicts were silently solved.
File "opam-doc.0.9.3-info_parser.mly", line 169, characters 0-9:
Warning: the precedence level assigned to Reduce_eror is never useful.
Warning: 137 states have an end-of-stream conflict.
File "opam-doc.0.9.3-info_parser.mly", line 175, characters 0-4:
Warning: symbol info is never accepted.
Warning: in total, 1 production is never reduced.
208 out of 342 states have a default reduction.
111 out of 342 states are represented.
0 out of 75 symbols keep track of their start position.
0 out of 75 symbols keep track of their end position.
104 out of 129 productions exploit shiftreduce optimization.
86 out of 342 states can peek at an error.
The generated parser cannot raise Error.
843 functions before inlining, 214 functions after inlining.
