%start main
%token <int> A
%token <int> B
%token <int> C
%token <int> D
%token EOF
%type <int> main
%%

fst_pair_new_syntax_pair_A_B__:
  x = A y = B
    {let _1 =                 ( x, y ) in
let (_1_1, _) = _1 in
_1_1}

snd_pair_new_syntax_pair_A_B__:
  x = A y = B
    {let _1 =                 ( x, y ) in
let (_, _1_1) = _1 in
_1_1}

main:
  x = A y = B c = fst_pair_new_syntax_pair_A_B__ d = snd_pair_new_syntax_pair_A_B__ _4 = C _5 = D _6 = EOF
    {let _1 =                 ( x, y ) in
let (a, b) = _1 in
_6;
    ( a + b + c + d )}

%%


Note: the nonterminal symbol pair (from pair-new-syntax.mly) is renamed pair_new_syntax_pair.
