File "photos.mly", line 37, characters 7-10:
Warning: the token EOF is unused.
Grammar has 5 nonterminal symbols, among which 1 start symbols.
Grammar has 18 terminal symbols.
Grammar has 21 productions.
nullable(query2) = false
nullable(query1) = false
nullable(query0) = false
nullable(query) = false
nullable(date) = false
first(query2) = YESTERDAY TRUE TODAY ON NOT NAME MATCHES LPAREN HAS BEFORE AFTER
first(query1) = YESTERDAY TRUE TODAY ON NOT NAME MATCHES LPAREN HAS BEFORE AFTER
first(query0) = YESTERDAY TRUE TODAY ON NOT NAME MATCHES LPAREN HAS BEFORE AFTER
first(query) = YESTERDAY TRUE TODAY ON NOT NAME MATCHES LPAREN HAS BEFORE AFTER
first(date) = NUMBER
minimal(query2) = (* 1 *) TODAY
minimal(query1) = (* 1 *) TODAY
minimal(query0) = (* 1 *) TODAY
minimal(query) = (* 1 *) TODAY
minimal(date) = (* 2 *) NUMBER error
follow(query2) = RPAREN OR #
follow(query1) = RPAREN OR AND #
follow(query0) = RPAREN OR AND #
follow(query) = RPAREN #
follow(date) = RPAREN OR AND #
Built an LR(0) automaton with 38 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 39 states.
Warning: 21 states have an end-of-stream conflict.
19 out of 39 states have a default reduction.
8 out of 39 states are represented.
0 out of 26 symbols keep track of their start position.
0 out of 26 symbols keep track of their end position.
18 out of 22 productions exploit shiftreduce optimization.
0 out of 39 states can peek at an error.
111 functions before inlining, 22 functions after inlining.
