Note: the nonterminal symbol a (from private-and-public-2.mly) is renamed private_and_public_2_a.
Grammar has 4 nonterminal symbols, among which 1 start symbols.
Grammar has 1 terminal symbols.
Grammar has 4 productions.
nullable(private_and_public_2_a) = false
nullable(c) = false
nullable(b) = false
nullable(a) = true
first(private_and_public_2_a) = C
first(c) = C
first(b) = C
first(a) = 
minimal(private_and_public_2_a) = (* 1 *) C
minimal(c) = (* 1 *) C
minimal(b) = (* 1 *) C
minimal(a) = (* 0 *) 
follow(private_and_public_2_a) = #
follow(c) = #
follow(b) = #
follow(a) = C
Built an LR(0) automaton with 6 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 6 states.
5 out of 6 states have a default reduction.
0 out of 6 states are represented.
0 out of 8 symbols keep track of their start position.
0 out of 8 symbols keep track of their end position.
4 out of 5 productions exploit shiftreduce optimization.
0 out of 6 states can peek at an error.
27 functions before inlining, 1 functions after inlining.
