Grammar has 16 nonterminal symbols, among which 1 start symbols.
Grammar has 39 terminal symbols.
Grammar has 51 productions.
nullable(transitions) = false
nullable(transition) = false
nullable(states) = false
nullable(state_labels) = false
nullable(state_body) = false
nullable(state) = false
nullable(promela) = false
nullable(logic_relation) = false
nullable(label) = false
nullable(guard) = false
nullable(arith_relation_mul) = false
nullable(arith_relation) = false
nullable(access_or_const) = false
nullable(access_leaf) = false
nullable(access_array) = false
nullable(access) = false
first(transitions) = PROMELA_DOUBLE_COLON
first(transition) = PROMELA_DOUBLE_COLON
first(states) = PROMELA_LABEL
first(state_labels) = PROMELA_LABEL
first(state_body) = PROMELA_SKIP PROMELA_IF PROMELA_FALSE
first(state) = PROMELA_LABEL
first(promela) = PROMELA_NEVER
first(logic_relation) = PROMELA_STAR PROMELA_MINUS PROMELA_LPAREN PROMELA_LABEL PROMELA_INT
first(label) = PROMELA_LABEL
first(guard) = PROMELA_TRUE PROMELA_STAR PROMELA_RETURNOF PROMELA_NOT PROMELA_MINUS PROMELA_LPAREN PROMELA_LABEL PROMELA_INT PROMELA_FALSE PROMELA_CALLORRETURNOF PROMELA_CALLOF
first(arith_relation_mul) = PROMELA_STAR PROMELA_MINUS PROMELA_LPAREN PROMELA_LABEL PROMELA_INT
first(arith_relation) = PROMELA_STAR PROMELA_MINUS PROMELA_LPAREN PROMELA_LABEL PROMELA_INT
first(access_or_const) = PROMELA_STAR PROMELA_MINUS PROMELA_LPAREN PROMELA_LABEL PROMELA_INT
first(access_leaf) = PROMELA_STAR PROMELA_LPAREN PROMELA_LABEL
first(access_array) = PROMELA_STAR PROMELA_LPAREN PROMELA_LABEL
first(access) = PROMELA_STAR PROMELA_LPAREN PROMELA_LABEL
minimal(transitions) = (* 5 *) PROMELA_DOUBLE_COLON PROMELA_CALLORRETURNOF PROMELA_RIGHT_ARROW PROMELA_GOTO PROMELA_LABEL
minimal(transition) = (* 5 *) PROMELA_DOUBLE_COLON PROMELA_CALLORRETURNOF PROMELA_RIGHT_ARROW PROMELA_GOTO PROMELA_LABEL
minimal(states) = (* 3 *) PROMELA_LABEL PROMELA_COLON PROMELA_SKIP
minimal(state_labels) = (* 2 *) PROMELA_LABEL PROMELA_COLON
minimal(state_body) = (* 1 *) PROMELA_SKIP
minimal(state) = (* 3 *) PROMELA_LABEL PROMELA_COLON PROMELA_SKIP
minimal(promela) = (* 7 *) PROMELA_NEVER PROMELA_LBRACE PROMELA_LABEL PROMELA_COLON PROMELA_SKIP PROMELA_RBRACE EOF
minimal(logic_relation) = (* 1 *) PROMELA_INT
minimal(label) = (* 2 *) PROMELA_LABEL PROMELA_COLON
minimal(guard) = (* 1 *) PROMELA_CALLORRETURNOF
minimal(arith_relation_mul) = (* 1 *) PROMELA_INT
minimal(arith_relation) = (* 1 *) PROMELA_INT
minimal(access_or_const) = (* 1 *) PROMELA_INT
minimal(access_leaf) = (* 1 *) PROMELA_LABEL
minimal(access_array) = (* 1 *) PROMELA_LABEL
minimal(access) = (* 1 *) PROMELA_LABEL
follow(transitions) = PROMELA_FI PROMELA_DOUBLE_COLON
follow(transition) = PROMELA_FI PROMELA_DOUBLE_COLON
follow(states) = PROMELA_SEMICOLON PROMELA_RBRACE
follow(state_labels) = PROMELA_SKIP PROMELA_IF PROMELA_FALSE
follow(state_body) = PROMELA_SEMICOLON PROMELA_RBRACE
follow(state) = PROMELA_SEMICOLON PROMELA_RBRACE
follow(promela) = #
follow(logic_relation) = PROMELA_RPAREN PROMELA_RIGHT_ARROW PROMELA_OR PROMELA_AND
follow(label) = PROMELA_SKIP PROMELA_LABEL PROMELA_IF PROMELA_FALSE
follow(guard) = PROMELA_RPAREN PROMELA_RIGHT_ARROW PROMELA_OR PROMELA_AND
follow(arith_relation_mul) = PROMELA_STAR PROMELA_RPAREN PROMELA_RIGHT_ARROW PROMELA_PLUS PROMELA_OR PROMELA_NEQ PROMELA_MODULO PROMELA_MINUS PROMELA_LT PROMELA_LE PROMELA_GT PROMELA_GE PROMELA_EQ PROMELA_DIV PROMELA_AND
follow(arith_relation) = PROMELA_RPAREN PROMELA_RIGHT_ARROW PROMELA_OR PROMELA_NEQ PROMELA_LT PROMELA_LE PROMELA_GT PROMELA_GE PROMELA_EQ PROMELA_AND
follow(access_or_const) = PROMELA_STAR PROMELA_RPAREN PROMELA_RIGHT_SQUARE PROMELA_RIGHT_ARROW PROMELA_PLUS PROMELA_OR PROMELA_NEQ PROMELA_MODULO PROMELA_MINUS PROMELA_LT PROMELA_LE PROMELA_GT PROMELA_GE PROMELA_EQ PROMELA_DIV PROMELA_AND
follow(access_leaf) = PROMELA_STAR PROMELA_RPAREN PROMELA_RIGHT_SQUARE PROMELA_RIGHT_ARROW PROMELA_PLUS PROMELA_OR PROMELA_NEQ PROMELA_MODULO PROMELA_MINUS PROMELA_LT PROMELA_LEFT_SQUARE PROMELA_LE PROMELA_GT PROMELA_GE PROMELA_EQ PROMELA_DOT PROMELA_DIV PROMELA_AND
follow(access_array) = PROMELA_STAR PROMELA_RPAREN PROMELA_RIGHT_SQUARE PROMELA_RIGHT_ARROW PROMELA_PLUS PROMELA_OR PROMELA_NEQ PROMELA_MODULO PROMELA_MINUS PROMELA_LT PROMELA_LEFT_SQUARE PROMELA_LE PROMELA_GT PROMELA_GE PROMELA_EQ PROMELA_DOT PROMELA_DIV PROMELA_AND
follow(access) = PROMELA_STAR PROMELA_RPAREN PROMELA_RIGHT_SQUARE PROMELA_RIGHT_ARROW PROMELA_PLUS PROMELA_OR PROMELA_NEQ PROMELA_MODULO PROMELA_MINUS PROMELA_LT PROMELA_LEFT_SQUARE PROMELA_LE PROMELA_GT PROMELA_GE PROMELA_EQ PROMELA_DOT PROMELA_DIV PROMELA_AND
Built an LR(0) automaton with 98 states.
The grammar is not SLR(1) -- 7 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 98 states.
6 shift/reduce conflicts were silently solved.
File "promelaparser_withexps.mly", line 66, characters 0-6:
Warning: the precedence level assigned to PROMELA_DIV is never useful.
File "promelaparser_withexps.mly", line 61, characters 0-6:
Warning: the precedence level assigned to PROMELA_EQ is never useful.
File "promelaparser_withexps.mly", line 50, characters 0-9:
Warning: the precedence level assigned to PROMELA_FALSE is never useful.
File "promelaparser_withexps.mly", line 61, characters 0-6:
Warning: the precedence level assigned to PROMELA_GE is never useful.
File "promelaparser_withexps.mly", line 61, characters 0-6:
Warning: the precedence level assigned to PROMELA_GT is never useful.
File "promelaparser_withexps.mly", line 61, characters 0-6:
Warning: the precedence level assigned to PROMELA_LE is never useful.
File "promelaparser_withexps.mly", line 61, characters 0-6:
Warning: the precedence level assigned to PROMELA_LT is never useful.
File "promelaparser_withexps.mly", line 66, characters 0-6:
Warning: the precedence level assigned to PROMELA_MINUS is never useful.
File "promelaparser_withexps.mly", line 66, characters 0-6:
Warning: the precedence level assigned to PROMELA_MODULO is never useful.
File "promelaparser_withexps.mly", line 61, characters 0-6:
Warning: the precedence level assigned to PROMELA_NEQ is never useful.
File "promelaparser_withexps.mly", line 66, characters 0-6:
Warning: the precedence level assigned to PROMELA_PLUS is never useful.
File "promelaparser_withexps.mly", line 66, characters 0-6:
Warning: the precedence level assigned to PROMELA_STAR is never useful.
File "promelaparser_withexps.mly", line 50, characters 0-9:
Warning: the precedence level assigned to PROMELA_TRUE is never useful.
Warning: 4 states have shift/reduce conflicts.
Warning: 4 shift/reduce conflicts were arbitrarily resolved.
43 out of 98 states have a default reduction.
26 out of 98 states are represented.
0 out of 58 symbols keep track of their start position.
0 out of 58 symbols keep track of their end position.
28 out of 52 productions exploit shiftreduce optimization.
0 out of 98 states can peek at an error.
270 functions before inlining, 45 functions after inlining.
