Grammar has 1 nonterminal symbols, among which 1 start symbols.
Grammar has 2 terminal symbols.
Grammar has 2 productions.
nullable(a) = false
first(a) = J I
minimal(a) = (* 1 *) J
follow(a) = #
Built an LR(0) automaton with 4 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 4 states.
3 out of 4 states have a default reduction.
0 out of 4 states are represented.
0 out of 6 symbols keep track of their start position.
0 out of 6 symbols keep track of their end position.
3 out of 3 productions exploit shiftreduce optimization.
0 out of 4 states can peek at an error.
18 functions before inlining, 2 functions after inlining.
