File "public-2.mly", line 4, characters 8-9:
File "public-1.mly", line 6, characters 8-9:
Warning: symbol a is unreachable from any of the start symbol(s).
Grammar has 1 nonterminal symbols, among which 1 start symbols.
Grammar has 2 terminal symbols.
Grammar has 1 productions.
nullable(s) = false
first(s) = T
minimal(s) = (* 1 *) T
follow(s) = #
Built an LR(0) automaton with 3 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 3 states.
2 out of 3 states have a default reduction.
0 out of 3 states are represented.
0 out of 6 symbols keep track of their start position.
0 out of 6 symbols keep track of their end position.
2 out of 2 productions exploit shiftreduce optimization.
0 out of 3 states can peek at an error.
15 functions before inlining, 1 functions after inlining.
