File "self.mly", line 11, characters 0-1:
Warning: symbol b is unreachable from any of the start symbol(s).
File "self.mly", line 9, characters 0-1:
Warning: symbol s is unreachable from any of the start symbol(s).
Grammar has 1 nonterminal symbols, among which 1 start symbols.
Grammar has 1 terminal symbols.
Grammar has 1 productions.
nullable(dummy) = false
first(dummy) = A
minimal(dummy) = (* 1 *) A
follow(dummy) = #
Built an LR(0) automaton with 3 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 3 states.
2 out of 3 states have a default reduction.
0 out of 3 states are represented.
0 out of 5 symbols keep track of their start position.
0 out of 5 symbols keep track of their end position.
2 out of 2 productions exploit shiftreduce optimization.
0 out of 3 states can peek at an error.
15 functions before inlining, 1 functions after inlining.
