%start phrase
%token ELSE
%token EOF
%token FALSE
%token IF
%token THEN
%token TRUE
%type <bool> phrase
%%

phrase:
  b = expression _2 = EOF
    {    ( b )}

expression:
  _1 = TRUE
    {    ( true )}
| _1 = FALSE
    {    ( false )}
| _1 = IF b = expression _3 = THEN e = expression
    {    ( if b then e else false )}
| _1 = IF b = expression _3 = THEN e1 = expression _5 = ELSE e2 = expression
    {    ( if b then e1 else e2 )}

%%


