Grammar has 2 nonterminal symbols, among which 1 start symbols.
Grammar has 2 terminal symbols.
Grammar has 3 productions.
nullable(main) = false
nullable(liste(A)) = true
first(main) = EOF A
first(liste(A)) = A
minimal(main) = (* 1 *) EOF
minimal(liste(A)) = (* 0 *) 
follow(main) = #
follow(liste(A)) = EOF
Built an LR(0) automaton with 6 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 6 states.
3 out of 6 states have a default reduction.
2 out of 6 states are represented.
0 out of 7 symbols keep track of their start position.
0 out of 7 symbols keep track of their end position.
2 out of 4 productions exploit shiftreduce optimization.
0 out of 6 states can peek at an error.
24 functions before inlining, 6 functions after inlining.
