File "subiso.mly", line 34, characters 10-17:
Warning: the token ASSIGNS is unused.
File "subiso.mly", line 24, characters 7-11:
Warning: the token PLUS is unused.
File "subiso.mly", line 23, characters 16-20:
Warning: the token TVAR is unused.
Grammar has 4 nonterminal symbols, among which 1 start symbols.
Grammar has 11 terminal symbols.
Grammar has 9 productions.
nullable(type_binding_list) = false
nullable(type_binding) = false
nullable(texpr) = false
nullable(main) = false
first(type_binding_list) = IDENT
first(type_binding) = IDENT
first(texpr) = TYPE LPAR IDENT
first(main) = TYPE LPAR IDENT
minimal(type_binding_list) = (* 3 *) IDENT EQ IDENT
minimal(type_binding) = (* 3 *) IDENT EQ IDENT
minimal(texpr) = (* 1 *) IDENT
minimal(main) = (* 2 *) IDENT Eof
follow(type_binding_list) = TIMES RPAR Eof ARROW AND
follow(type_binding) = TIMES RPAR Eof ARROW AND
follow(texpr) = TIMES RPAR Eof ARROW AND
follow(main) = #
Built an LR(0) automaton with 20 states.
The grammar is not SLR(1) -- 4 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 20 states.
7 shift/reduce conflicts were silently solved.
File "subiso.mly", line 34, characters 0-9:
Warning: the precedence level assigned to ASSIGNS is never useful.
6 out of 20 states have a default reduction.
7 out of 20 states are represented.
0 out of 18 symbols keep track of their start position.
0 out of 18 symbols keep track of their end position.
6 out of 10 productions exploit shiftreduce optimization.
0 out of 20 states can peek at an error.
60 functions before inlining, 12 functions after inlining.
