%start s
%token A
%token B
%token C
%token D
%token L
%token R
%nonassoc B
%nonassoc A
%type <unit> s
%%

s:
  _1 = L _2 = l
    {      ( () )}
| _1 = R _2 = r
    {      ( () )}

l:
  _1 = a _2 = C
    {      ( () )}
| _1 = b _2 = B
    {      ( () )}

r:
  _1 = a _2 = C
    {      ( () )}
| _1 = b _2 = D
    {      ( () )}

a:
  _1 = A _2 = B
    {      ( () )}

b:
  _1 = A
    {      ( () )}

%%


