Grammar has 5 nonterminal symbols, among which 1 start symbols.
Grammar has 6 terminal symbols.
Grammar has 8 productions.
nullable(s) = false
nullable(r) = false
nullable(l) = false
nullable(b) = false
nullable(a) = false
first(s) = R L
first(r) = A
first(l) = A
first(b) = A
first(a) = A
minimal(s) = (* 3 *) L A B
minimal(r) = (* 2 *) A D
minimal(l) = (* 2 *) A B
minimal(b) = (* 1 *) A
minimal(a) = (* 2 *) A B
follow(s) = #
follow(r) = #
follow(l) = #
follow(b) = D B
follow(a) = C
Built an LR(0) automaton with 16 states.
The grammar is not SLR(1) -- 1 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 16 states.
One shift/reduce conflict was silently solved.
Only 15 states remain after resolving shift/reduce conflicts.
File "subtle-conflict-pager.mly", line 27, characters 2-5:
Warning: production a -> A B is never reduced.
Warning: in total, 1 production is never reduced.
8 out of 15 states have a default reduction.
2 out of 15 states are represented.
0 out of 14 symbols keep track of their start position.
0 out of 14 symbols keep track of their end position.
9 out of 9 productions exploit shiftreduce optimization.
0 out of 15 states can peek at an error.
49 functions before inlining, 5 functions after inlining.
