Grammar has 7 nonterminal symbols, among which 1 start symbols.
Grammar has 3 terminal symbols.
Grammar has 8 productions.
nullable(sugar) = false
nullable(option(foo)) = true
nullable(nothing) = true
nullable(main) = false
nullable(hop) = false
nullable(foo) = false
nullable(bar) = false
first(sugar) = C
first(option(foo)) = C
first(nothing) = 
first(main) = A
first(hop) = C B
first(foo) = C
first(bar) = C B
minimal(sugar) = (* 1 *) C
minimal(option(foo)) = (* 0 *) 
minimal(nothing) = (* 0 *) 
minimal(main) = (* 6 *) A B B A B C
minimal(hop) = (* 3 *) B A B
minimal(foo) = (* 1 *) C
minimal(bar) = (* 1 *) B
follow(sugar) = #
follow(option(foo)) = B
follow(nothing) = C B
follow(main) = #
follow(hop) = C
follow(foo) = B
follow(bar) = A
Built an LR(0) automaton with 16 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 16 states.
9 out of 16 states have a default reduction.
2 out of 16 states are represented.
6 out of 13 symbols keep track of their start position.
5 out of 13 symbols keep track of their end position.
6 out of 9 productions exploit shiftreduce optimization.
0 out of 16 states can peek at an error.
54 functions before inlining, 5 functions after inlining.
