File "tilde-used-warning.mly", line 44, characters 2-3:
Warning: one nameless variable has been introduced by a ~ pattern,
yet this sequence does not end in a point-free semantic action <...>.
Perhaps a wildcard pattern _ should be used instead.
File "tilde-used-warning.mly", line 21, characters 6-7:
File "tilde-used-warning.mly", line 21, characters 3-4:
Warning: two nameless variables have been introduced by ~ patterns,
yet this sequence does not end in a point-free semantic action <...>.
Perhaps wildcard patterns _ should be used instead.
File "tilde-used-warning.mly", line 17, characters 6-7:
Warning: one nameless variable has been introduced by a ~ pattern,
yet this sequence does not end in a point-free semantic action <...>.
Perhaps a wildcard pattern _ should be used instead.
%start main
%token <int> A
%token <int> B
%token <int> C
%token <int> D
%token EOF
%type <int> main
%%

fst_paire_A_B__:
  x = A y = B
    {let _1 =                 ( x, y ) in
let (_1_1, _) = _1 in
_1_1}

snd_paire_A_B__:
  x = A y = B
    {let _1 =                 ( x, y ) in
let (_, _1_1) = _1 in
_1_1}

bizarre_fst_paire_A_B__:
  x = A y = B
    {let _1 =                 ( x, y ) in
let (x, _1_1) = _1 in
              (x)}

hop_paire_A_B__:
  x = A y = B
    {let _1 =                 ( x, y ) in
let (_1_1, _1_2) = _1 in
              (())}

a:
  _1 = A
    {_1}

b:
  _1 = B
    {_1}

odd:
  a = a _2 = b
    {_2}

main:
  _1 = hop_paire_A_B__ x = A y = B c = fst_paire_A_B__ _4 = bizarre_fst_paire_A_B__ d = snd_paire_A_B__ _6 = odd _7 = C _8 = D _9 = EOF
    {let _2 =                 ( x, y ) in
let (a, b) = _2 in
let _7_1 = _7 in
_9;
    ( a + b + c + d )}

%%


