File "tptp2cime.mly", line 28, characters 6-9:
Warning: the token EXP is unused.
File "tptp2cime.mly", line 26, characters 11-16:
Warning: the token MINUS is unused.
File "tptp2cime.mly", line 27, characters 6-10:
Warning: the token MULT is unused.
File "tptp2cime.mly", line 12, characters 46-51:
Warning: the token QUOTE is unused.
Grammar has 13 nonterminal symbols, among which 2 start symbols.
Grammar has 17 terminal symbols.
Grammar has 21 productions.
nullable(term_list) = false
nullable(term_line) = false
nullable(term) = false
nullable(literal_list) = false
nullable(literal) = false
nullable(keyword_input_clause) = false
nullable(keyword_include) = false
nullable(ident) = false
nullable(f_name) = false
nullable(donnees) = false
nullable(declaration) = false
nullable(clause) = false
nullable(atom) = false
first(term_list) = VRB PARGAUCHE IDENT
first(term_line) = VRB PARGAUCHE IDENT
first(term) = VRB PARGAUCHE IDENT
first(literal_list) = PLUS MOINS
first(literal) = PLUS MOINS
first(keyword_input_clause) = TOKEN_INPUT_CLAUSE
first(keyword_include) = TOKEN_INCLUDE
first(ident) = IDENT
first(f_name) = FILE_NAME
first(donnees) = TOKEN_INPUT_CLAUSE TOKEN_INCLUDE FIN
first(declaration) = TOKEN_INPUT_CLAUSE TOKEN_INCLUDE
first(clause) = CROGAUCHE
first(atom) = EGAL
minimal(term_list) = (* 1 *) VRB
minimal(term_line) = (* 2 *) VRB POINT_VIRGULE
minimal(term) = (* 1 *) VRB
minimal(literal_list) = (* 7 *) PLUS EGAL PARGAUCHE VRB VIRGULE VRB PARDROITE
minimal(literal) = (* 7 *) PLUS EGAL PARGAUCHE VRB VIRGULE VRB PARDROITE
minimal(keyword_input_clause) = (* 1 *) TOKEN_INPUT_CLAUSE
minimal(keyword_include) = (* 1 *) TOKEN_INCLUDE
minimal(ident) = (* 1 *) IDENT
minimal(f_name) = (* 1 *) FILE_NAME
minimal(donnees) = (* 1 *) FIN
minimal(declaration) = (* 5 *) TOKEN_INCLUDE PARGAUCHE FILE_NAME PARDROITE POINT
minimal(clause) = (* 9 *) CROGAUCHE PLUS EGAL PARGAUCHE VRB VIRGULE VRB PARDROITE CRODROIT
minimal(atom) = (* 6 *) EGAL PARGAUCHE VRB VIRGULE VRB PARDROITE
follow(term_list) = PARDROITE
follow(term_line) = #
follow(term) = VIRGULE POINT_VIRGULE PARDROITE
follow(literal_list) = CRODROIT
follow(literal) = VIRGULE CRODROIT
follow(keyword_input_clause) = PARGAUCHE
follow(keyword_include) = PARGAUCHE
follow(ident) = VIRGULE
follow(f_name) = PARDROITE
follow(donnees) = #
follow(declaration) = TOKEN_INPUT_CLAUSE TOKEN_INCLUDE FIN
follow(clause) = PARDROITE
follow(atom) = VIRGULE CRODROIT
Built an LR(0) automaton with 54 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 54 states.
File "tptp2cime.mly", line 28, characters 0-5:
Warning: the precedence level assigned to EXP is never useful.
File "tptp2cime.mly", line 26, characters 0-5:
Warning: the precedence level assigned to MINUS is never useful.
File "tptp2cime.mly", line 27, characters 0-5:
Warning: the precedence level assigned to MULT is never useful.
File "tptp2cime.mly", line 24, characters 0-9:
Warning: the precedence level assigned to PARDROITE is never useful.
File "tptp2cime.mly", line 26, characters 0-5:
Warning: the precedence level assigned to PLUS is never useful.
File "tptp2cime.mly", line 23, characters 0-5:
Warning: the precedence level assigned to TERMLIST is never useful.
File "tptp2cime.mly", line 83, characters 13-21:
Warning: this %prec declaration is never useful.
20 out of 54 states have a default reduction.
14 out of 54 states are represented.
0 out of 34 symbols keep track of their start position.
0 out of 34 symbols keep track of their end position.
18 out of 23 productions exploit shiftreduce optimization.
0 out of 54 states can peek at an error.
151 functions before inlining, 22 functions after inlining.
