File "<standard.mly>", line 209, characters 8-12:
Warning: symbol list(B) is unreachable from any of the start symbol(s).
Grammar has 2 nonterminal symbols, among which 1 start symbols.
Grammar has 3 terminal symbols.
Grammar has 3 productions.
nullable(main) = false
nullable(list(C)) = true
first(main) = A
first(list(C)) = C
minimal(main) = (* 2 *) A B
minimal(list(C)) = (* 0 *) 
follow(main) = #
follow(list(C)) = #
Built an LR(0) automaton with 7 states.
The grammar is SLR(1).
The construction mode is pager.
Built an LR(1) automaton with 7 states.
Warning: 2 states have an end-of-stream conflict.
File "<standard.mly>", line 209, characters 16-16:
Warning: production list(C) -> is never reduced.
Warning: in total, 1 production is never reduced.
3 out of 7 states have a default reduction.
2 out of 7 states are represented.
0 out of 8 symbols keep track of their start position.
0 out of 8 symbols keep track of their end position.
3 out of 4 productions exploit shiftreduce optimization.
0 out of 7 states can peek at an error.
25 functions before inlining, 4 functions after inlining.
