%token LBRACE RBRACE LBRACKET RBRACKET LPAR RPAR LT GT
%token UNSIGNED BYTE OCTET SHORT LONG
%token DOMSTRING USVSTRING BYTESTRING 
%token UNRESTRICTED FLOAT DOUBLE
%token ANY VOID BOOLEAN OBJECT OR 
%token TRUE FALSE NULL INFINITY MINUSINFINITY NAN
%token GETTER SETTER DELETER LEGACYCALLER
%token STRINGIFIER  
%token QUESTION EQUAL COMMA COLON SEMICOLON ELLIPSIS MINUS DOT
%token MAPLIKE SETLIKE ITERABLE
%token PROMISE RECORD SEQUENCE INCLUDES MIXIN
%token NAMESPACE CALLBACK PARTIAL INTERFACE DICTIONARY ENUM
%token IMPLEMENTS INHERIT ATTRIBUTE TYPEDEF  CONST
%token READONLY REQUIRED STATIC OPTIONAL   
%token DOMEXCEPTION ERROR_       
%token INT8ARRAY INT16ARRAY INT32ARRAY 
%token UINT8ARRAY UINT16ARRAY UINT32ARRAY UINT8CLAMPEDARRAY 
%token FLOAT32ARRAY FLOAT64ARRAY 
%token ARRAYBUFFER DATAVIEW FROZENARRAY

%token<int> INTVAL
%token<float> FLOATVAL
%token<string> IDENTIFIER STRING
%token<char> OTHER
%token EOF

%%