%start exp
%token INT
%token LPAREN
%token MATRIX
%token PLUS
%token RPAREN
%token TENSOR
%token TIMES
%type <int> exp
%%

exp:
  _1 = term
    {       ()}

fa1:
  _1 = LPAREN _2 = exp _3 = RPAREN
    {                    ()}
| _1 = INT
    {      ()}

fa4:
  _1 = MATRIX
    {         ()}
| _1 = LPAREN _2 = exp _3 = RPAREN
    {                    ()}

product:
  _1 = product _2 = TIMES _3 = fa1
    {                    ()}
| _1 = fa1
    {      ()}

tensorproduct:
  _1 = tensorproduct _2 = TENSOR _3 = fa4
    {                           ()}
| _1 = fa4
    {      ()}

term:
  _1 = term _2 = PLUS _3 = product
    {                    ()}
| _1 = term _2 = PLUS _3 = tensorproduct
    {                          ()}
| _1 = product
    {          ()}
| _1 = term _2 = PLUS _3 = tensorproduct
    {                          ()}

%%


