%{
  open Logtk
  module A = Tip_ast
  module Loc = ParseLocation

%}
%start parse
%start parse_list
%start parse_term
%start parse_ty
%token AND
%token ARROW
%token AS
%token ASSERT
%token ASSERT_NOT
%token AT
%token BOOL
%token CASE
%token CHECK_SAT
%token DATA
%token DECLARE_CONST
%token DECLARE_FUN
%token DECLARE_SORT
%token DEFAULT
%token DEFINE_FUN
%token DEFINE_FUNS_REC
%token DEFINE_FUN_REC
%token DISTINCT
%token EOI
%token EQ
%token EXISTS
%token FALSE
%token FORALL
%token FUN
%token <string> IDENT
%token IF
%token LEFT_PAREN
%token LEMMA
%token LET
%token MATCH
%token NOT
%token OR
%token PAR
%token <string> QUOTED
%token RIGHT_PAREN
%token TRUE
%type <Tip_ast.statement> parse
%type <Tip_ast.statement list> parse_list
%type <Tip_ast.term> parse_term
%type <Tip_ast.ty> parse_ty
%%

list_stmt_:
  
    {    ( [] )}
| x = stmt xs = list_stmt_
    {    ( x :: xs )}

list_ty_:
  
    {    ( [] )}
| x = ty xs = list_ty_
    {    ( x :: xs )}

list_typed_var_:
  
    {    ( [] )}
| x = typed_var xs = list_typed_var_
    {    ( x :: xs )}

list_tyvar_:
  
    {    ( [] )}
| x = tyvar xs = list_tyvar_
    {    ( x :: xs )}

nonempty_list_binding_:
  x = binding
    {    ( [ x ] )}
| x = binding xs = nonempty_list_binding_
    {    ( x :: xs )}

nonempty_list_case_:
  x = case
    {    ( [ x ] )}
| x = case xs = nonempty_list_case_
    {    ( x :: xs )}

nonempty_list_cstor_:
  x = cstor
    {    ( [ x ] )}
| x = cstor xs = nonempty_list_cstor_
    {    ( x :: xs )}

nonempty_list_cstor_arg_:
  x = cstor_arg
    {    ( [ x ] )}
| x = cstor_arg xs = nonempty_list_cstor_arg_
    {    ( x :: xs )}

nonempty_list_data_:
  x = data
    {    ( [ x ] )}
| x = data xs = nonempty_list_data_
    {    ( x :: xs )}

nonempty_list_funs_rec_decl_:
  x = funs_rec_decl
    {    ( [ x ] )}
| x = funs_rec_decl xs = nonempty_list_funs_rec_decl_
    {    ( x :: xs )}

nonempty_list_term_:
  x = term
    {    ( [ x ] )}
| x = term xs = nonempty_list_term_
    {    ( x :: xs )}

nonempty_list_ty_:
  x = ty
    {    ( [ x ] )}
| x = ty xs = nonempty_list_ty_
    {    ( x :: xs )}

nonempty_list_typed_var_:
  x = typed_var
    {    ( [ x ] )}
| x = typed_var xs = nonempty_list_typed_var_
    {    ( x :: xs )}

nonempty_list_tyvar_:
  x = tyvar
    {    ( [ x ] )}
| x = tyvar xs = nonempty_list_tyvar_
    {    ( x :: xs )}

nonempty_list_var_:
  x = var
    {    ( [ x ] )}
| x = var xs = nonempty_list_var_
    {    ( x :: xs )}

parse_list:
  l = list_stmt_ _2 = EOI
    {                        (l)}

parse:
  t = stmt _2 = EOI
    {                  ( t )}

parse_term:
  t = term _2 = EOI
    {                       ( t )}

parse_ty:
  t = ty _2 = EOI
    {                   ( t )}

cstor_arg:
  _1 = LEFT_PAREN name = IDENT ty = ty _4 = RIGHT_PAREN
    {                                            ( name, ty )}

cstor:
  _1 = LEFT_PAREN c = IDENT _3 = RIGHT_PAREN
    {                                   ( A.mk_cstor c [] )}
| _1 = LEFT_PAREN c = IDENT l = nonempty_list_cstor_arg_ _4 = RIGHT_PAREN
    {    ( A.mk_cstor c l )}

data:
  _1 = LEFT_PAREN s = IDENT l = nonempty_list_cstor_ _4 = RIGHT_PAREN
    {                                            ( s,l )}

fun_def_mono:
  f = IDENT _2 = LEFT_PAREN args = list_typed_var_ _4 = RIGHT_PAREN ret = ty
    {    ( f, args, ret )}

fun_decl_mono:
  f = IDENT _2 = LEFT_PAREN args = list_ty_ _4 = RIGHT_PAREN ret = ty
    {    ( f, args, ret )}

fun_decl:
  tup = fun_decl_mono
    {                      ( let f, args, ret = tup in [], f, args, ret )}
| _1 = LEFT_PAREN _2 = PAR _3 = LEFT_PAREN tyvars = list_tyvar_ _5 = RIGHT_PAREN _6 = LEFT_PAREN tup = fun_decl_mono _8 = RIGHT_PAREN _9 = RIGHT_PAREN
    {    ( let f, args, ret = tup in tyvars, f, args, ret )}

fun_rec:
  tup = fun_def_mono body = term
    {    (
      let f, args, ret = tup in
      A.mk_fun_rec ~ty_vars:[] f args ret body
    )}
| _1 = LEFT_PAREN _2 = PAR _3 = LEFT_PAREN l = list_tyvar_ _5 = RIGHT_PAREN _6 = LEFT_PAREN tup = fun_def_mono body = term _9 = RIGHT_PAREN _10 = RIGHT_PAREN
    {    (
      let f, args, ret = tup in
      A.mk_fun_rec ~ty_vars:l f args ret body
    )}

funs_rec_decl:
  _1 = LEFT_PAREN tup = fun_def_mono _3 = RIGHT_PAREN
    {    (
      let f, args, ret = tup in
      A.mk_fun_decl ~ty_vars:[] f args ret
    )}
| _1 = LEFT_PAREN _2 = PAR _3 = LEFT_PAREN l = list_tyvar_ _5 = RIGHT_PAREN _6 = LEFT_PAREN tup = fun_def_mono _8 = RIGHT_PAREN _9 = RIGHT_PAREN
    {    (
      let f, args, ret = tup in
      A.mk_fun_decl ~ty_vars:l f args ret
    )}

assert_not:
  _1 = LEFT_PAREN _2 = PAR _3 = LEFT_PAREN tyvars = nonempty_list_tyvar_ _5 = RIGHT_PAREN t = term _7 = RIGHT_PAREN
    {  ( tyvars, t )}
| t = term
    {  ( [], t )}

stmt:
  _1 = LEFT_PAREN _2 = ASSERT t = term _4 = RIGHT_PAREN
    {let _endpos = _endpos__4_ in
let _startpos = _startpos__1_ in
    (
      let loc = Loc.mk_pos _startpos _endpos in
      A.assert_ ~loc t
    )}
| _1 = LEFT_PAREN _2 = LEMMA t = term _4 = RIGHT_PAREN
    {let _endpos = _endpos__4_ in
let _startpos = _startpos__1_ in
    (
      let loc = Loc.mk_pos _startpos _endpos in
      A.lemma ~loc t
    )}
| _1 = LEFT_PAREN _2 = DECLARE_SORT s = IDENT n = IDENT _5 = RIGHT_PAREN
    {let _endpos = _endpos__5_ in
let _startpos = _startpos__1_ in
    (
      let loc = Loc.mk_pos _startpos _endpos in
      try
        let n = int_of_string n in
        A.decl_sort ~loc s ~arity:n
      with Failure _ ->
        A.parse_errorf ~loc "expected arity to be an integer, not `%s`" n
    )}
| _1 = LEFT_PAREN _2 = DATA _3 = LEFT_PAREN vars = list_tyvar_ _5 = RIGHT_PAREN _6 = LEFT_PAREN l = nonempty_list_data_ _8 = RIGHT_PAREN _9 = RIGHT_PAREN
    {let _endpos = _endpos__9_ in
let _startpos = _startpos__1_ in
    (
      let loc = Loc.mk_pos _startpos _endpos in
      A.data ~loc vars l
    )}
| _1 = LEFT_PAREN _2 = DECLARE_FUN tup = fun_decl _4 = RIGHT_PAREN
    {let _endpos = _endpos__4_ in
let _startpos = _startpos__1_ in
    (
      let loc = Loc.mk_pos _startpos _endpos in
      let tyvars, f, args, ret = tup in
      A.decl_fun ~loc ~tyvars f args ret
    )}
| _1 = LEFT_PAREN _2 = DECLARE_CONST f = IDENT ty = ty _5 = RIGHT_PAREN
    {let _endpos = _endpos__5_ in
let _startpos = _startpos__1_ in
    (
      let loc = Loc.mk_pos _startpos _endpos in
      A.decl_fun ~loc ~tyvars:[] f [] ty
    )}
| _1 = LEFT_PAREN _2 = DEFINE_FUN f = fun_rec _4 = RIGHT_PAREN
    {let _endpos = _endpos__4_ in
let _startpos = _startpos__1_ in
    (
      let loc = Loc.mk_pos _startpos _endpos in
      A.fun_rec ~loc f
    )}
| _1 = LEFT_PAREN _2 = DEFINE_FUN_REC f = fun_rec _4 = RIGHT_PAREN
    {let _endpos = _endpos__4_ in
let _startpos = _startpos__1_ in
    (
      let loc = Loc.mk_pos _startpos _endpos in
      A.fun_rec ~loc f
    )}
| _1 = LEFT_PAREN _2 = DEFINE_FUNS_REC _3 = LEFT_PAREN decls = nonempty_list_funs_rec_decl_ _5 = RIGHT_PAREN _6 = LEFT_PAREN bodies = nonempty_list_term_ _8 = RIGHT_PAREN _9 = RIGHT_PAREN
    {let _endpos = _endpos__9_ in
let _startpos = _startpos__1_ in
    (
      let loc = Loc.mk_pos _startpos _endpos in
      A.funs_rec ~loc decls bodies
    )}
| _1 = LEFT_PAREN _2 = ASSERT_NOT tup = assert_not _4 = RIGHT_PAREN
    {let _endpos = _endpos__4_ in
let _startpos = _startpos__1_ in
    (
      let loc = Loc.mk_pos _startpos _endpos in
      let ty_vars, f = tup in
      A.assert_not ~loc ~ty_vars f
    )}
| _1 = LEFT_PAREN _2 = CHECK_SAT _3 = RIGHT_PAREN
    {let _endpos = _endpos__3_ in
let _startpos = _startpos__1_ in
    (
      let loc = Loc.mk_pos _startpos _endpos in
      A.check_sat ~loc ()
    )}
| _1 = error
    {let _endpos = _endpos__1_ in
let _startpos = _startpos__1_ in
    (
      let loc = Loc.mk_pos _startpos _endpos in
      A.parse_errorf ~loc "expected statement"
    )}

var:
  s = IDENT
    {            ( s )}

tyvar:
  s = IDENT
    {            ( s )}

ty:
  _1 = BOOL
    {         ( A.ty_bool )}
| s = IDENT
    {            ( A.ty_const s )}
| _1 = LEFT_PAREN s = IDENT args = nonempty_list_ty_ _4 = RIGHT_PAREN
    {    ( A.ty_app s args )}
| _1 = LEFT_PAREN _2 = ARROW tup = ty_arrow_args _4 = RIGHT_PAREN
    {    (
      let args, ret = tup in
      A.ty_arrow_l args ret )}

ty_arrow_args:
  a = ty ret = ty
    {                ( [a], ret )}
| a = ty tup = ty_arrow_args
    {                           ( a :: fst tup, snd tup )}

typed_var:
  _1 = LEFT_PAREN s = IDENT ty = ty _4 = RIGHT_PAREN
    {                                         ( s, ty )}

case:
  _1 = LEFT_PAREN _2 = CASE c = IDENT rhs = term _5 = RIGHT_PAREN
    {    ( A.Match_case (c, [], rhs) )}
| _1 = LEFT_PAREN _2 = CASE _3 = LEFT_PAREN c = IDENT vars = nonempty_list_var_ _6 = RIGHT_PAREN rhs = term _8 = RIGHT_PAREN
    {    ( A.Match_case (c, vars, rhs) )}
| _1 = LEFT_PAREN _2 = CASE _3 = DEFAULT rhs = term _5 = RIGHT_PAREN
    {    ( A.Match_default rhs )}

binding:
  _1 = LEFT_PAREN v = var t = term _4 = RIGHT_PAREN
    {                                        ( v, t )}

term:
  _1 = TRUE
    {         ( A.true_ )}
| _1 = FALSE
    {          ( A.false_ )}
| s = QUOTED
    {             ( A.const s )}
| s = IDENT
    {            ( A.const s )}
| t = composite_term
    {                     ( t )}
| _1 = error
    {let _endpos = _endpos__1_ in
let _startpos = _startpos__1_ in
    (
      let loc = Loc.mk_pos _startpos _endpos in
      A.parse_errorf ~loc "expected term"
    )}

composite_term:
  _1 = LEFT_PAREN t = term _3 = RIGHT_PAREN
    {                                  ( t )}
| _1 = LEFT_PAREN _2 = IF a = term b = term c = term _6 = RIGHT_PAREN
    {                                                   ( A.if_ a b c )}
| _1 = LEFT_PAREN _2 = OR l = nonempty_list_term_ _4 = RIGHT_PAREN
    {                                      ( A.or_ l )}
| _1 = LEFT_PAREN _2 = AND l = nonempty_list_term_ _4 = RIGHT_PAREN
    {                                       ( A.and_ l )}
| _1 = LEFT_PAREN _2 = NOT t = term _4 = RIGHT_PAREN
    {                                      ( A.not_ t )}
| _1 = LEFT_PAREN _2 = DISTINCT l = nonempty_list_term_ _4 = RIGHT_PAREN
    {                                            ( A.distinct l )}
| _1 = LEFT_PAREN _2 = EQ a = term b = term _5 = RIGHT_PAREN
    {                                            ( A.eq a b )}
| _1 = LEFT_PAREN _2 = ARROW a = term b = term _5 = RIGHT_PAREN
    {                                               ( A.imply a b )}
| _1 = LEFT_PAREN f = IDENT args = nonempty_list_term_ _4 = RIGHT_PAREN
    {                                              ( A.app f args )}
| _1 = LEFT_PAREN f = composite_term args = nonempty_list_term_ _4 = RIGHT_PAREN
    {                                                       ( A.ho_app_l f args )}
| _1 = LEFT_PAREN _2 = AT f = term arg = term _5 = RIGHT_PAREN
    {                                              ( A.ho_app f arg )}
| _1 = LEFT_PAREN _2 = MATCH lhs = term l = nonempty_list_case_ _5 = RIGHT_PAREN
    {    ( A.match_ lhs l )}
| _1 = LEFT_PAREN _2 = FUN _3 = LEFT_PAREN vars = nonempty_list_typed_var_ _5 = RIGHT_PAREN body = term _7 = RIGHT_PAREN
    {    ( A.fun_l vars body )}
| _1 = LEFT_PAREN _2 = LET _3 = LEFT_PAREN l = nonempty_list_binding_ _5 = RIGHT_PAREN r = term _7 = RIGHT_PAREN
    {    ( A.let_ l r )}
| _1 = LEFT_PAREN _2 = AS t = term ty = ty _5 = RIGHT_PAREN
    {    ( A.cast t ~ty )}
| _1 = LEFT_PAREN _2 = FORALL _3 = LEFT_PAREN vars = nonempty_list_typed_var_ _5 = RIGHT_PAREN f = term _7 = RIGHT_PAREN
    {    ( A.forall vars f )}
| _1 = LEFT_PAREN _2 = EXISTS _3 = LEFT_PAREN vars = nonempty_list_typed_var_ _5 = RIGHT_PAREN f = term _7 = RIGHT_PAREN
    {    ( A.exists vars f )}

%%




