File "zyvaall.mly", line 10, characters 61-71:
Warning: the token EQUALEQUAL is unused.
File "zyvaall.mly", line 7, characters 16-22:
Warning: the token STRING is unused.
File "zyvaall.mly", line 16, characters 32-36:
Warning: the token TYPE is unused.
Grammar has 20 nonterminal symbols, among which 1 start symbols.
Grammar has 45 terminal symbols.
Grammar has 62 productions.
nullable(vars) = true
nullable(type_expr) = false
nullable(main) = false
nullable(instruction) = false
nullable(idents) = false
nullable(fonction) = false
nullable(expression) = false
nullable(endtok) = false
nullable(definitions) = true
nullable(declvar) = false
nullable(call_expression) = false
nullable(body) = false
nullable(bloc1) = true
nullable(bloc) = true
nullable(array_expression) = false
nullable(arguments1) = true
nullable(arguments) = true
nullable(args2) = true
nullable(args1) = true
nullable(args) = true
first(vars) = VAR
first(type_expr) = INTEGER BOOLEAN ARRAY
first(main) = PROGRAM
first(instruction) = WRITELN WRITE WHILE READ LPAREN IF IDENT BEGIN ALLOC
first(idents) = IDENT
first(fonction) = PROCEDURE FUNCTION
first(expression) = MINUS LPAREN INT IDENT BOOL ALLOC
first(endtok) = SEMISEMI DOT
first(definitions) = PROCEDURE FUNCTION
first(declvar) = IDENT
first(call_expression) = IDENT ALLOC
first(body) = BEGIN
first(bloc1) = SEMI
first(bloc) = WRITELN WRITE WHILE READ LPAREN IF IDENT BEGIN ALLOC
first(array_expression) = LPAREN IDENT ALLOC
first(arguments1) = COMMA
first(arguments) = MINUS LPAREN INT IDENT BOOL ALLOC
first(args2) = IDENT
first(args1) = SEMI
first(args) = IDENT
minimal(vars) = (* 0 *) 
minimal(type_expr) = (* 1 *) INTEGER
minimal(main) = (* 4 *) PROGRAM BEGIN END SEMISEMI
minimal(instruction) = (* 2 *) BEGIN END
minimal(idents) = (* 1 *) IDENT
minimal(fonction) = (* 7 *) PROCEDURE IDENT LPAREN RPAREN SEMI BEGIN END
minimal(expression) = (* 1 *) INT
minimal(endtok) = (* 1 *) SEMISEMI
minimal(definitions) = (* 0 *) 
minimal(declvar) = (* 3 *) IDENT COLON INTEGER
minimal(call_expression) = (* 3 *) IDENT LPAREN RPAREN
minimal(body) = (* 2 *) BEGIN END
minimal(bloc1) = (* 0 *) 
minimal(bloc) = (* 0 *) 
minimal(array_expression) = (* 1 *) IDENT
minimal(arguments1) = (* 0 *) 
minimal(arguments) = (* 0 *) 
minimal(args2) = (* 0 *) 
minimal(args1) = (* 0 *) 
minimal(args) = (* 0 *) 
follow(vars) = PROCEDURE FUNCTION BEGIN
follow(type_expr) = SEMI RPAREN
follow(main) = #
follow(instruction) = SEMI END ELSE
follow(idents) = COLON
follow(fonction) = SEMI
follow(expression) = TIMES THEN SEMI RPAREN RBRACKET PLUS MINUS LESSGREATER LESSEQUAL LESS GREATEREQUAL GREATER EQUAL END ELSE DO DIV COMMA COLON
follow(endtok) = #
follow(definitions) = BEGIN
follow(declvar) = SEMI RPAREN
follow(call_expression) = TIMES THEN SEMI RPAREN RBRACKET PLUS MINUS LESSGREATER LESSEQUAL LESS LBRACKET GREATEREQUAL GREATER EQUAL END ELSE DO DIV COMMA COLON
follow(body) = SEMISEMI SEMI DOT
follow(bloc1) = END
follow(bloc) = END
follow(array_expression) = LBRACKET
follow(arguments1) = RPAREN
follow(arguments) = RPAREN
follow(args2) = PROCEDURE FUNCTION BEGIN
follow(args1) = RPAREN
follow(args) = RPAREN
Built an LR(0) automaton with 147 states.
The grammar is not SLR(1) -- 12 states have a conflict.
The construction mode is pager.
Built an LR(1) automaton with 147 states.
110 shift/reduce conflicts were silently solved.
File "zyvaall.mly", line 19, characters 0-5:
Warning: the precedence level assigned to EQUALEQUAL is never useful.
36 out of 147 states have a default reduction.
74 out of 147 states are represented.
0 out of 68 symbols keep track of their start position.
0 out of 68 symbols keep track of their end position.
22 out of 63 productions exploit shiftreduce optimization.
0 out of 147 states can peek at an error.
383 functions before inlining, 70 functions after inlining.
